// SPDX-License-Identifier: MIT
pragma solidity ^0.8.9;

import "@openzeppelin/contracts/utils/Strings.sol";

library Footwear {
  using Strings for uint256;

  string constant FOOTWEAR_FOOTWEAR___BLACK_GLADIATOR_SANDALS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAZQTFRFAAAA////pdmf3QAAAAJ0Uk5T/wDltzBKAAAAf0lEQVR42uyTUQrAIAxDn/e/9GCC2jpniwz2EUWQWF5DipTDhQACCCCAAAIIIIAAAgggQBZAf2RX96zXba9xAP3w7uEzB/gMIDsF5yAVInc/TBULD6w0yuigaREAQ9fqx6QRALTqBsC+BAGd5IVtBrjySYhMwYQ+CX/6zpcAAwBGVg+X6K8IkgAAAABJRU5ErkJggg==";

  string constant FOOTWEAR_FOOTWEAR___BLACK_SNEAKERS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAlQTFRFAAAANTU1////eV5mqQAAAAN0Uk5T//8A18oNQQAAAHdJREFUeNrs09EKgCAQRNG7/f9HZyppou5CL0Fj6MPgHKyQ4+VAgAABAgQIECBAgAABAn4LENmxiaFMf+eYYnktQCYM4kDqp4cG1CAKtL5dgG0FZn26ficwExZA17+FOGDP/ixxvoHlwS7x/sJ43NULfOEunAIMAEFDHt/2yl1PAAAAAElFTkSuQmCC";

  string constant FOOTWEAR_FOOTWEAR___BLACK_AND_BLUE_SNEAKERS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFAAAAPlPGNTU1////XUP9KwAAAAR0Uk5T////AEAqqfQAAACFSURBVHja7JPbCoAwDEOT+v//7K46kIyCLwrpUxvoSVYYjpcFAwwwwAADDDDAAAMMMMCAvwFQS44ZQERAjtkE3XZp84DmCE5AaWQEaH/WxTq0RmWA8I+xNhKwaznAfDPvG1DfAfp+bbHMXJUM4Fog0QWuwEQCjpp+TyV3A2yl73ymU4ABABUXLacGOQ2JAAAAAElFTkSuQmCC";

  string constant FOOTWEAR_FOOTWEAR___BLACK_AND_WHITE_SNEAKERS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFAAAARUVFzs7O////PUlx0AAAAAR0Uk5T////AEAqqfQAAAB9SURBVHja7NPBCoAwDAPQpP7/P1u76YZIV/AimI15CM07bIjt5YIAAQIECBAgQIAAAQIE/BZAZSKJgXbWk/cUjG8DgiBQB7zvGwPoQRUYfR4AU+Ehg9nUnwTPq4CPXv1TiLQG0GKYGEnUjSjeAWMhS1av0N8uSb7zL+wCDAB7aS5pEKrMVwAAAABJRU5ErkJggg==";

  string constant FOOTWEAR_FOOTWEAR___BLUE_BASKETBALL_SNEAKERS_WITH_BLACK_STRIPE =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFUGv/AAAAPVLD////BVFE0AAAAAR0Uk5T////AEAqqfQAAACKSURBVHja7NNLDoAgDATQznj/O0tTlW5KStxoMt3wCTwGjHa8LBMgQIAAAQIECBAgQICAnwEwr7TKC1sAyQz4ENsJ4tTc7wIRwIAARltHsPp8TAB1BivOZ2yLK3iXRQZbBJhvsIhgixccN3eAc9wE7h0kYszktR6RUbjW45lof8aoxcSXfqZTgAEAT30t92/H2c4AAAAASUVORK5CYII=";

  string constant FOOTWEAR_FOOTWEAR___BLUE_CROCS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFUGv/QFbNAAAA////e4+K7QAAAAR0Uk5T////AEAqqfQAAACHSURBVHja7NLRDoAgCAVQuP3/P5eAs9LEVo+XhzaYHtCU7WMIAQIECBAgQIAAAQIECBB4CUBKnFaVwDrg+5sQKVYBqKgDtgUOHEWsAYj10fSW5gDqAMen9IRKzXUgyOgAtaPP3BVyQK9n7ivJHcTMbbXNoMMBHv6CBWaV5B1YzCu/PeVdgAEAOP4uMXpWMqcAAAAASUVORK5CYII=";

  string constant FOOTWEAR_FOOTWEAR___BLUE_FLIP_FLOPS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFUGv/AAAAOk65////ucZOEwAAAAR0Uk5T////AEAqqfQAAACGSURBVHja7NLbCsAgDAPQpPv/f571LhQsDPaUgkNCeyZzeD4WBAgQIECAAAECBAgQIEDAzwDjXmYB4hiZc2AO4Ep9ZHIIz4D4/WUBGIBva2dwhgjo0+VpDljdtjQLtLTOD8Fbk4DhmN+EmVw+YhFK2eqm9YjJazQvbt3sUfpH8rpGrV4BBgDn0y7rApH2nwAAAABJRU5ErkJggg==";

  string constant FOOTWEAR_FOOTWEAR___BLUE_HIGH_HEELS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFUGv/AAAAS2Le////23idyAAAAAR0Uk5T////AEAqqfQAAACESURBVHja7NJRDoAgDAPQrt7/zsrGYjS4zPBb/mzoywBxbC4IECBAgAABAgQIECBAgICfgC1iWB8wzJh2Y1gLqPoIoBRQ9ROoBHxewNVjAEyiB8wBRt8CsBR8og4Qi5aACxF1AN/NGN+DkZF5pMYdcLTtsff6JFf99TO+2lW6/yufAgwARaQus8v8p3AAAAAASUVORK5CYII=";

  string constant FOOTWEAR_FOOTWEAR___BLUE_SNEAKERS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFUGv/AAAAPFHB////I6QlLgAAAAR0Uk5T////AEAqqfQAAAB9SURBVHja7NNBDoAgEAPAtv7/zwqCoFFc48XEwgEp7gRCwPSywYABAwYMGDBgwIABAwZ+B7CNPEQhgCUG999RgIDSGlYA6SfhXMBF/dLRgBIwBlBbvZinVRCDQF/fC3FAavVVSOkDQP2G06EUB6rAUXJzjbmNk++8hVmAAQC4WS6hsNZf7QAAAABJRU5ErkJggg==";

  string constant FOOTWEAR_FOOTWEAR___BLUE_TOENAIL_POLISH =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAZQTFRFUGv/////mbDXhwAAAAJ0Uk5T/wDltzBKAAAAOklEQVR42uzRwQkAMAwCQLP/0h2gUCg+c34jB8FMmQAAAAAAAAAAAAAAAPALpO+2L+Q65FFdP+MRYAAP/w/7AEwtVAAAAABJRU5ErkJggg==";

  string constant FOOTWEAR_FOOTWEAR___BLUE_WORK_BOOTS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFAAAAPlPGRUVF////xIywuQAAAAR0Uk5T////AEAqqfQAAACASURBVHja7NPLDoAgDETRC/z/P9tKBU1EJe50uuE5J6QJlJeFAAECBAgQIECAAAECBPwNIFllKzvGR18zA+QKEICDeQKwfHaACthgq4HAMJ/i2cR0IHCZ3wMDgbMGtvwB8G3ugX4fag9Ye9DFBy+IfNmA0gQe9SDqbu8zf2ERYADm5i4zkCr+QgAAAABJRU5ErkJggg==";

  string constant FOOTWEAR_FOOTWEAR___BLUE_AND_GRAY_BASKETBALL_SNEAKERS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFUGv/AAAAPDw8////NgpYqAAAAAR0Uk5T////AEAqqfQAAACESURBVHja7NNRDoAgDAPQrt7/zgLbDCZCIH5pur8R9tZgxPGyIECAAAECBAgQIECAAAEfAwy1ulu1bAsg2QO1te0EAMuQMZoNwAPcgGEETPaXqQZkhEcBg/30rQ5E85gBwwB1IoEMsQjkwjafAuNJlt6AMR737TpY/gpek4Nf/UynAAMA4HguaaDOOR8AAAAASUVORK5CYII=";

  string constant FOOTWEAR_FOOTWEAR___PINK_HIGH_HEELS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF6Jr/AAAAyqLV////Ci+i2QAAAAR0Uk5T////AEAqqfQAAACESURBVHja7NJRDoAgDAPQrt7/zsrGYjS4zPBb/mzoywBxbC4IECBAgAABAgQIECBAgICfgC1iWB8wzJh2Y1gLqPoIoBRQ9ROoBHxewNVjAEyiB8wBRt8CsBR8og4Qi5aACxF1AN/NGN+DkZF5pMYdcLTtsff6JFf99TO+2lW6/yufAgwARaQus8v8p3AAAAAASUVORK5CYII=";

  string constant FOOTWEAR_FOOTWEAR___PINK_TOENAIL_POLISH =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAZQTFRF6Jr/////Gn0/cgAAAAJ0Uk5T/wDltzBKAAAAOklEQVR42uzRwQkAMAwCQLP/0h2gUCg+c34jB8FMmQAAAAAAAAAAAAAAAPALpO+2L+Q65FFdP+MRYAAP/w/7AEwtVAAAAABJRU5ErkJggg==";

  string constant FOOTWEAR_FOOTWEAR___PINK_WORK_BOOTS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF4JzzQ0NDAAAA////YFrTTQAAAAR0Uk5T////AEAqqfQAAACFSURBVHja7NNRDoAgDAPQrtz/zg5FgggC8cfE7kNxoS/KIsLLggABAgQIECBAgAABAgT8DSC8zIu+jvf4zBXA7oAtAJ63GrCOgG4e6bWZlh0Bj/kS6AhoHWDOX4DY5hgo9ldTQHMUaA7gyPMEmAXjxCdYKgbu2/1a9GYOMdWo95V/YRNgAGtrLe9GZ97wAAAAAElFTkSuQmCC";

  string constant FOOTWEAR_FOOTWEAR___RED_BASKETBALL_SNEAKERS_WITH_WHITE_STRIPE =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF/2tyAAAAwz1F////4ACcGgAAAAR0Uk5T////AEAqqfQAAAB9SURBVHja7NNRCoAwDAPQNt7/zlI6pRuutPijkHy5MV/DRDleRggQIECAAAECBAgQIEDgZ4CKJZyyaAsAEAFbaruBT43PVcALTMC2gmTz5wbPHWQzHyuATQdJCywN+gAMQBu43gDU1whe6RLh0XFe743yZ/QkG1/6mU4BBgAm3S3jNWLTiAAAAABJRU5ErkJggg==";

  string constant FOOTWEAR_FOOTWEAR___RED_CROCS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF/1BZzUBIAAAA////KQANqwAAAAR0Uk5T////AEAqqfQAAACHSURBVHja7NLRDoAgCAVQuP3/P5eAs9LEVo+XhzaYHtCU7WMIAQIECBAgQIAAAQIECBB4CUBKnFaVwDrg+5sQKVYBqKgDtgUOHEWsAYj10fSW5gDqAMen9IRKzXUgyOgAtaPP3BVyQK9n7ivJHcTMbbXNoMMBHv6CBWaV5B1YzCu/PeVdgAEAOP4uMXpWMqcAAAAASUVORK5CYII=";

  string constant FOOTWEAR_FOOTWEAR___RED_FLIP_FLOPS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF/1BZAAAAuTpB////yw3NhQAAAAR0Uk5T////AEAqqfQAAACGSURBVHja7NLbCsAgDAPQpPv/f571LhQsDPaUgkNCeyZzeD4WBAgQIECAAAECBAgQIEDAzwDjXmYB4hiZc2AO4Ep9ZHIIz4D4/WUBGIBva2dwhgjo0+VpDljdtjQLtLTOD8Fbk4DhmN+EmVw+YhFK2eqm9YjJazQvbt3sUfpH8rpGrV4BBgDn0y7rApH2nwAAAABJRU5ErkJggg==";

  string constant FOOTWEAR_FOOTWEAR___RED_HIGH_HEELS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAlQTFRF/1BZAAAA////KfmcOwAAAAN0Uk5T//8A18oNQQAAAHdJREFUeNrs0lEKwCAMA9Bk9z+0qC3O0ZWKv/EzmGdR8VwuCBAgQIAAAQIECBAgQICAQ4BBDNYBAqvkGGIBaX8CqYC0b0Am4PcCgAUYUQNsgFGfAF2IRggBW3TgFZ0AvTyCPStdYj9928s5BYvP+Gln6f1XbgIMAMdTHwvim8UAAAAAAElFTkSuQmCC";

  string constant FOOTWEAR_FOOTWEAR___RED_TOENAIL_POLISH =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAZQTFRF/1BZ////zwu78gAAAAJ0Uk5T/wDltzBKAAAAOklEQVR42uzRwQkAMAwCQLP/0h2gUCg+c34jB8FMmQAAAAAAAAAAAAAAAPALpO+2L+Q65FFdP+MRYAAP/w/7AEwtVAAAAABJRU5ErkJggg==";

  string constant FOOTWEAR_FOOTWEAR___RED_WORK_BOOTS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF////xj5GAAAA////hHNfkQAAAAR0Uk5T////AEAqqfQAAACFSURBVHja7NNRDoAgDAPQUu5/Z4ciQWQC8cfE7kNxoS/KIuLLggABAgQIECBAgAABAgT8DWCwghVtne7pmSsA7gAWAMujBeAIcPMhvzbz0hHwmK8BR0DvAEv+AqQ2x0C1v5lC6I4C3QEceZ4AiwBOfAJyMXLfbteqN3OIuUa9r/wLmwADAKwqLhHie0YmAAAAAElFTkSuQmCC";

  string constant FOOTWEAR_FOOTWEAR___RED_AND_GRAY_BASKETBALL_SNEAKERS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF/1BZAAAA0dHR////ze5X2AAAAAR0Uk5T////AEAqqfQAAACGSURBVHja7NPRCoAwCAXQq/3/PzdTY8EcG70UXN8MPV6KcLwsECBAgAABAgQIECBAgMDPAIFVN2UlW4Cq9oC1sp0A0LYkGs0G4AEeQBkBk/tt6wIywlBAcV/9qgPRDDOgDGAbCWSIRSAP9oCnWAXuklG/8BJzPOZF6v3iM3pNHnzpZzoFGADLZS5L1UvYJAAAAABJRU5ErkJggg==";

  string constant FOOTWEAR_FOOTWEAR___STEPPED_IN_A_PUMPKIN =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF2IdFxnErAAAA////LzM4xAAAAAR0Uk5T////AEAqqfQAAABjSURBVHja7NMxDoAwDENR29z/zrQpbAwoFWL5VlY/KVKiYzMCAAAAAAAAAAAAAAAAGEn2AElpAbFW34+CXvQrnuP0AF/1LmDdxhYwjV+AIVR5LuC07iCDqCTdQ8rKN79wCjAAjrgu+RwA0+0AAAAASUVORK5CYII=";

  string constant FOOTWEAR_FOOTWEAR___TAN_COWBOY_BOOTS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFnIFNiW8+AAAA////ushiWgAAAAR0Uk5T////AEAqqfQAAACUSURBVHja7NPBDoAgDAPQdv7/P6swFMMQ0YuH7qDJQp8DIpaPBQECBAgQIECAAAECBAiYAwAMGveAkdcAQNoMAC//eCqbncBDjr2ZgAXg7ATGnGcGmIV4BMR5tgBjAd18s4VYQLR/ojr540YcHAHVeqaTt/2N7l32gS1dADuFBwBL2WJp+fasm+MzKDVs/uR3XgUYABTXLYHfBa9KAAAAAElFTkSuQmCC";

  string constant FOOTWEAR_FOOTWEAR___TAN_WORK_BOOTS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFnIFNiW8+AAAA////ushiWgAAAAR0Uk5T////AEAqqfQAAACFSURBVHja7NNRDoAgDAPQrtz/zg5FgggC8cfE7kNxoS/KIsLLggABAgQIECBAgAABAgT8DSC8zIu+jvf4zBXA7oAtAJ63GrCOgG4e6bWZlh0Bj/kS6AhoHWDOX4DY5hgo9ldTQHMUaA7gyPMEmAXjxCdYKgbu2/1a9GYOMdWo95V/YRNgAGtrLe9GZ97wAAAAAElFTkSuQmCC";

  string constant FOOTWEAR_FOOTWEAR___WATERMELON_SHOES =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFU+9bAAAA4YGA////N0xUmAAAAAR0Uk5T////AEAqqfQAAACJSURBVHja7NNRDoAgDAPQdt7/zjqHiHGQJX7axagl9P2I2D4OBAgQIECAAAECBAgQIOBnAFlfzQCir/K82lawBhBm/ZVHasEsE5D12QSveIzAVEgB881+gwM9lwFYqyCAIReBqPgzgDuXgWv4zpWvMAVYPgdjgav+5CQ+C1z0J/8CYybxMbsAAwBW8y3SEXl2fQAAAABJRU5ErkJggg==";

  string constant FOOTWEAR_FOOTWEAR___WHITE_SNEAKERS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF////AAAAysrK////8hTnlQAAAAR0Uk5T////AEAqqfQAAAB4SURBVHja7NPBDoAwCAPQgv//zzqcyhJkGC8mlnlYqn2HLWJ5OSBAgAABAgQIECBAgACB3wJiz7GtA9JjyLivAgJoe4cdQPtIEQu46W8LF9ADqQGurw3QVIgB13fCE8D1T6EO6NiPkskhqo1kyeQabfLkO//CKsAAfD8uc7Djs80AAAAASUVORK5CYII=";

  string constant FOOTWEAR_FOOTWEAR___WHITE_AND_RED_SNEAKERS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF+Pj4AAAAxj5G////IJI/hQAAAAR0Uk5T////AEAqqfQAAAB4SURBVHja7NNRCoAwDAPQNt7/zlrqtD/NBoIoJF+jmMdW0LaHMQECBAgQIECAAAECBAj4GeAWKV9F/H0gS/W8CpwdDABEMNZHAmCC0f51g16w/v24d4B+DwSIYgAogyXgKgCeA1RwDhyFjHs3mSxxhI6+8zPtAgwA1Y4ts6ftldUAAAAASUVORK5CYII=";

  string constant FOOTWEAR_FOOTWEAR___YELLOW_RAIN_BOOTS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF7Mg/AAAAz68x////oARwjwAAAAR0Uk5T////AEAqqfQAAABjSURBVHja7NPLCoAwEEPRmfj//yyDDyxoRhBc6M2qBHIWLY3pYQIAAAAAAAAAAAAAAOBlIGNJDsdfAdvoCFwIYfcqQFaIbt8JDtA62IXbgIb9SdHegSppivYVKrb40m+cBRgAm+suCeR/MroAAAAASUVORK5CYII=";

  function getAsset(uint256 headNum) external pure returns (string memory) {
    if (headNum == 0) {
      return FOOTWEAR_FOOTWEAR___BLACK_GLADIATOR_SANDALS;
    } else if (headNum == 1) {
      return FOOTWEAR_FOOTWEAR___BLACK_SNEAKERS;
    } else if (headNum == 2) {
      return FOOTWEAR_FOOTWEAR___BLACK_AND_BLUE_SNEAKERS;
    } else if (headNum == 3) {
      return FOOTWEAR_FOOTWEAR___BLACK_AND_WHITE_SNEAKERS;
    } else if (headNum == 4) {
      return FOOTWEAR_FOOTWEAR___BLUE_BASKETBALL_SNEAKERS_WITH_BLACK_STRIPE;
    } else if (headNum == 5) {
      return FOOTWEAR_FOOTWEAR___BLUE_CROCS;
    } else if (headNum == 6) {
      return FOOTWEAR_FOOTWEAR___BLUE_FLIP_FLOPS;
    } else if (headNum == 7) {
      return FOOTWEAR_FOOTWEAR___BLUE_HIGH_HEELS;
    } else if (headNum == 8) {
      return FOOTWEAR_FOOTWEAR___BLUE_SNEAKERS;
    } else if (headNum == 9) {
      return FOOTWEAR_FOOTWEAR___BLUE_TOENAIL_POLISH;
    } else if (headNum == 10) {
      return FOOTWEAR_FOOTWEAR___BLUE_WORK_BOOTS;
    } else if (headNum == 11) {
      return FOOTWEAR_FOOTWEAR___BLUE_AND_GRAY_BASKETBALL_SNEAKERS;
    } else if (headNum == 12) {
      return FOOTWEAR_FOOTWEAR___PINK_HIGH_HEELS;
    } else if (headNum == 13) {
      return FOOTWEAR_FOOTWEAR___PINK_TOENAIL_POLISH;
    } else if (headNum == 14) {
      return FOOTWEAR_FOOTWEAR___PINK_WORK_BOOTS;
    } else if (headNum == 15) {
      return FOOTWEAR_FOOTWEAR___RED_BASKETBALL_SNEAKERS_WITH_WHITE_STRIPE;
    } else if (headNum == 16) {
      return FOOTWEAR_FOOTWEAR___RED_CROCS;
    } else if (headNum == 17) {
      return FOOTWEAR_FOOTWEAR___RED_FLIP_FLOPS;
    } else if (headNum == 18) {
      return FOOTWEAR_FOOTWEAR___RED_HIGH_HEELS;
    } else if (headNum == 19) {
      return FOOTWEAR_FOOTWEAR___RED_TOENAIL_POLISH;
    } else if (headNum == 20) {
      return FOOTWEAR_FOOTWEAR___RED_WORK_BOOTS;
    } else if (headNum == 21) {
      return FOOTWEAR_FOOTWEAR___RED_AND_GRAY_BASKETBALL_SNEAKERS;
    } else if (headNum == 22) {
      return FOOTWEAR_FOOTWEAR___STEPPED_IN_A_PUMPKIN;
    } else if (headNum == 23) {
      return FOOTWEAR_FOOTWEAR___TAN_COWBOY_BOOTS;
    } else if (headNum == 24) {
      return FOOTWEAR_FOOTWEAR___TAN_WORK_BOOTS;
    } else if (headNum == 25) {
      return FOOTWEAR_FOOTWEAR___WATERMELON_SHOES;
    } else if (headNum == 26) {
      return FOOTWEAR_FOOTWEAR___WHITE_SNEAKERS;
    } else if (headNum == 27) {
      return FOOTWEAR_FOOTWEAR___WHITE_AND_RED_SNEAKERS;
    } else if (headNum == 28) {
      return FOOTWEAR_FOOTWEAR___YELLOW_RAIN_BOOTS;
    }
    return FOOTWEAR_FOOTWEAR___BLACK_GLADIATOR_SANDALS;
  }
}

// SPDX-License-Identifier: MIT
// OpenZeppelin Contracts (last updated v4.7.0) (utils/Strings.sol)

pragma solidity ^0.8.0;

/**
 * @dev String operations.
 */
library Strings {
    bytes16 private constant _HEX_SYMBOLS = "0123456789abcdef";
    uint8 private constant _ADDRESS_LENGTH = 20;

    /**
     * @dev Converts a `uint256` to its ASCII `string` decimal representation.
     */
    function toString(uint256 value) internal pure returns (string memory) {
        // Inspired by OraclizeAPI's implementation - MIT licence
        // https://github.com/oraclize/ethereum-api/blob/b42146b063c7d6ee1358846c198246239e9360e8/oraclizeAPI_0.4.25.sol

        if (value == 0) {
            return "0";
        }
        uint256 temp = value;
        uint256 digits;
        while (temp != 0) {
            digits++;
            temp /= 10;
        }
        bytes memory buffer = new bytes(digits);
        while (value != 0) {
            digits -= 1;
            buffer[digits] = bytes1(uint8(48 + uint256(value % 10)));
            value /= 10;
        }
        return string(buffer);
    }

    /**
     * @dev Converts a `uint256` to its ASCII `string` hexadecimal representation.
     */
    function toHexString(uint256 value) internal pure returns (string memory) {
        if (value == 0) {
            return "0x00";
        }
        uint256 temp = value;
        uint256 length = 0;
        while (temp != 0) {
            length++;
            temp >>= 8;
        }
        return toHexString(value, length);
    }

    /**
     * @dev Converts a `uint256` to its ASCII `string` hexadecimal representation with fixed length.
     */
    function toHexString(uint256 value, uint256 length) internal pure returns (string memory) {
        bytes memory buffer = new bytes(2 * length + 2);
        buffer[0] = "0";
        buffer[1] = "x";
        for (uint256 i = 2 * length + 1; i > 1; --i) {
            buffer[i] = _HEX_SYMBOLS[value & 0xf];
            value >>= 4;
        }
        require(value == 0, "Strings: hex length insufficient");
        return string(buffer);
    }

    /**
     * @dev Converts an `address` with fixed length of 20 bytes to its not checksummed ASCII `string` hexadecimal representation.
     */
    function toHexString(address addr) internal pure returns (string memory) {
        return toHexString(uint256(uint160(addr)), _ADDRESS_LENGTH);
    }
}