// SPDX-License-Identifier: MIT
pragma solidity ^0.8.9;

import "@openzeppelin/contracts/utils/Strings.sol";

library ClothingB {
  using Strings for uint256;

  string constant CLOTHING_SHIRT___DUSTY_MAROON_MINERS_GARB =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFV0lJXSkpZDg4////urRkUQAAAAR0Uk5T////AEAqqfQAAADuSURBVHja7JXhDsIgDISv5/u/s5R2dIt1gP4yFrOZkd3X46iIx5cDBShAAQpQgB8AyHTiFiBtzGZuACIARBgzVD1TBNLyVAK9KLpY7xnhFSBWTi20j5mH6yErAH1vlDTr1CVB73OAVzIfRqE/AYmFBID+qgTgMlYcYAgPJzSp9FBmAMJDY5TlugPbQ570/k3kBGQZum3vhVgUVgGqA0aCNCmx7ODUO4cFNUMk7fx+CThtxREq5w6cwWjCSzNsHCgSKKQ/gikgwuiB7gOaCCOMfQddSDAC3Af0JMfFD07lpvKdqH+mAhSgAP8BeAowAGNnK9qnBstyAAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___DUSTY_NAVY_MINERS_GARB =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFMDNVQENYUVJb////P3zpEgAAAAR0Uk5T////AEAqqfQAAADoSURBVHja7JXhDsIgDITvzvd/Z6Fl6zRs1PnLWBIXIdzX4+oQjy8HClCAAhSgAD8AwO2NvtrGauUCAJBsj1hh13OKwLQ81QgcRWliYyAD8K2Uq9y8hl7IAPq+JhDG6KdRm6n5SgB2zfYlZuTEwgRgxaL628g42OtHbZcCTAC4JXCozryD0cODfjOjOQEnGZqLrfsWS5xkDeg7Q22z8JACxG8nDkB/5I+gF//cW5J6F17bqPMeXFwoCBRn/V8DIgwL9HOAII0cecOBpyhLQGeXyQIAHj+8cSv399cjrH+mAhSgAP8BeAowAHUvKo3TiLgkAAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___GRASS_SKIRT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFd6N5bpZwAAAA////lmA8jwAAAAR0Uk5T////AEAqqfQAAACESURBVHja7NPbCoAgEATQmfH//zkXQxEU1noSpqUbNselDOXnBgMGDBgwYMCAAQMGrgIIYneXAVATjFgU2uUBoJZAP7RSFhCnHDukHKA+d9sHt+oBq/63pVwH6on5BKVfosrIjumV/4xiDHH0Hg9ChyuRdVAxL1/101KWf2cDdwCPAAMAME0uEEJObu0AAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___LEDERHOSEN =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF6sU3dV83AAAA////ltIfUgAAAAR0Uk5T////AEAqqfQAAABfSURBVHja7NYxCsAwDENRS73/nQsZWko8JO5gWr68aHpg8OA4XiYAAAAAAADWAKV1B9DcABoAjdQBxRjVgUvoWoE7+DqgKXuAtCqkgJXGAE2AXQFuwc/OfwDwX+AUYABU2y2HN3xQjwAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___MAGICIAN_UNIFORM_WITH_BLUE_CAPE =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFS2Tv/f39CQkJ////AyuzQAAAAAR0Uk5T////AEAqqfQAAADPSURBVHja7NbLEoMwCAXQG/z/f/aFJhAkqHXRGdgUrZwiNRkxvQwkkEACCSTwBwANT/gALeEdjwAyIw4cFUV82AK83y8cXg9w+1f1lvABIOam6g3BAXAC3hSuAWAXNuVxB6TuIADQIBKIAKV7/Np1QeEdKbSWvwSC24k1Ax8IDBFX/8V2eQRYogpttn4zBIgBLhRJDMABTPW+ObkL1IFxchvoro0DaIpE/Q8A8gFSgM77FqDr5XPbAjs+AlSL4gTvtK9eMPpVlS9ZCawxCzAABn8sL+cocM4AAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___MAGICIAN_UNIFORM_WITH_RED_CAPE =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF4EZO+vr6AAAA////bjHSwgAAAAR0Uk5T////AEAqqfQAAADWSURBVHja7NbhEsIgCABgxPd/5+ZwGsgQWv3oDv6Ednyi2W5QHwYkkEACCSTwBwBuJ2wASynv42OIEaDVL4F+4KpH9qELYK2PPawewOyf16vCDwB2gLxeEwwABmCdwj0AQMKpfNxB4TvwAOodMoQEVEBeP3Yp0f1EkkD4kfYUWHfvBdAGHIcIej0J4AGO0IH2zRZAAupcdmY+AAjohSwJAnUc3JVEgTp+uZ4EgDnL0q8AaAMoAJmvLYCsp3+dBhC+A0SLbKINlj0EXzCWFfIlK4EzXgIMAHZRKlpJQWTyAAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___NAKEY =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAZQTFRF////AAAAVcLTfgAAAAF0Uk5TAEDm2GYAAAAdSURBVHja7MGBAAAAAMOg+VPf4ARVAQAAAHwTYAAQQAABpAJfkQAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___NODE_OPERATORS_VEST =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF/40Szs7O9f+I////uL3xVwAAAAR0Uk5T////AEAqqfQAAABwSURBVHja7NXRCsAgCAXQq/3/P08XtMVgmIPcw71PRnQQfQjtY0CAAAECBAhEAKiI9tIr5ADMVQVg1ygGPATKAFW9ADssA+KvRkQSwJz9wNn3SGIGNrtbsLwFPLIZAKLCywxCDfBjIUCAwI+AQ4ABAJbLLS7e3N1BAAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___ORANGE_INFLATABLE_WATER_WINGS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF13swTmfwAAAA////AIPRhgAAAAR0Uk5T////AEAqqfQAAABlSURBVHja7NNBCsAgDETROL3/nduF1ViKsxAXLT+4GpIHGoxjsQIAAAAAAODvgGbt8oCi1qOvlhzQ5kehp9oMXPPlPiPQYs2B0ivnKd4NhHsDc4UkvK/RboHPBAAAAADwceAUYAAviS47vQJjZQAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___ORANGE_PRISON_UNIFORM =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF2Hww////AAAA////Dh5QBwAAAAR0Uk5T////AEAqqfQAAACLSURBVHja7NbRCoAgDAXQ7fb//1z0MArn5rIepLsHEeEeRGUo22QJAQIECBD4AQAgWQgBQJzyCQ9w4ycxBnTzriCVvCe8D4R5R8gBhSpmACigUzs4NlAAkiNoBQIfALbeVLEjrQ94x1fpieMdjUD3Fi4tDHE+A3CfLwTYYzTg4f8ANvCPRCCsXYABAMKMJ26oEyGzAAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___PINK_TUTU =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF6Jr/yqLVAAAA////nUtfkwAAAAR0Uk5T////AEAqqfQAAAB1SURBVHja7NPbDoAgDAPQrv7/P3vFjDiSqk+aEnDhYaeRAKaXAwYMGDBgwIABAwYMfAoIIEY7BUBgbWoFY6EE2LpPYCtUAabYNGsBVf8ley8ARaDPTYvqL1TA8qF8iIyu8YjnzYuUgcc3kaxz/RoN/A6YBRgA8LsuBJvLa3cAAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___PINK_AND_TEAL_DEFI_LENDING_TANKTOP =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFU9rs7Kz/qYK1////0tMTyAAAAAR0Uk5T////AEAqqfQAAAB+SURBVHja7NXBCoAwDAPQNPv/f9aJuNmD0FZEMb31kAftKEMrFgQIECBAwB8AGi/aR4BTZG2iQPNAeImwEaJlgC5wnyYHoOe4xZMAbKoUgDKAFwAoATcscSh5AJURpk1WASZf4RDCADzACoB+VCWAccAR1M8kQICADwCLAAMAYkEtOym5jCwAAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___RED_BEAR_LOVE_SHIRT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF+E5XAAAA66f/////yKGIgAAAAAR0Uk5T////AEAqqfQAAACwSURBVHja7NXBDoMwDANQJ/v/f16adqMaqWjCDhxsISEk/AQlAF43AwIECBAg8HxAWpaHl4AIWqazWmIiAno9iOwBy34oINOPBKT6gYBc/yz8HZgEtcz7vVv4PnXr2fBY03dDyIxyB0YMSL8L7cptIn3TIiAfQOrAnVvw1ZPOKIpAb1cBF3wpFTUAYxUUVcCHcAxRFvgZ57VwAeB4DYrAkfRnfavOXxsBAgSeBLwFGADVbis9JdwUCQAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___RED_BEAR_MARKET_SHIRT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF/1BZtUpDAAAA////8bwkVAAAAAR0Uk5T////AEAqqfQAAACYSURBVHja7NVLDoAgDATQTr3/nRUUtLF+Cgs1ziQuTJgXQVAZOiMECBAgQOD9gKYc3l4CqpKyGZXiEx4w153oPeCw7woS6XuChPqOILH+XjgB0ARUAVbA3SmUt458Ya0CZmdcb2VZhFkRhM9CefJOoC5FM1DX41Egz+OHgD0I02ZAFDAC0ADA9hH+rMOEvzYCBAh8ABgFGABpDCrhHGjZSAAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___RED_BULL_MARKET_SHIRT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF+U5XUf9aAAAA////90KP8wAAAAR0Uk5T////AEAqqfQAAACGSURBVHja7NXhCoAgDATg23r/dw6T0nLazKCE2x9xcB84BmIZLBAgQIAAgf8DGqp6vQVUESo1JFxtwgJiPC+Jh/qAMr8DlgBP/gAMAV15Q4AjnwOF8DrQGqHrCVuvCvSscgpLLesBBEOADAL58D4BTvmnQ5wZKBd6OuBK8GsjQIDABMAqwABsmCqyMR9fiwAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___RED_DRESS_WITH_WHITE_DOTS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF/2ZuzUBIAAAA////Y/AVtQAAAAR0Uk5T////AEAqqfQAAACuSURBVHja7NYLCoQwDATQyez976x2lXxaanBZEUnQSkvzYquC+PwYKKCAAgoooIDbAOTnvBSAiSsAkBLeDAA5oYAnA0BS+BcAZIXBMDVHgsEEQB6Zsh1ioLUlT4AtXUy+A1o/EvDpmqyAdtolEHDpossWhPJmxBIweydwtWw/DnEEiC0zO9eGwyX4onAgxD5UjjeRLbrbdeW/c6Yv0s5EoE+dfwvsov5QCpjEIsAAKSUpMkaxWAgAAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___RED_DRESS_WITH_WHITE_LACE =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF/2FpzUBIAAAA////qBcbTwAAAAR0Uk5T////AEAqqfQAAACwSURBVHja7NaNCoMwDEbRm+z933mrc2uSlhocG0MS/KHF77RWBbl9WBRQQAEFFFDAzwDy11wUwNQZAFLClQHICQX8MwBJ4VsAZIVJt/aMBEMTgOorKW0TAz2OqgdAi4vJO2BrRwIf7+EO9MZ2CgQu7vP7PvZYArN2ghvLtmOXzgCB2QTGvc1hegt+UBz4XlAJjxO3hq2G6brhn9csX6SdicAYXX8LOlT9oRSwqLsAAwA6rCk3E+qmcgAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___RED_DRESS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF/1BZ3ktTAAAA////hP6nfQAAAAR0Uk5T////AEAqqfQAAACASURBVHja7NXRCoAgDIXhf+v93zkxKMMFswi9OLsZ6M6H6IVsHwsBAgQIECAgBzA6tR5w7bHNArj34TvgSJZmbwDasq8AEwDICQJWBiAp/AVAVgiXPcqbeRZ4yMcCA/lQ6AEvg2E6FqITuNfhPu2efYU6aE2di/qdBQj4C9gFGABNgivdwtBkGwAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___RED_ETH_SHIRT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF/1BZxj5GAAAA////QrBriQAAAAR0Uk5T////AEAqqfQAAACmSURBVHja7NXZDoUwCARQpv7/P5uKS+0ipZqoyfBmcucEWvHKdLOEAAECBAh8Hwixmo8mEILESn4Vq07UAI1XKvQBzXxVECMPGIJYeUuQ6/4LoBDEbMBooTkC9vwioHeE7dYhZ0BP0/MqJ/mYhXsXngDSQxzsQK/xzggrMjqCRvUaXzmDB4BjF9wAsnUGvADyrXIDyJbS/VnHqfjXRoAAgR8AswADAJ2vKy0LNfteAAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___RED_FANNY_PACK =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF/1BZ9vb23ktT////OxgMMgAAAAR0Uk5T////AEAqqfQAAABJSURBVHja7NJBCgAgCAXRn93/zkllexNczewieoikWUwAAAAAAAAAAAAAfcDYKbJzTgNWBl5pIC7vAP9L9MceHwkAAKAHWAIMAMqKL1kZ5yG7AAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___RED_HOOLA_HOOP =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAlQTFRFAAAA/1BZ////6Q/r/QAAAAN0Uk5T//8A18oNQQAAAHxJREFUeNrs08sOgCAMRNFb//+j1SIRjbVNiCvHHaE9Di+WyQ8BAgQIECBAgAABfwCYawDLAIMYwCxPcKvhMkdhS7aUxEBp20LAI5D9n3gJvsDdIGz2grdTaSWOjEwbHzPZuffSzlzHxZs4tj0lKt68M4GeswAB3wOrAAMAE1AfEcd7K6MAAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___RED_HOOT_SHIRT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF/1BZAAAAwj1E////LxYcpQAAAAR0Uk5T////AEAqqfQAAACTSURBVHja7NULCoAgEATQdbr/nUsr8bOiW4EJM1EQNK+PhrK9jBAgQIAAgf8Dzqd52gWcE5/kKh+d0ICzrsSNAc2+Koilrwli6iuC2Pq18DkQBeQ9jL7CPeoo7wxkM6M/lXEYQNxh/hcCcG3+MAHA9CdIPuIjoBzF9QBUE9EKoOjbAWR1MxCIJFzaCBAgsACwCzAAco0rPU9WJtwAAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___RED_JESTERS_COLLAR =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF/lVYzUBIAAAA////LDCGuAAAAAR0Uk5T////AEAqqfQAAAB/SURBVHja7NPdCoAgFAPgbb7/O+dfgmV1pNsdCHGwTxBD+jkwYMCAAQMfgBTLngBhEQOKArl/F0qmGFD7V6FligC9PxEj0hawmBBAgLx3S0aFLpHMX61wVMGWh4CSsVbSWW077LzEfhzbujz8HcC8wr+zAQMGDBgwYCA6hwADAJymLlxLBQJrAAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___RED_KNIT_SWEATER =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF1URL////ra5T////v5wGVAAAAAR0Uk5T////AEAqqfQAAACaSURBVHja7NXdCoAwCAXgo73/OwfF6Gc6z4hu6ujVBn7oaAvLw4AAAQIECPgBANQ7AwCwLdt6X8UEBvV9ckBeHwkI6j3NYIoIGEUNAHMCZiZwCohPr50s3wHczkl3cExwqXdkArgJ8hmyDvpgO/BKKDto0c8Qfgjpe3A9Q/PpB+VWb9MAcZOHAHGN3gWom6wfiwABAr4GrAIMANqwKsnzfo/xAAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___RED_LEG_WARMERS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF/1BZ3ktTAAAA////hP6nfQAAAAR0Uk5T////AEAqqfQAAABeSURBVHja7NLBCgAhCEVRn/P//zwpFszSghbDdfUQPFRmz2EZAAAAAAAAAAAAAADAXcBnW+5asQVk3yyAyj1gTEXFUGU1AZ0BefwPoI0tqK49X6G/Ri2Ar/x34BVgAAYBLzkR21hbAAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___RED_OVERALLS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF/lNc3ktTAAAA////YJBGVwAAAAR0Uk5T////AEAqqfQAAACcSURBVHja7NZZCoAwDATQmXj/O2vt4lpLUkSkyVdA52FtLGLqLDjggAMOODAIAO1dl0u4dg4MBxBgzudOC8QcbEDI74oGgMVYOvY+AUwAU9mBtIJ/AjwD1AI4AdABaQYOjAKQMkN5E9dWFABuSgPgtr4BaAI2gSLP+SYQz5P6O2wAISSPu1j/FkpIaDuRpnWIylT6L44D7wKzAAMAQW0reFxPcNAAAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___RED_PINK_UNICORN_DEX_TANKTOP =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF/1BZzUBI4Yn7////GYmGyQAAAAR0Uk5T////AEAqqfQAAACVSURBVHja7NXRCoAgDAXQbf7/P6ebovYQ7ApBdEcP8+GepkVJOSwhQIAAAQJ/AFT0YfkKsEXqIguUO1DywAytfQboc6u3ENAI7U0aqCEzmYUATbAjwIU+BzZBIE5AZxBXjAAAY/voBHFjG3tAAAsEPoNFgB/jfJcUBQQFVPZS4IOy5/OAruk84MRS/DMRIEDgA8AlwACaCi0QdikF3AAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___RED_PONCHO =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF/8rN/6uwAAAA////UxQpNQAAAAR0Uk5T////AEAqqfQAAADBSURBVHja7NbRDoMgDAXQe7v//+epAW0RpOBMtqV9siU9QUAiXjcDAQQQQAABfD8g0q9cACJAMbAU6kQNWNthiFQQH5D7l+Ca88jFA6j+TaDOpQ+Y/kWgzWUUKKML6H56hOcAWoAzgBa8gKAFtARcTMA8/hDAFHsH8yKkunR2IUcJ7CPeG8lsA4HhK+0uYJaOQFN4CsAZgB8QvXv6DMjQpXqewgxAzAPmAHMWwKeA0VdgNdzA8UUVEX8oAfwx8BZgALY6J9iJ920KAAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___RED_PORTAL_SHIRT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF/1BZxz5GAAAA////Vct/ygAAAAR0Uk5T////AEAqqfQAAACzSURBVHja7NXLDoQwCAVQLvP//2w6MFQNrYVunAQ2jYn3pC+UPptFBRRQQAEFvB/gVsPHR4CZWp3eauUTHiBxp3gNGOZdgSJ5T6BQ3hFolofUVJgBuI1LgAloOZ0AOsIrx9jzvwl8rcvNeL7KNgXBEO4FDdpasgB2Adpbgq4hBdjm65gC+jlmAMnpVUYGOF3hxB5AmklbajKFIQDrRx3DAG5tHf6s41L1ayuggAL+ADgEGAD0IysZWvo8YwAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___RED_PROOF_OF_STAKE_SHIRT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF/1BZxT1FAAAA////xFpKMgAAAAR0Uk5T////AEAqqfQAAACcSURBVHja7NXdCoAgDAXgHXv/d45Zij8LnXVRdBZBQedzpaFsN0sIECBAgMD7gaB1eTsEQhCt4iktm7CAI25UmAMu86YgnrwliCtvCOLL98LjQBZQ5zD7CmnW0Y4MVCtjvJQ1gngeF+5/QZtIhzawAuCMxy6WOpA8/jqQv8MCUE/CDwF0C9ELoMn7AVRxNxCJori1ESBA4APALsAAtJgq670UmOMAAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___RED_PROOF_OF_WORK_SHIRT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF/1BZxD1FAAAA////0yFecQAAAAR0Uk5T////AEAqqfQAAACYSURBVHja7NVRDkAwEATQnXX/O7Mtou02bPkgZhofEvOKVsh0M0KAAAECBN4PqKV7egqoiuVwlcUnPCDXneg1oNt3BYn0PUFCfUeQWL8VHgd2AWUPVx9hW3XUMwPFzjjfyksD+Ugcwt+CldYxCuAukIvbGATs1aWbGACqRfghgGYjRgFU/TiAoh4GEnEIf20ECBD4ADALMAC7qyrsiyDDtwAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___RED_PUFFY_VEST =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF/1BZ10ZOAAAA////tVH5+QAAAAR0Uk5T////AEAqqfQAAAChSURBVHja7NXhDoMgEAPg9nj/d57K2EAXXCFkWVL+YdLP4/QC0uSCAQMGDBj4AyBuH/SBAFjvCYQCbPlG4L4PpYJPQFKBt3DkB4Ai5PwIkIVnXgMqoZ+/A8CSHwUwCrzezFKJXAGbBc4eQQXSCaA8zqUJ7LegV8FXLVh4hJ/3gKceyJ+Rk/8Br7NAAYhcdTsLZGj3QjsLvhsNGDCwHngIMAAGoSwqROmXnAAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___RED_REKT_SHIRT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF/1BZAAAAwj1E////LxYcpQAAAAR0Uk5T////AEAqqfQAAACsSURBVHja7NVLDoAgDATQMt7/zgZUfmKBslCTadyY0GdbIMq2GEKAAAECBL4POB+Pr13AOfGRrfLRJlrAkd4INwbEfByhC6J/H+HRBNHrr4G7IEq+Lx/ozEFGBzgKRAHlFDHawrXrSBPA2U9xMvpHuQIwfReq1o1AGoK9AixVIPEkWFtIO/rSELMbYZ7BuQ3TAOoKMAuUtxAGAEX6NBCILPhrI0CAwA+AXYABANj3K0Odp0mhAAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___RED_RASPBERRY_PI_NODE_TANKTOP =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFU8tZ/1BZpTRk////uisyaAAAAAR0Uk5T////AEAqqfQAAACESURBVHja7NXBCsAgDAPQGv//n7dJWTsPg0YYyNKD1EMeUlCtL5YJECBAgIA/AGh42X4CPCLnpgr0Geh1IEK5rwB+boyWAi4C3pSBNhUFmMVKAuYLCVxhz5NADJEEgFugACCE/QGsDhH1F2m6C8SDkgsEgJyuA4NIpZ9JgAABGwCHAAMAGu4uBDbABo0AAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___RED_SKIRT_WITH_BLACK_AND_WHITE_DOTS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF/2ZuAAAA00RM////nBp/1AAAAAR0Uk5T////AEAqqfQAAACYSURBVHja7NRLDoAgEAPQtt7/ziofgzgaiNFVJ0rCgtcBP1heFgwYMGDAgAEDBgwY+BMAu7lmgb3aySSwLyHO4wRACNcSRwFG+QJDATf5+SrRdYwEROvzFvoeEPYQACqhwrkVQUPAUtPSubW9aGwLpYcaffQijR7iJjCdek5XfgLbzYkXiUyRTcXLHz4mduUfioFPgVWAAQC/+y1Xv7XVbwAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___RED_SKIRT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF/1BZ0kRMAAAA////Knyq4gAAAAR0Uk5T////AEAqqfQAAACLSURBVHja7NThCoAgDATgu/X+75xlqdmMSdSvG1FC3OcUC8vLggABAgQIECBAgAABfwLoXoDTAKqxjScB3IsTgIGeYFHAzXMgYJDPV8mOBQzz1ah3R3AAogVqKwRDQGoBV6M8Yks4emjCeUhGNzEJTRPnMlLcJg6S2T5lU3784WOyrvRDEfApsAowAEA8LTjDaUAWAAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___RED_STRIPED_NECKTIE =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAlQTFRF/1BZuTpB////3AVB+QAAAAN0Uk5T//8A18oNQQAAAElJREFUeNrs1MEJADAIBMG99F900oGPAyGw/h08QTllISAgICAgsAgQ0k0w9Y9A6IBQRnj9tEvECEaoI9S34EsTEBAQ+Au4AgwAeycfqdWs1wcAAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___RED_SUIT_JACKET_WITH_GOLD_TIE =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF905W9+q4AAAA////xmtExAAAAAR0Uk5T////AEAqqfQAAACMSURBVHja7NXdCoAgDAXgdXz/d44aynLi/IEgOrsRh+cDpVTSZgkBAgQIEPgBAMSdDgDIVUepe9omWoDGjZDnGANK3gEtQTr5LJgGXgBsXoVHA0tA7xQCQDS/CUxtocr7AoEYcN9/9V9g9EKpgekbaRfwm/8ckEps9RA1aceFd0HG1/BtJECAQDoFGAALYym45HO4MQAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___RED_TANKTOP =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF/1BZzUBIAAAA////KQANqwAAAAR0Uk5T////AEAqqfQAAAB4SURBVHja7NXBCsAgDAPQpv3/f54bsqkDR+ouQnpqDn0oSLVYLBMgQIAAARsA7j6J34DD0OYSnTvBGyCvgG6kBBaIEQgeeIbangHquXG1KeAkUJskcBcP2FACBPwB0C8RI4A1AEhspG6c30iBrvS1CRAgYAPgEGAAmagspLFiOg8AAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___RED_TOGA =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF/1BZ3ktTAAAA////hP6nfQAAAAR0Uk5T////AEAqqfQAAACXSURBVHja7NXLDoAgDETRW/z/f1ZRHguD0FkZy4KwmRNoKLCJgwACCCCAAH4JJA0wLCmAgSk7GOSnAI4DoACj/AyACOS8AJxpGUAA7rwboADOe1DzToA2XAAigAj0aQ9AK6AL6PN5tfoeYNYMB2BWky/CI5C6HHUnz6/iHHBNabGI5QTjdmKij9zd2G5SfK4BBPABYBdgAJjYLNcRmxqrAAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___RED_TUBE_TOP =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAlQTFRF/1BZzUBI////gty5ygAAAAN0Uk5T//8A18oNQQAAAEVJREFUeNrs1CEOACAMQ9GW+x+aBMUyA5lq8r+q2ZPTGiYAAAAAAIBHwG0AxAHWXSLgCvgfqPcTwCceCgAAAABABrAFGADpGR9PORU0BwAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___RED_VEST =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF/1de3ktTAAAA////TxmphwAAAAR0Uk5T////AEAqqfQAAACSSURBVHja7NXdCoAgDAXgs/n+75zWRSr+sGmBcEYXipwPKZsIiwUCBAgQIHAAoKqD6RxQoFiJU7UAKQ8p8hC17KAF2N5BERnkvwMkC8ED3EIOBA/wCPAB2AIkAUtAJOITyw9AFnewC5D/ATkd0Crf7Scz4D2JNiDLzwRM/yVvP6g6kv0rBJH2mJcrAQIEOnUJMADtWiyLv96PBQAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___RED_WAGMI_SHIRT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF/1BZAAAAwz1E////5ErPAAAAAAR0Uk5T////AEAqqfQAAACjSURBVHja7NXpDkAwEATg6Xj/d6aHo7XClgTJrB8iMV+vFRhuFgQIECBAwPeBEOvw8RQIAbE2b8WyCQvIcaPCNeAwbwrw5C0BrrwhwJffC48Di8A6x6tLmE+d7chk1RnnrZwIZmkK0/0tTMn1wg2A5e4HUjaP37eEZg+7gDwHshcoG0i8CKCcQwfAXSN6ATZ5P8Aq7gYSsSn92gQIEPADYBRgABx3KzXUNXLUAAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___RED_WITH_PINK_AND_GREEN_DRESS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF1UNK4YGAiP/E////zBhpiQAAAAR0Uk5T////AEAqqfQAAAELSURBVHja7NbRDsIgDAXQ27v//2cHbWE4ZFtNfDAlRucih9KWRWxfDiSQQAIJJJDAzwDc/82fAgQgYHlDBNinsQEMAVKAEgYXIVwAdRdRgGV5VkACwD7XgXLFICBxgPs0Ql8IAUJdXlMZAjQBdQOfy7AArIYVkOdAjd4yGQEs9g7IY4AKQAN5CtRTpOl3ALcBXbPOpfWjfp0ea0w60BpQ20gvOnUBwOd7C0nXPCcLADg0rwH0Dw3jtBG8rS7DBg6TW00oA4Ehd+yR2zFku619bf2JKeCPMN+zt1ErpT8eMAW2Vi7frh5EK+MozJOIPujVsHzS7+pYNtIhjsb0ubfPAk4j/6EksBgvAQYArucp0bIjHFUAAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___RED_WITH_WHITE_APRON =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF/1BZuTpB////////3OI9SAAAAAR0Uk5T////AEAqqfQAAABvSURBVHja7NbRCsAgCIXh3+3933kVC1ZXS2MtOEZ4kx8iFHEGAwECBAgQIOAlwNAhAb8EjGfsCLT12PfAQbMcHXTC8hngACwHNQ0DqZKy77QCoLRekweIDVHADCB6mbp6PK9yvhEp9MEQsANwCTAAshQsVnWKSjsAAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___RED_WITH_WHITE_STRIPES_SOCCER_JERSEY =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF+U5X////AAAA////zrcqRAAAAAR0Uk5T////AEAqqfQAAACQSURBVHja7NXbCoAgEATQme3//7mSEFG3vAQZzPok6tlVFLFNBgQIECBAwPqAneF2HwEzEEiGji5RJ2qAhflXMGnWBhg9gNYCGHygUgOc/AEgc6CsAU5+hvUlUNRwA3AISLbAoS2cEY+wAHqucg50v4UXAIZTnKogvUgCPgCQA/gdEAn/GelrEyBAwGrALsAA3k4rQtxR7UkAAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___TAN_CARGO_SHORTS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFjHJBo4tdAAAA////FtYbmwAAAAR0Uk5T////AEAqqfQAAACISURBVHja7NTbCoAgEATQcfr/f25L3YRMV4LoYSTChDlu2wXbywEBAgQIECBAgAABAr4E0nRhBiANLudAssRx5JHnCwCBknPATmAUYBtuEUYB9AGEASv3DtgSwz24Kmj7wPhTYK0AZJ31e/gIlH2ZW3reAdfeA9/Vq1n9Fjw0SOt/IOA3wC7AAN7lLixpTRBDAAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___VAMPIRE_BAT_WINGS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFRUVFAAAANTU1////uJgBVgAAAAR0Uk5T////AEAqqfQAAAD1SURBVHja7NZbDoQgDAXQW9z/nseCBugLyDiJmeAPiaXHAoLi+PLCBjawgd8ARHF/FRcApRQKOo5jRTCirwMIIwDhHBAQCZwPIUDmj4FegMw/AU848zPQCVD5iAAoASrfHUQpQArQ+TwIC7gGIIQeKMHkTWKqD1FAkx9sUGjBAMLNGwLDAtoSBDBZgFEClgowSngImFsDcx2wVoAu4RlgfgR6DC8CrvxJoE7CvwAs3ECK81MFxItUI+HzHYC/SM36YLSVuZG7kUmaA0o/EidSvsMOhz2ACHc/daSVO7khD6C+nzjWm8b7Msl++z9xAxt4E/ARYAD+xijnidMGgQAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___WHITE_TUXEDO =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF////AAAA29vb////j7u4YwAAAAR0Uk5T////AEAqqfQAAACxSURBVHja7JXrDsMgCIU5Z+//ziupdlRSFZs0WwZ/VML5wEtEXjdNEpCABCQgAX8AAMaeDgAQtTLIsZwFFN0mOQ3bZA5wxKtSsxvHDOATrnI163gAYMN3wtmxBACWAfsh3gWEttDEe8PTAPL3KgDd8zOPksDsh9JWEP6R2gqiAH8Gi4BhCTLQm1sIAegBjG2hCFlZZLgvsGbldfp+Y2GVsaPvdia6SXbnBCTgiwFvAQYA1scpYl5y4lkAAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___WHITE_AND_RED_STRIPED_BIB =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF/////1BZ5eXl////FQoEIgAAAAR0Uk5T////AEAqqfQAAABLSURBVHja7NMxEgAgDAJBxP//2UYzloqWR53ZUCTqjxEAAAAAAMAZoNup/0CrhMAWGoQNXBXk7BK99js9Zc/wzgAAAAAAAOcZAgwAumcvAQiUdHgAAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___WHITE_WITH_RED_DRESS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF////uTpBAAAA////6oRj4QAAAAR0Uk5T////AEAqqfQAAAB9SURBVHja7NXhCoAgEAPg3Xz/dy6SSkNpElHC5g/l5D4EQZEeBgYMGDBgwIAGRHM5FXC2RfoIAOp5FABy5z6PAqgyIwBogoE/A4AovAUAqgC1vUe0iuwB1AAG8iiTK1SAo781KJ2AHWPdUG+BvChbYfRNZBF/7wYM3GURYAAQMCu/Csc6bQAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___WHITE_WITH_RED_STRIPES_TANKTOP =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF////uTpB5eXl////rZgQdQAAAAR0Uk5T////AEAqqfQAAABfSURBVHja7NVBCoAwDAXRSXr/O7tQkHShtCIinb8KhDzIJqE9DAICAgICKwBQOgQfAJT5UaD1QJsAOOtJYCfgYoM74EgQAgKLAvQAvwMyK5A5fNazxNcmICDwPrAJMADHnix+v0+20gAAAABJRU5ErkJggg==";

  function getAsset(uint256 headNum) external pure returns (string memory) {
    if (headNum == 54) {
      return CLOTHING_SHIRT___DUSTY_MAROON_MINERS_GARB;
    } else if (headNum == 55) {
      return CLOTHING_SHIRT___DUSTY_NAVY_MINERS_GARB;
    } else if (headNum == 56) {
      return CLOTHING_SHIRT___GRASS_SKIRT;
    } else if (headNum == 57) {
      return CLOTHING_SHIRT___LEDERHOSEN;
    } else if (headNum == 58) {
      return CLOTHING_SHIRT___MAGICIAN_UNIFORM_WITH_BLUE_CAPE;
    } else if (headNum == 59) {
      return CLOTHING_SHIRT___MAGICIAN_UNIFORM_WITH_RED_CAPE;
    } else if (headNum == 60) {
      return CLOTHING_SHIRT___NAKEY;
    } else if (headNum == 61) {
      return CLOTHING_SHIRT___NODE_OPERATORS_VEST;
    } else if (headNum == 62) {
      return CLOTHING_SHIRT___ORANGE_INFLATABLE_WATER_WINGS;
    } else if (headNum == 63) {
      return CLOTHING_SHIRT___ORANGE_PRISON_UNIFORM;
    } else if (headNum == 64) {
      return CLOTHING_SHIRT___PINK_TUTU;
    } else if (headNum == 65) {
      return CLOTHING_SHIRT___PINK_AND_TEAL_DEFI_LENDING_TANKTOP;
    } else if (headNum == 66) {
      return CLOTHING_SHIRT___RED_BEAR_LOVE_SHIRT;
    } else if (headNum == 67) {
      return CLOTHING_SHIRT___RED_BEAR_MARKET_SHIRT;
    } else if (headNum == 68) {
      return CLOTHING_SHIRT___RED_BULL_MARKET_SHIRT;
    } else if (headNum == 69) {
      return CLOTHING_SHIRT___RED_DRESS_WITH_WHITE_DOTS;
    } else if (headNum == 70) {
      return CLOTHING_SHIRT___RED_DRESS_WITH_WHITE_LACE;
    } else if (headNum == 71) {
      return CLOTHING_SHIRT___RED_DRESS;
    } else if (headNum == 72) {
      return CLOTHING_SHIRT___RED_ETH_SHIRT;
    } else if (headNum == 73) {
      return CLOTHING_SHIRT___RED_FANNY_PACK;
    } else if (headNum == 74) {
      return CLOTHING_SHIRT___RED_HOOLA_HOOP;
    } else if (headNum == 75) {
      return CLOTHING_SHIRT___RED_HOOT_SHIRT;
    } else if (headNum == 76) {
      return CLOTHING_SHIRT___RED_JESTERS_COLLAR;
    } else if (headNum == 77) {
      return CLOTHING_SHIRT___RED_KNIT_SWEATER;
    } else if (headNum == 78) {
      return CLOTHING_SHIRT___RED_LEG_WARMERS;
    } else if (headNum == 79) {
      return CLOTHING_SHIRT___RED_OVERALLS;
    } else if (headNum == 80) {
      return CLOTHING_SHIRT___RED_PINK_UNICORN_DEX_TANKTOP;
    } else if (headNum == 81) {
      return CLOTHING_SHIRT___RED_PONCHO;
    } else if (headNum == 82) {
      return CLOTHING_SHIRT___RED_PORTAL_SHIRT;
    } else if (headNum == 83) {
      return CLOTHING_SHIRT___RED_PROOF_OF_STAKE_SHIRT;
    } else if (headNum == 84) {
      return CLOTHING_SHIRT___RED_PROOF_OF_WORK_SHIRT;
    } else if (headNum == 85) {
      return CLOTHING_SHIRT___RED_PUFFY_VEST;
    } else if (headNum == 86) {
      return CLOTHING_SHIRT___RED_REKT_SHIRT;
    } else if (headNum == 87) {
      return CLOTHING_SHIRT___RED_RASPBERRY_PI_NODE_TANKTOP;
    } else if (headNum == 88) {
      return CLOTHING_SHIRT___RED_SKIRT_WITH_BLACK_AND_WHITE_DOTS;
    } else if (headNum == 89) {
      return CLOTHING_SHIRT___RED_SKIRT;
    } else if (headNum == 90) {
      return CLOTHING_SHIRT___RED_STRIPED_NECKTIE;
    } else if (headNum == 91) {
      return CLOTHING_SHIRT___RED_SUIT_JACKET_WITH_GOLD_TIE;
    } else if (headNum == 92) {
      return CLOTHING_SHIRT___RED_TANKTOP;
    } else if (headNum == 93) {
      return CLOTHING_SHIRT___RED_TOGA;
    } else if (headNum == 94) {
      return CLOTHING_SHIRT___RED_TUBE_TOP;
    } else if (headNum == 95) {
      return CLOTHING_SHIRT___RED_VEST;
    } else if (headNum == 96) {
      return CLOTHING_SHIRT___RED_WAGMI_SHIRT;
    } else if (headNum == 97) {
      return CLOTHING_SHIRT___RED_WITH_PINK_AND_GREEN_DRESS;
    } else if (headNum == 98) {
      return CLOTHING_SHIRT___RED_WITH_WHITE_APRON;
    } else if (headNum == 99) {
      return CLOTHING_SHIRT___RED_WITH_WHITE_STRIPES_SOCCER_JERSEY;
    } else if (headNum == 100) {
      return CLOTHING_SHIRT___TAN_CARGO_SHORTS;
    } else if (headNum == 101) {
      return CLOTHING_SHIRT___VAMPIRE_BAT_WINGS;
    } else if (headNum == 102) {
      return CLOTHING_SHIRT___WHITE_TUXEDO;
    } else if (headNum == 103) {
      return CLOTHING_SHIRT___WHITE_AND_RED_STRIPED_BIB;
    } else if (headNum == 104) {
      return CLOTHING_SHIRT___WHITE_WITH_RED_DRESS;
    } else if (headNum == 105) {
      return CLOTHING_SHIRT___WHITE_WITH_RED_STRIPES_TANKTOP;
    }
    return CLOTHING_SHIRT___RED_TANKTOP;
  }
}

// SPDX-License-Identifier: MIT
// OpenZeppelin Contracts (last updated v4.7.0) (utils/Strings.sol)

pragma solidity ^0.8.0;

/**
 * @dev String operations.
 */
library Strings {
    bytes16 private constant _HEX_SYMBOLS = "0123456789abcdef";
    uint8 private constant _ADDRESS_LENGTH = 20;

    /**
     * @dev Converts a `uint256` to its ASCII `string` decimal representation.
     */
    function toString(uint256 value) internal pure returns (string memory) {
        // Inspired by OraclizeAPI's implementation - MIT licence
        // https://github.com/oraclize/ethereum-api/blob/b42146b063c7d6ee1358846c198246239e9360e8/oraclizeAPI_0.4.25.sol

        if (value == 0) {
            return "0";
        }
        uint256 temp = value;
        uint256 digits;
        while (temp != 0) {
            digits++;
            temp /= 10;
        }
        bytes memory buffer = new bytes(digits);
        while (value != 0) {
            digits -= 1;
            buffer[digits] = bytes1(uint8(48 + uint256(value % 10)));
            value /= 10;
        }
        return string(buffer);
    }

    /**
     * @dev Converts a `uint256` to its ASCII `string` hexadecimal representation.
     */
    function toHexString(uint256 value) internal pure returns (string memory) {
        if (value == 0) {
            return "0x00";
        }
        uint256 temp = value;
        uint256 length = 0;
        while (temp != 0) {
            length++;
            temp >>= 8;
        }
        return toHexString(value, length);
    }

    /**
     * @dev Converts a `uint256` to its ASCII `string` hexadecimal representation with fixed length.
     */
    function toHexString(uint256 value, uint256 length) internal pure returns (string memory) {
        bytes memory buffer = new bytes(2 * length + 2);
        buffer[0] = "0";
        buffer[1] = "x";
        for (uint256 i = 2 * length + 1; i > 1; --i) {
            buffer[i] = _HEX_SYMBOLS[value & 0xf];
            value >>= 4;
        }
        require(value == 0, "Strings: hex length insufficient");
        return string(buffer);
    }

    /**
     * @dev Converts an `address` with fixed length of 20 bytes to its not checksummed ASCII `string` hexadecimal representation.
     */
    function toHexString(address addr) internal pure returns (string memory) {
        return toHexString(uint256(uint160(addr)), _ADDRESS_LENGTH);
    }
}