/**
 *Submitted for verification at Etherscan.io on 2022-03-21
*/

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

contract GenesisMouths {
    function G_Mouth(uint32 traitId_) public pure returns (string[2] memory) {
        if (traitId_ == 0) return  ["Stitched","iVBORw0KGgoAAAANSUhEUgAAACIAAAAiAQMAAAAAiZmBAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAZdEVYdFNvZnR3YXJlAEFkb2JlIEltYWdlUmVhZHlxyWU8AAAABlBMVEVHcEwAAACfKoRRAAAAAXRSTlMAQObYZgAAABVJREFUCNdjYBh0IDQARCopINhEAgBO8AGNql7pmwAAAABJRU5ErkJggg=="];
        if (traitId_ == 1) return  ["Laughing","iVBORw0KGgoAAAANSUhEUgAAACIAAAAiBAMAAADIaRbxAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAZdEVYdFNvZnR3YXJlAEFkb2JlIEltYWdlUmVhZHlxyWU8AAAAD1BMVEVHcEwAAAD17trQXV26SkopqFGfAAAAAXRSTlMAQObYZgAAACxJREFUKM9jYBgFQwEwCgIBioiQEhAIIIuIuBgbm6CIMIoYGzsKYBhEZ7cDALnZAvJ8qYDHAAAAAElFTkSuQmCC"];
        if (traitId_ == 2) return  ["Grin","iVBORw0KGgoAAAANSUhEUgAAACIAAAAiAgMAAABHKeNRAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAZdEVYdFNvZnR3YXJlAEFkb2JlIEltYWdlUmVhZHlxyWU8AAAACVBMVEVHcEwAAAD//upiE/orAAAAAXRSTlMAQObYZgAAAB5JREFUGNNjYBiBgDU0FMqSylwGZbHBWYyhIZQZDwAb3AOY4i14uwAAAABJRU5ErkJggg=="];
        if (traitId_ == 3) return  ["Fangs","iVBORw0KGgoAAAANSUhEUgAAACIAAAAiAgMAAABHKeNRAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAZdEVYdFNvZnR3YXJlAEFkb2JlIEltYWdlUmVhZHlxyWU8AAAACVBMVEVHcEwAAAD///8W1S+BAAAAAXRSTlMAQObYZgAAABpJREFUGNNjYBiBgDU0FMoSnJACE3QQoJbxAK2nAgXuqFVtAAAAAElFTkSuQmCC"];
        if (traitId_ == 4) return  ["Tongue Out","iVBORw0KGgoAAAANSUhEUgAAACIAAAAiAgMAAABHKeNRAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAZdEVYdFNvZnR3YXJlAEFkb2JlIEltYWdlUmVhZHlxyWU8AAAACVBMVEVHcEwAAAC6SkpCPX1UAAAAAXRSTlMAQObYZgAAABhJREFUGNNjYBiBQDQ0FMaUcsBksVJoPAB/ggF5w+wUxwAAAABJRU5ErkJggg=="];
        if (traitId_ == 5) return  ["Shocked","iVBORw0KGgoAAAANSUhEUgAAACIAAAAiBAMAAADIaRbxAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAZdEVYdFNvZnR3YXJlAEFkb2JlIEltYWdlUmVhZHlxyWU8AAAAD1BMVEVHcEwAAACRLi56MzOvQkJbI8D/AAAAAXRSTlMAQObYZgAAACZJREFUKM9jYBgFQwIICgoKoAoIK7kIIgswChopKRuiioDAgDsdADGxAe/wsW54AAAAAElFTkSuQmCC"];
        if (traitId_ == 6) return  ["Single Tooth","iVBORw0KGgoAAAANSUhEUgAAACIAAAAiAgMAAABHKeNRAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAZdEVYdFNvZnR3YXJlAEFkb2JlIEltYWdlUmVhZHlxyWU8AAAACVBMVEVHcEwAAAD///8W1S+BAAAAAXRSTlMAQObYZgAAABhJREFUGNNjYBiBgDU0FMpinAAXdKCa8QCDWwGBMVYyPwAAAABJRU5ErkJggg=="];
        if (traitId_ == 7) return  ["Hidden","iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVQYV2NgYAAAAAMAAWgmWQ0AAAAASUVORK5CYII="];
        if (traitId_ == 8) return  ["Mouth1","iVBORw0KGgoAAAANSUhEUgAAACIAAAAiAQMAAAAAiZmBAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAZdEVYdFNvZnR3YXJlAEFkb2JlIEltYWdlUmVhZHlxyWU8AAAABlBMVEVHcEwAAACfKoRRAAAAAXRSTlMAQObYZgAAABBJREFUCNdjYBh0oP4DmRoBUZMBcMH5ZOoAAAAASUVORK5CYII="];
        if (traitId_ == 9) return  ["Mouth2","iVBORw0KGgoAAAANSUhEUgAAACIAAAAiAQMAAAAAiZmBAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAZdEVYdFNvZnR3YXJlAEFkb2JlIEltYWdlUmVhZHlxyWU8AAAABlBMVEVHcEwAAACfKoRRAAAAAXRSTlMAQObYZgAAABNJREFUCNdjYBhEwAFM2n8gUzsAUxMBcKSkhgYAAAAASUVORK5CYII="];
        if (traitId_ == 10) return ["Mouth3","iVBORw0KGgoAAAANSUhEUgAAACIAAAAiAQMAAAAAiZmBAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAZdEVYdFNvZnR3YXJlAEFkb2JlIEltYWdlUmVhZHlxyWU8AAAABlBMVEVHcEwAAACfKoRRAAAAAXRSTlMAQObYZgAAABZJREFUCNdjYBh0gP8DiDQAsx1I0QgATXMBcCZ9dggAAAAASUVORK5CYII="];
        return ["",""];
    }
}