// SPDX-License-Identifier: MIT
pragma solidity ^0.8.9;

import "@openzeppelin/contracts/utils/Strings.sol";

library ClothingA {
  using Strings for uint256;
  string constant CLOTHING_CLOTHING___BLUE_ERC20_SHIRT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABJQTFRFUGv/QFbN3v8AAAAA/+QA////Znr5FAAAAAZ0Uk5T//////8As7+kvwAAALZJREFUeNrs1YsOhSAIBmBAev9XTrCaOrSws51zNnDdtv6vi7Rge1kQQAABBBDA7wNJanh4C6QEUtVZUjZhASVuVHoGDPOmAJ68JcA4T0R50Z2JAOPra1bH7B5mAB2LC7gEBM5r1qGHDx/hnPUcYD7iLARi0xn3rdy9fnR/Cx8BqklcAqhMo07D6iN8HSB4B5RW0s0SwNJKpY38APZ9gF4Au7wfwCbuBpSoKn5tAQQQwB8AuwADACjoR71QLaovAAAAAElFTkSuQmCC";

  string constant CLOTHING_CLOTHING___BLUE_FOX_WALLET_TANKTOP =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABhQTFRFUGv/QFbNyWojdj4aAAAA1b+yFhYW////s0sOyAAAAAh0Uk5T/////////wDeg71ZAAAAp0lEQVR42uzVywrEIAwF0CRG/f8/bqr2oQMz5M6iFBIKNYt7iGAt1T+LAggggAACeAGgql/a34Ay8b23Vn0TfALOLfAUscYL1BWofuAK3dceYMzNbQkBO8FjAQJn+QELifRweyNA6oJIQgET9ko4kHoeBeiYgEDAsqU9ggOjHgRyKRkHSChbkSAncTnJ/vtg/RQYuJGmuP9GqjxV/NoCCCCAFwCbAAMATJRopFHCgyYAAAAASUVORK5CYII=";

  string constant CLOTHING_CLOTHING___BLUE_GRADIENT_DIAMOND_SHIRT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABhQTFRFUGv/QFbN/8hGAAAA1nfb73qd/5Nt////gNwLKgAAAAh0Uk5T/////////wDeg71ZAAAAq0lEQVR42uzV0Q6CMAyF4dPOzfd/Y23nkGEJtBqjSc8dxP8LxBlxfXNIIIEEEkjg94Ei2708BEqBbPUpmU1YQM+NlXPAbm8K8PSWAFdvCPD1r8LHgUUg4NLXWtPLc68wvvWpZ77foOlkHB/l3teqPTO5fwv6BFUA6REBIH1l7WMAnn0QwNJHAYw+DODRx4Gx7wO0BcgL0Kb3AzTlbkCJ1fKvLYEEEvgD4CbAAINIZIz+nTBKAAAAAElFTkSuQmCC";

  string constant CLOTHING_CLOTHING___BLUE_LINK_SHIRT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRFUGv/////QFbNAAAA////ElYvGQAAAAV0Uk5T/////wD7tg5TAAAAr0lEQVR42uzV2w6EIAwE0F72/79ZqYu2BijUF006DyQmzkkKGOH3MJBAAgkkkMD7AS7pProAM5Sot0raRAs46o3wHNDtNwVw+oiOAMM+SoYCOP3/0hdGQG0agWdHoL14SvI4N0I9dQILAJG5Gf5VvgG0/C3c9iAE6FOIAeoeBIFrjDBQEwBQth+PBeMAPgWEwPURSI5PjUCrANk9DABk6suAECr5a0sggQQ+AGwCDABRpjl7XdftpgAAAABJRU5ErkJggg==";

  string constant CLOTHING_CLOTHING___BLUE_WEB3_SAFE_SHIRT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRFUGv/BJp9QFbNAAAA////5DqGRQAAAAV0Uk5T/////wD7tg5TAAAAoklEQVR42uzV4QqAIAwE4Ln1/s8cS7JZy5xCFNz9qaD7yFxEy2QIAAAAAAB8HxDN7eUjIEIac5fGJzwg151IH3DbdwWK9D2BQn1HoGY/adpCE0jpKkjvErj0N4F7l7Dvuu1ngavJeB7lDNB+4PC3UAA9mQLmnqC8gxGg3oURwM7BGGAmcRA48j7AZ4CjAJ/6cYCrehjYCBP82gAAAPADYBVgAONaOYs9mUpXAAAAAElFTkSuQmCC";

  string constant CLOTHING_CLOTHING___RED_ERC20_SHIRT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABJQTFRF/1BZzUBI3v8AAAAA/+QA////Zr8gVAAAAAZ0Uk5T//////8As7+kvwAAALZJREFUeNrs1YsOhSAIBmBAev9XTrCaOrSws51zNnDdtv6vi7Rge1kQQAABBBDA7wNJanh4C6QEUtVZUjZhASVuVHoGDPOmAJ68JcA4T0R50Z2JAOPra1bH7B5mAB2LC7gEBM5r1qGHDx/hnPUcYD7iLARi0xn3rdy9fnR/Cx8BqklcAqhMo07D6iN8HSB4B5RW0s0SwNJKpY38APZ9gF4Au7wfwCbuBpSoKn5tAQQQwB8AuwADACjoR71QLaovAAAAAElFTkSuQmCC";

  string constant CLOTHING_CLOTHING___RED_FOX_WALLET_TANKTOP =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABhQTFRF/1BZzUBIyWojdj4aAAAA1b+yFhYW////eWUHuAAAAAh0Uk5T/////////wDeg71ZAAAAp0lEQVR42uzVywrEIAwF0CRG/f8/bqr2oQMz5M6iFBIKNYt7iGAt1T+LAggggAACeAGgql/a34Ay8b23Vn0TfALOLfAUscYL1BWofuAK3dceYMzNbQkBO8FjAQJn+QELifRweyNA6oJIQgET9ko4kHoeBeiYgEDAsqU9ggOjHgRyKRkHSChbkSAncTnJ/vtg/RQYuJGmuP9GqjxV/NoCCCCAFwCbAAMATJRopFHCgyYAAAAASUVORK5CYII=";

  string constant CLOTHING_CLOTHING___RED_GRADIENT_DIAMOND_SHIRT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABhQTFRF/1BZzUBI/8hGAAAA1nfb73qd/5Nt////SvICWgAAAAh0Uk5T/////////wDeg71ZAAAAq0lEQVR42uzV0Q6CMAyF4dPOzfd/Y23nkGEJtBqjSc8dxP8LxBlxfXNIIIEEEkjg94Ei2708BEqBbPUpmU1YQM+NlXPAbm8K8PSWAFdvCPD1r8LHgUUg4NLXWtPLc68wvvWpZ77foOlkHB/l3teqPTO5fwv6BFUA6REBIH1l7WMAnn0QwNJHAYw+DODRx4Gx7wO0BcgL0Kb3AzTlbkCJ1fKvLYEEEvgD4CbAAINIZIz+nTBKAAAAAElFTkSuQmCC";

  string constant CLOTHING_CLOTHING___RED_LINK_SHIRT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRF/1BZ////zUBIAAAA////IGP2JgAAAAV0Uk5T/////wD7tg5TAAAAr0lEQVR42uzV2w6EIAwE0F72/79ZqYu2BijUF006DyQmzkkKGOH3MJBAAgkkkMD7AS7pProAM5Sot0raRAs46o3wHNDtNwVw+oiOAMM+SoYCOP3/0hdGQG0agWdHoL14SvI4N0I9dQILAJG5Gf5VvgG0/C3c9iAE6FOIAeoeBIFrjDBQEwBQth+PBeMAPgWEwPURSI5PjUCrANk9DABk6suAECr5a0sggQQ+AGwCDABRpjl7XdftpgAAAABJRU5ErkJggg==";

  string constant CLOTHING_CLOTHING___RED_WEB3_SAFE_SHIRT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRF/1BZBJp9zUBIAAAA////1g9fegAAAAV0Uk5T/////wD7tg5TAAAAoklEQVR42uzV4QqAIAwE4Ln1/s8cS7JZy5xCFNz9qaD7yFxEy2QIAAAAAAB8HxDN7eUjIEIac5fGJzwg151IH3DbdwWK9D2BQn1HoGY/adpCE0jpKkjvErj0N4F7l7Dvuu1ngavJeB7lDNB+4PC3UAA9mQLmnqC8gxGg3oURwM7BGGAmcRA48j7AZ4CjAJ/6cYCrehjYCBP82gAAAPADYBVgAONaOYs9mUpXAAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___ADAMS_LEAF =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAZQTFRFbpZw////ol6D2wAAAAJ0Uk5T/wDltzBKAAAARklEQVR42uzSwQkAMAgEwbX/pgM2YMiBn6z4UwcUqTAQEBAQEBAQEBAQ+BQgrTP0MPB0vgMdyQoxUNP81RF9ZQGBDeAIMACv4Q/oMKQQ5gAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___BLACK_BELT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAZQTFRFAAAA////pdmf3QAAAAJ0Uk5T/wDltzBKAAAAT0lEQVR42uzUMQoAIAxD0fT+l1YcRdohWBF+9j6aDlWYEQAAAAAAAAAAAEAfoGO+AnbLOeKcTgXVCyzEAOI5YFawjxhFgx6AhwJwHxgCDAAzUQ+aPiEm0gAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___BLACK_LEATHER_JACKET =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFGRkZAAAAzs7O////QbMmzgAAAAR0Uk5T////AEAqqfQAAACQSURBVHja7NVLDoAgDARQptz/zpqS8FOgSJSYzKzQ2EfLAp1fjCNAgAABAj8AMHzRBQBxGv1EI4AZ0HIpAWkRN0AqzzsIhA2I5cGIK3EmAHn1WeTzR0wB0MwCKLdPZ9AQmgDKQ8TnAOoRYATKBq7ARXgXkD0dSA+QMYDFEapRMmD2RtoO8L9AgAABAg9yCDAAHAEqvf7vD8EAAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___BLACK_TUXEDO =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRFAAAA////NTU1zs7O////OlAWfgAAAAV0Uk5T/////wD7tg5TAAAAnElEQVR42uzV3QqAIAwF4HOq93/msB8zi80pBMHZjSHta5pMLIMBAQIECBAgwAeQgkQ5BgAcwdvwTsDIT5np6xlAG4AruEUx8QkAVMJtog8gu4F9E0eB2BLgxOfANP2wAs58HJ/zUM5Ecz+oKwg3FG/tHvDcg07ALQFOfvEX+ioon4JdOWeZe2i19Zxm5Zv3AkIv6W4UIODvwCrAAJXUN44Ur7szAAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___BLACK_AND_BLUE_STRIPED_BIB =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAlQTFRFAAAAUGv/////v7SHiAAAAAN0Uk5T//8A18oNQQAAAERJREFUeNrs0yESACAIBED0/4+2qU1F4l5mlgsQ/TMBAAAAAMAdEK9T9UCbSQJbNEg2WBUie4nn/b4RAAAAAIByYAgwACjmH2vCPwVJAAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___BLACK_AND_WHITE_STRIPED_JAIL_UNIFORM =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRFAAAA////zs7ORUVF////YpJ5pAAAAAV0Uk5T/////wD7tg5TAAAA2UlEQVR42uyW2xKDIAxEl6X//80Vq8idpY59adYXcCZHNwlRvG4KBjCAAQxggD8AAG7TuQtrYAWwh5eCDkBQER2kAtCVBkB8YqaOC2j++3lA00Aaw6CYBxGQit7T97OAhoMSsF0xD1AAnzc/LfjdAntJQLsHE0C2hQIYawaAG8cTU8BRu7IDeNzHtIzkVfmyHUh5Hkjn4FEAK60CqnP0YwvNFoI+0tiaBVwAuLsAfSQ+BaiO8aKFi0BgHD8tY7b8AlCudUDy1hg5GHze4/QIANovjgGeBbwFGACILzY2oNeE/QAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___BLACK_WITH_BLUE_DRESS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAlQTFRFAAAAOk65////oYUMIQAAAAN0Uk5T//8A18oNQQAAAHNJREFUeNrs1UEKwCAMRNGv9z90FyKtYHFCDW1hkkVEmLfIQqkPCwMGDBgwYEADyvT4K+CMlfoSAOOMAtCSfUYBhooDoAmI+VshCwBV+CoAsmAgCwBdSAEKra/VbjSg52etLlFNL571Vda/swEDO4FDgAEAVf0c8UOq3HwAAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___BLACK_WITH_BLUE_STRIPES_TANKTOP =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAlQTFRFAAAAOk65////oYUMIQAAAAN0Uk5T//8A18oNQQAAAFlJREFUeNrs1TEKwDAMBMGV/v9oFw4EuUiwUwTjvUogbkCVyI9BQEBAQOAEAMqG4AeA0p8FcgRyAeCeF4FOwMMFb8CVIAQEDgUYAbYDKhH4mQQEBDYAmgADAG0xHcIUImbIAAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___BLUE_BEAR_LOVE_SHIRT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABJQTFRFUGv/////6Jr/QFbNAAAA////1efoqQAAAAZ0Uk5T//////8As7+kvwAAALxJREFUeNrs1eEKgzAMBOCkyd7/lddcW+dYRBP3Y4Mcggreh9WI9LgZKqCAAgoo4PcBtRyengKqZNldZfEJDxh1J3oNOOy7AkX6nkChviNQrP8pfB3YBKHWY0fYy9UlrLdufWbuAnZdkLfJOB/lAcy0JuFvwe6cmbC1JMAL4DxwZwl4eqwKgJIA2poFIKiinwNoPgUbpxyAIRzjGAbm6K5+H8QosAmzHwfk9QWKxAEQu9SvrYACCvgD4CnAAGgrSGlS/YzpAAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___BLUE_BEAR_MARKET_SHIRT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABJQTFRFUGv/QFbNAAAA/1JRUf9a////grSvdAAAAAZ0Uk5T//////8As7+kvwAAAJtJREFUeNrs1VEOQDAQBNCdlvtfmS0VjS22/UDMfEgk5qWrFTJ2RggQIECAwPuBoKneXgIhiGb3lMYmLGCpGwn3gGrfFMTTtwRx9Q1BfP2jcALEJmATUAq4O0LedaQlDPN1WAUUJ+P6KC9DqJEWAve3kN9DJ6AD9AF5O54FVPgjACkFwAsUQkQDsBPQACRiSwR/bQQIEPgAMAkwAPh8R1rI3W1LAAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___BLUE_BULL_MARKET_SHIRT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABJQTFRFUGv/QFbNAAAAUf9a/1NR////3F3VpQAAAAZ0Uk5T//////8As7+kvwAAAJxJREFUeNrs1esKgCAMhuFN6/5vOVQ8L3Taj4RvEKHwPlQU0b05BAAAAAAA/g8YN6/LIWAMuckb1i1lQgJCXo4NJzMH9H0EJIFm+gQIAql6QaCJvgQ64XMgCVz3PHsLfq/uwwUwV2/G+FXOcejV30Lsrx3AbgKuJn8sA3lWgLJffognA9wCrAW46fUAV7ka8EQx+LUBAADgAOARYAAlv0dYQnwcWwAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___BLUE_DRESS_WITH_WHITE_DOTS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRFUGv/QFbNAAAA////////4q5S+AAAAAV0Uk5T/////wD7tg5TAAAAy0lEQVR42uyWgQ6DIAxEr+f+/5snKKEUgtWFJVvaIKSVPq6AiXh9aAhAAAIQgAAE4GsA+Of8KQDKngCwQbUnALgkLAXoGu4DAJ+ElYDmFPCDJWzw3aRlCgAnAc4K7gIAr4RBmDVHDIMOAJkUyy5aUhMUN/fkBYDMywrKIFpJ8i0CbXpNroDq5MEg0KRn1YAqAqOIRkDtnaBZS/s2xBGgvLx89o7DEopEUXLFBI/G8SYyWye3Wf6YM71IJ8YC+tT5t8DO4g8lABN7CzAA6/03ZRYRDFwAAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___BLUE_DRESS_WITH_WHITE_LACE =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRFUGv/QFbNAAAA////////4q5S+AAAAAV0Uk5T/////wD7tg5TAAAAx0lEQVR42uzWiw7CIAwF0Nvq/3+zsldfyEgXXWKKYwaye+iYJsPzYkMBBRRQQAEF/AzA/DV/CuAhnwyg8wPhM2DyuKMCXKwA0AKQAlQ+CUg+Cxz5NLDn8wDuAoBJ4VsAMCt0plky5AyeAJj3JLWDFPQ+M58ALU4qb4Bl7AnYuIQFkMHy5QiYuM1vPc5oAmrvCGYtPfZT3AMI6BUQe6uhewt2URjw2FByjxNmD1sL5Zrl12uGP6SN8UCMjv8LHFq9oRQwaC8BBgC4cTc9RVw6OQAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___BLUE_DRESS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRFUGv/S2LeAAAATWf3////tNYCwwAAAAV0Uk5T/////wD7tg5TAAAAkklEQVR42uzVwQrEIAxF0ZvY///misN0LE0hWkrL8LIJaN5BdCHLxUKAAAECBAjIAYxOvQ/47bE8BbDvw3fAJ1mbzQD0ZVcBHgAofb4wCRS+fRyg1Grh1ieA3CX8MQBJ4S4AskK47FHezLPAST4WGMiHwhHwOhimYyE6gXsbPqbds6/QBq2rbVG/swABdwGrAAMAEJk6iXr20NwAAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___BLUE_ETH_SHIRT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRFUGv/QFbNOk65AAAA////IO6oqQAAAAV0Uk5T/////wD7tg5TAAAArklEQVR42uzV2wrDIBAE0JnY///mZtW22phuNgbawuxDQHAO3pbgNlkQIECAAAG/DySr3aELpASrZpbVmBgBJT6odAzYzQ8FOPmFjgAnv9AR8Hn9G2AjwFnACjAEPAWWvAGsw0NbeNw60QPI38hTrvkMrFmGe+EKoD3Ekyso1zizBXuJE1swAfUav3IGFwCvXggDfGtnMgr0LcQTALt4GMhEU/q1CRAg4A+AuwADAKHIOZyruYN8AAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___BLUE_FANNY_PACK =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFUGv/AAAAS2Le////23idyAAAAAR0Uk5T////AEAqqfQAAABMSURBVHja7NJBCgAgCAVRs/vfuUhsGfQLVzO7Fr1CtP6YAQAAAAAAAAAAANQBbWWZx/kacB2IfKfOID+gD3FePr/PIgEAAHwEhgADAEFtL3Hj35rhAAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___BLUE_HOOLA_HOOP =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAlQTFRFAAAAUGv/////v7SHiAAAAAN0Uk5T//8A18oNQQAAAHxJREFUeNrs08sOgCAMRNFb//+j1SIRjbVNiCvHHaE9Di+WyQ8BAgQIECBAgAABfwCYawDLAIMYwCxPcKvhMkdhS7aUxEBp20LAI5D9n3gJvsDdIGz2grdTaSWOjEwbHzPZuffSzlzHxZs4tj0lKt68M4GeswAB3wOrAAMAE1AfEcd7K6MAAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___BLUE_HOOT_SHIRT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRFUGv/Ok65QFbNAAAA////1/BWvQAAAAV0Uk5T/////wD7tg5TAAAAlUlEQVR42uzV6QqAIBAE4HXs/Z+5tAOPFd0KLJixfgTN16GRLA8jBAgQIEDg+4APaR52Ae8lJDkrRCc0YK8r8WNAs68KYulrgpj6iiC2fi28DlwC8h5GH+GcdZRXBrKV0V/KTrbhrh3mbyECx9i2GYCbfgfJS7wFlLP4PwDVQrQCKPp2AFndDEQiCX9tBAgQ+AGwCjAAvKk5Zh18qpkAAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___BLUE_JESTERS_COLLAR =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRFUGv/QFbNAAAA6sU3////6d2nHgAAAAV0Uk5T/////wD7tg5TAAAAgElEQVR42uzT2wrAIAwD0Cb1/7953hCcbqvsNYUhBnIEcZZ+jgkQIECAgA+AjGVPAG0TmzEK5P4qlIwxoPbvQssYAXp/IkbEI2AzIQBmwNotGRi6RCB/tYJRNbQ8BHiqAFJ3xs5PXmI/Dm3dHv4O+Ly6fmcBAgQIECBAQHQuAQYAMAI9ysAZ6R4AAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___BLUE_KNIT_SWEATER =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABhQTFRFUGv/////Ok65S2Le6sU3bpZwAAAA////Z+jJUAAAAAh0Uk5T/////////wDeg71ZAAAAt0lEQVR42uyVSw7DMAhEx8El979x1cSOYgMxqLsWZmWkefJAPti/LCQgAQlIQAL+AMC87jwAmAs+6ufzpCM0AKPoYh/A9KsEKP6XKWIPYIMpD+DJrxEQSaBlkIA2LxrnR63ruUE9RLXcRa27BFwJaPBXsjLAl8DOACuBmL+RQQB6gnmDLYPjBkcRzU8xne0l4KpxhqWGPyiTv4QB8xaiAPkWBAHCv8UA6Mu4Vf5YEpCABPw84C3AAJMLZQNVCsV6AAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___BLUE_LEG_WARMERS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFUGv/S2LeAAAA////rmvP5AAAAAR0Uk5T////AEAqqfQAAABeSURBVHja7NLBCgAhCEVRn/P//zwpFszSghbDdfUQPFRmz2EZAAAAAAAAAAAAAADAXcBnW+5asQVk3yyAyj1gTEXFUGU1AZ0BefwPoI0tqK49X6G/Ri2Ar/x34BVgAAYBLzkR21hbAAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___BLUE_OVERALLS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRFUGv/S2LeAAAAzs7O////3OYueQAAAAV0Uk5T/////wD7tg5TAAAAn0lEQVR42uzWSwqAMAwE0JnU+5/ZahvFD8KkCxEzq4DmgWkoYhoMEkgggQQS+AkA9a3LI1yrBH4HEKD3e6UBpbQ+oJQAwNqGHqdEgHSgVhHgmBDAnjjQv+CbAM8AVQBjQN+BAyMAtu2QH+JamgDgJgqA27wCkCFgE+rg9nnYFABsnygHAUpAuwhbkz0u4sOduCyR+VZELtX8xUlAyCzAAHgcOfOmJR/pAAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___BLUE_PINK_UNICORN_DEX_TANKTOP =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABJQTFRFUGv/QFbN23z46Jr/U27/////9VSvWgAAAAZ0Uk5T//////8As7+kvwAAAJ9JREFUeNrs1cEKwzAMA1DZXv7/l5c6KW16GFiBwZh8KMlBDzspLdpmQYAAAQIE/ANgsA/brwBLpG+qQHsCrQ5cIXtxwOzbckkBB2FzUQZ6yB1XMcAh+BaQQsRGB/mIJKgzAAJnCwRwju9kBx5zijEDA8S4SLaDnnbEEOhrHAD9JiJvgQQMaxnxQVnzdcDu6TqQxK30ZxIgQMAPAG8BBgCraErGJlXB6QAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___BLUE_PONCHO =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRFytL/q7j/AAAA09r/////ULoMdwAAAAV0Uk5T/////wD7tg5TAAAAxUlEQVR42uzWUQ6DIBAE0Jmx9z9z1aplFWTBmrTNzpdA9kUBUTwuBgEEEEAAAXw/INV7TgAJ2A2MHXkiB0zlMMTSIR+w1o/h1Oa7LQ+Q1M8C07bqgKkfBdq2WoF9qkBaT49wH0ALsAdIBS8glICSgJMbMJe/AwxcslVwnYRXBlVWYc0e2Ea8J5JZBgLNR9pVwEwdgaJwF4AjAD+gdPXSPaCmQ/V4Cz0A0Q+YDcxeAJ8CGh9he6NsBvm/jfnEH0oAfww8BRgAtJ80z7xqP48AAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___BLUE_PORTAL_SHIRT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRFUGv/QFbNOk65AAAA////IO6oqQAAAAV0Uk5T/////wD7tg5TAAAAv0lEQVR42uzV7Q6DMAgFUCi+/zNPPqzTYC34RxNoolmye4oOJywPCwoooIACCng/QFyXH28BIuD6+xaXT3iAxp2iOeAy7woQyXsChPKOAKM8ag2FEYCn8xTQBeScNYA7QjM/457fGhDrMBn3o9xbUAzDz4IF7djSAEJb1wNA0utKAhxXIg5suzfJZwDb3I4JQIUmLWRuYt9fewgDMoSyud4GxCigY2xXwBMZBvD0WIf/1vFQ9WoroIACPgD8BBgAbXU5ezvoUlYAAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___BLUE_PROOF_OF_STAKE_SHIRT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRFUGv/QFbNOk65AAAA////IO6oqQAAAAV0Uk5T/////wD7tg5TAAAAoUlEQVR42uzV4QqDMAwE4LvU939ml24VqxFN3Y/JLqIgeF+jrRTTzYIAAQIECPh9oHgd3p4CpcBr9ZRXTETAOx5UuQYc5kMBmXwkIJUPBOTye+HrwCKwz/HqK7RZ53ZkslsZ50sZMLN61gvT/8IrtxzewAhgn7h3MdYB2vg2DrTvMAL0k/CHAHcLMQtwk88D7OJpoBKr0tYmQICABwCzAAMAOEc5SWQl0jUAAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___BLUE_PROOF_OF_WORK_SHIRT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRFUGv/QFbNOk65AAAA////IO6oqQAAAAV0Uk5T/////wD7tg5TAAAAmklEQVR42uzVUQ5AMBAE0Jmt+5+ZaojWCls+iJnGh8S8VlqB4WYgQIAAAQLeD6Scw9tTICXkbJ7K8QkPKHUn6Rpw2HcFRPqegFDfERDr74XHgVVg3ePVV1h2ne3MZHUyzo8yzKxcU9HA8LcAW0cvYHeBubiMXmBaRVlEB9Bswg8B7g5iFGDTjwOs6mFgJjbRr02AAAEfAEYBBgBGbTlL5pGu5gAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___BLUE_PUFFY_VEST =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRFUGv/S2LeQFbNAAAA////16KZPwAAAAV0Uk5T/////wD7tg5TAAAAqElEQVR42uzV4QrDIAwE4Fzi+z/z2lo37YblImMMLn+KQj5iatDKYpgAAQIECPgDIG435kCYoV/DLBhgyx8E7OtgKvgEFBZ4CUd+AmhCzc8AVTjzOaAT5vl3gKHlZwHLAu4j4E5X4DVQP+PFzByBBcoFAD3OrQmYt2BWQd+DRAXLR/h5D3DpAf0bsXgP8D4LIIAAnlPYmrhFcO8ChtDbKECAgO8DDwEGAGFxOu854dqRAAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___BLUE_REKT_SHIRT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRFUGv/Ok65QFbNAAAA////1/BWvQAAAAV0Uk5T/////wD7tg5TAAAArklEQVR42uzVUQ6EIAwE0HbY+5/ZILsgyBaoH2oyjTExkWc7YpTPxRICBAgQIPB8IMT6ezkEQpBYh7ti9YkekJZ3KswBeb2msgWxn6/7YQli998CZ0GM9bF91UEOMhvgLJAF1ClidoTfW0dJIA0BVDtjvJUbAMvfQjO6Eygh+DvQSx1I3gneEfL5rhBLDv4Mvq9hGUDbAVYB1BE4AFTLl4GdOBR/bQQIEHgBsAkwAO/eOWmD0pTuAAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___BLUE_RASPBERRY_PI_NODE_TANKTOP =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABhQTFRFUGv/QFbNXRpwhy6hV9RdR65NU27/////Ks1hpgAAAAh0Uk5T/////////wDeg71ZAAAAl0lEQVR42uzVwQoDIQwE0EzU+v9/3MYKWg8FR2hZdsIiepinqKxWD8sECBAgQMAdABi+DH8CfEReg12grkDdB0YIDw7o60brUkAQ6J1twJaigJxHSwElsjkXGgih50nAPCU/2APzAJwHWryv4T/AO+6JB5K3j7+JHvM7dZWxHCOIH8pcIADM6X2gEVPpZRIgQMAFgKcAAwAYqWiyvHTVtwAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___BLUE_SKIRT_WITH_BLACK_AND_WHITE_DOTS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABJQTFRFUGv/AAAAQFbN////S2Le////L1gcOAAAAAZ0Uk5T//////8As7+kvwAAAJ9JREFUeNrslNsOgyAQRGeG7f//chHshXZtIMY+zQY38sA5Iyq4nSwYYIABBhhggAEGGGDAPwHgOC+xCtjqfbIIQAGIsS8ACOG7xFkAM7/AlIADfx+7+tEzArL1dSQZkGZIANqlwhhFiODcI3Rb7WMWBSc3UXgGeGWJzH/0Gtl2vdvV7kOFXPiQyE2pam2tXvnyHz8TP8oHigGXAu4CDADJ9kuCLqH6NAAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___BLUE_SKIRT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRFUGv/QFbNAAAAS2Le////Uu0oYQAAAAV0Uk5T/////wD7tg5TAAAAkUlEQVR42uzUSw6AIAwE0Gnr/c8siAHE1kCMrqZRJDHzil9sLwsECBAgQIAAAQIECPwJYDgBWwbQjDxfBHAvWwAU4giis4Cbl0BAkC9bzcYCwnwz2ugIDiDogbYUgZnOXQKuRj2YTt5EwSVcpub1jx5jt4gTstReF14k1dxSUtdjSLsff/iYdCj+UAh8CuwCDACVWzxGrh3vrwAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___BLUE_STRIPED_NECKTIE =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAlQTFRFUGv/Ok65////zGC7igAAAAN0Uk5T//8A18oNQQAAAElJREFUeNrs1MEJADAIBMG99F900oGPAyGw/h08QTllISAgICAgsAgQ0k0w9Y9A6IBQRnj9tEvECEaoI9S34EsTEBAQ+Au4AgwAeycfqdWs1wcAAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___BLUE_SUIT_JACKET_WITH_GOLD_TIE =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABhQTFRFUGv/QFbN////AAAA6sU38uOpOk65////eiK6iwAAAAh0Uk5T/////////wDeg71ZAAAA1ElEQVR42uzV2w6EIAwE0E6p6///8XJRAsqt7OO2L0SSORkxQTp/HDLAAAMMMOAPAOfmOwPAOQrDLMchcjDHxzbRAlI8CkU+EGtAznuAQz4DLYEG+VihKNAUJkA4AyVQ5onCGVQbTgn4vAeEtwFKedkAcL8Dffzcj3MgF0DdBL0KNC7wFrSAb19tYBFApwHmAK55NbhmCrBwnGeDtCvsVi+UZwP1jfRsoAXodQabQP4IWgBUfU+ogTMlESn086Nr3RNIaz8++S+gWuzfaIABBoznK8AAFZ1h2q7B4g8AAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___BLUE_TANKTOP =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRFUGv/QFbNAAAAU27/////YBaNzQAAAAV0Uk5T/////wD7tg5TAAAAeUlEQVR42uzVwQrAIAwD0Kbr/3/z3JBtKmyk7iKkp+bQh4JUi8kyAQIECBCwAODuL/EbcBieuUTnTjAC5BXQjJTAAtEDwQP3ELYcUM+Ns00BB4HaJIGreMC6EiDgD4B+iegBzAFAYiM14/xGCjSlr02AAAELALsAAwAOWzttt1K3WAAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___BLUE_TOGA =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFUGv/S2LeAAAA////rmvP5AAAAAR0Uk5T////AEAqqfQAAACXSURBVHja7NXLDoAgDETRW/z/f1ZRHguD0FkZy4KwmRNoKLCJgwACCCCAAH4JJA0wLCmAgSk7GOSnAI4DoACj/AyACOS8AJxpGUAA7rwboADOe1DzToA2XAAigAj0aQ9AK6AL6PN5tfoeYNYMB2BWky/CI5C6HHUnz6/iHHBNabGI5QTjdmKij9zd2G5SfK4BBPABYBdgAJjYLNcRmxqrAAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___BLUE_TUBE_TOP =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAlQTFRFUGv/QFbN////0hR+pQAAAAN0Uk5T//8A18oNQQAAAEVJREFUeNrs1CEOACAMQ9GW+x+aBMUyA5lq8r+q2ZPTGiYAAAAAAIBHwG0AxAHWXSLgCvgfqPcTwCceCgAAAABABrAFGADpGR9PORU0BwAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___BLUE_VEST =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABJQTFRFUGv/S2LeAAAA////6sU3////k/s+EAAAAAZ0Uk5T//////8As7+kvwAAAKZJREFUeNrs1eEKgzAMBOBLur7/Ky86GKmoJVf3Y3BF0CL3kVaN6IsDAgQIECDgDwB3v5nOAQeGOzH1CrDlYUMe5pUKzoDaHgyRm/zvAEshMMAuZKAzwEeIcyMAJKC1RgKbsOdpIIg4YvDAy8BtIlIJTwC2ugTj3oOVCh4DyCX4oYDLfjID7LubNSDlZwKm3xLbDw4dqf4Uutn5tX6uAgQIuBhvAQYAPXNKJwyo5N0AAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___BLUE_WAGMI_SHIRT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRFUGv/Ok65QFbNAAAA////1/BWvQAAAAV0Uk5T/////wD7tg5TAAAAqElEQVR42uzVUQqEMAwE0Enq/c+81qhra0QTBXdh4kcRnFfbRsRws0CAAAECBH4fKLUOb0+BUlBr81Qtn/AAiztVrgGHeVdAJO8JCOUdAbH8XngcWAVtc3p1Ccupaz+zatMZ560MGQMCGwQa/hbG5PfCDUBsTABT1ubPLaHbwxRg7yCSBeYNFLwIYD6HBKC7RowC2uXjgDbxMDARm+KvjQABAn8AfAQYAJGeOWKplSgTAAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___BLUE_WITH_BLACK_STRIPES_SOCCER_JERSEY =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFUGv/AAAAQFbN////p7KLPAAAAAR0Uk5T////AEAqqfQAAACfSURBVHja7NXhDoMgDATg3u3931nphKGAwlgyTa78USifBSXaazJMgAABAgTcH0CI5u0lABjMsiELHXWiBni2bYG89QFoA+gBYnYNqNRgjec7sF4fAVwBn9wwvwSKGk4AfAWkJdALTgB7lxCrYLEH7H6N28Ae4PBZ+AHgB2CuguxDEvAPgEeAowCnAWYAxwEnQuDd9GsTIEDAA4BFgAEAbp0rblZPrXIAAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___BLUE_WITH_PINK_AND_GREEN_DRESS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRFUGv/4YGAiP/EAAAA////f+yuPwAAAAV0Uk5T/////wD7tg5TAAABF0lEQVR42uzW4W7DIAwE4PN57//MA84mI01pwqT9mEBViarwYYxBxdcvGzawgQ1sYAMb+DMA99/5pwABGFi/sAKUYewAlwCrQA2DkxA+AG0VqwDr9GyALQBlbAL1iYuArQMswwh9sAQYNb1SuQQoAW0B77dhAsQeNsCeAy36yOQKELEfgD0GKAAK5CnQTpHSnwBuAw6dIRFKJrQivwG4MwpQZaSHpNw/AO7Q+CwhOzTl5EzgPHsv3gCYncIoykjgNLsNC/gxuO8JbSAw5I5H5HEMiX4kFZXq0y+BvMJyzVlGfSvzesAlUENA33nmZRhbOgp+nURvLRGtPvLJ/FXvTAspmMhedKV/GTo/C/7S9j+UDUzatwADACJGOA0u6TEiAAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___BLUE_WITH_WHITE_APRON =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRFUGv/QFbN////AAAA////7zl41AAAAAV0Uk5T/////wD7tg5TAAAAb0lEQVR42uzW0QqAIAyF4X/V+z9zKgnpVW6RCeeI7MZ9iKDIEQwCBAgQIEDAQ4ChRQJ+CRj3rAi0/dj3wEYzHDvohOlngAOwHGoZBlInZV5lBkDZei0eIHaIAt4Aopep68fzKqfsKfpgCFgBOAUYAEoBOwJog1HxAAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___BORAT_SWIMSUIT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFUf9aAAAAV9Rd////ch20ZQAAAAR0Uk5T////AEAqqfQAAABsSURBVHja7NVBDoAgDETR3/b+d3ZlMCamSKMEHRZsZvICCyhRXAgQIECAgD8AdgqwuydgrHeVEBOAY0RMAVpGrArsIbEwQNvHXiOdlQcBshtkHwo9DQFJDB8AvDaZ3IujzUzjXYCAd4BNgAEAI00vP0Y++BgAAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___BUTTERFLY_WINGS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRFwkvlyqLVAAAAodj5////5GyjhQAAAAV0Uk5T/////wD7tg5TAAABa0lEQVR42uyX6w7DIAiFEfb+z7y2auWOybJkWepPdviqBo4MXh8ueAB/BUDE/Swmhhlpre0ihLgDzsi5tghSDDy0swlkYgGAY21s4kof2hsw81k4y5fSATgCtEG48+mSSsAZppzQ84nmFlxAQhjfDwAj2gk+YJ3/kjs7GJiI0GW0PuQA5k9xPlchq4N1tusmXYCQgCokUL+6+Rmg8Us4ltO3UiBKmRPmB5x8InMDEkAMQBpADMDrDWSNTo3rPWt7rNocAIU2BxQCxC0kBmibFmyjphZqWhZMq+QA025gmq1wcd2uYOyqAqh2B2N4OcDYJhjLrQDKuPWOa1v//+f90zvAVgG054N2/hLQ8IsALCv5SEgqEXebCRMAVX5AMWA9UORnkzJkH+B6unT2ADAOEL5s99smDwHOCeLn3TmDAvQnI54PGpsMAlNt+YTSClPNZ0V0BlJjqvmo2RGxqeLOpIr4/GN5AL8HeAswAG+JNKIGEK8PAAAAAElFTkSuQmCC";

  // duplicate this in both clothingA & B
  string constant NONE =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAZQTFRF////AAAAVcLTfgAAAAF0Uk5TAEDm2GYAAAAdSURBVHja7MGBAAAAAMOg+VPf4ARVAQAAAHwTYAAQQAABpAJfkQAAAABJRU5ErkJggg==";

  function getAsset(uint256 assetNum) external pure returns (string memory) {
    if (assetNum == 0) {
      return CLOTHING_CLOTHING___BLUE_ERC20_SHIRT;
    } else if (assetNum == 1) {
      return CLOTHING_CLOTHING___BLUE_FOX_WALLET_TANKTOP;
    } else if (assetNum == 2) {
      return CLOTHING_CLOTHING___BLUE_GRADIENT_DIAMOND_SHIRT;
    } else if (assetNum == 3) {
      return CLOTHING_CLOTHING___BLUE_LINK_SHIRT;
    } else if (assetNum == 4) {
      return CLOTHING_CLOTHING___BLUE_WEB3_SAFE_SHIRT;
    } else if (assetNum == 5) {
      return CLOTHING_CLOTHING___RED_ERC20_SHIRT;
    } else if (assetNum == 6) {
      return CLOTHING_CLOTHING___RED_FOX_WALLET_TANKTOP;
    } else if (assetNum == 7) {
      return CLOTHING_CLOTHING___RED_GRADIENT_DIAMOND_SHIRT;
    } else if (assetNum == 8) {
      return CLOTHING_CLOTHING___RED_LINK_SHIRT;
    } else if (assetNum == 9) {
      return CLOTHING_CLOTHING___RED_WEB3_SAFE_SHIRT;
    } else if (assetNum == 10) {
      return CLOTHING_SHIRT___ADAMS_LEAF;
    } else if (assetNum == 11) {
      return CLOTHING_SHIRT___BLACK_BELT;
    } else if (assetNum == 12) {
      return CLOTHING_SHIRT___BLACK_LEATHER_JACKET;
    } else if (assetNum == 13) {
      return CLOTHING_SHIRT___BLACK_TUXEDO;
    } else if (assetNum == 14) {
      return CLOTHING_SHIRT___BLACK_AND_BLUE_STRIPED_BIB;
    } else if (assetNum == 15) {
      return CLOTHING_SHIRT___BLACK_AND_WHITE_STRIPED_JAIL_UNIFORM;
    } else if (assetNum == 16) {
      return CLOTHING_SHIRT___BLACK_WITH_BLUE_DRESS;
    } else if (assetNum == 17) {
      return CLOTHING_SHIRT___BLACK_WITH_BLUE_STRIPES_TANKTOP;
    } else if (assetNum == 18) {
      return CLOTHING_SHIRT___BLUE_BEAR_LOVE_SHIRT;
    } else if (assetNum == 19) {
      return CLOTHING_SHIRT___BLUE_BEAR_MARKET_SHIRT;
    } else if (assetNum == 20) {
      return CLOTHING_SHIRT___BLUE_BULL_MARKET_SHIRT;
    } else if (assetNum == 21) {
      return CLOTHING_SHIRT___BLUE_DRESS_WITH_WHITE_DOTS;
    } else if (assetNum == 22) {
      return CLOTHING_SHIRT___BLUE_DRESS_WITH_WHITE_LACE;
    } else if (assetNum == 23) {
      return CLOTHING_SHIRT___BLUE_DRESS;
    } else if (assetNum == 24) {
      return CLOTHING_SHIRT___BLUE_ETH_SHIRT;
    } else if (assetNum == 25) {
      return CLOTHING_SHIRT___BLUE_FANNY_PACK;
    } else if (assetNum == 26) {
      return CLOTHING_SHIRT___BLUE_HOOLA_HOOP;
    } else if (assetNum == 27) {
      return CLOTHING_SHIRT___BLUE_HOOT_SHIRT;
    } else if (assetNum == 28) {
      return CLOTHING_SHIRT___BLUE_JESTERS_COLLAR;
    } else if (assetNum == 29) {
      return CLOTHING_SHIRT___BLUE_KNIT_SWEATER;
    } else if (assetNum == 30) {
      return CLOTHING_SHIRT___BLUE_LEG_WARMERS;
    } else if (assetNum == 31) {
      return CLOTHING_SHIRT___BLUE_OVERALLS;
    } else if (assetNum == 32) {
      return CLOTHING_SHIRT___BLUE_PINK_UNICORN_DEX_TANKTOP;
    } else if (assetNum == 33) {
      return CLOTHING_SHIRT___BLUE_PONCHO;
    } else if (assetNum == 34) {
      return CLOTHING_SHIRT___BLUE_PORTAL_SHIRT;
    } else if (assetNum == 35) {
      return CLOTHING_SHIRT___BLUE_PROOF_OF_STAKE_SHIRT;
    } else if (assetNum == 36) {
      return CLOTHING_SHIRT___BLUE_PROOF_OF_WORK_SHIRT;
    } else if (assetNum == 37) {
      return CLOTHING_SHIRT___BLUE_PUFFY_VEST;
    } else if (assetNum == 38) {
      return CLOTHING_SHIRT___BLUE_REKT_SHIRT;
    } else if (assetNum == 39) {
      return CLOTHING_SHIRT___BLUE_RASPBERRY_PI_NODE_TANKTOP;
    } else if (assetNum == 40) {
      return CLOTHING_SHIRT___BLUE_SKIRT_WITH_BLACK_AND_WHITE_DOTS;
    } else if (assetNum == 41) {
      return CLOTHING_SHIRT___BLUE_SKIRT;
    } else if (assetNum == 42) {
      return CLOTHING_SHIRT___BLUE_STRIPED_NECKTIE;
    } else if (assetNum == 43) {
      return CLOTHING_SHIRT___BLUE_SUIT_JACKET_WITH_GOLD_TIE;
    } else if (assetNum == 44) {
      return CLOTHING_SHIRT___BLUE_TANKTOP;
    } else if (assetNum == 45) {
      return CLOTHING_SHIRT___BLUE_TOGA;
    } else if (assetNum == 46) {
      return CLOTHING_SHIRT___BLUE_TUBE_TOP;
    } else if (assetNum == 47) {
      return CLOTHING_SHIRT___BLUE_VEST;
    } else if (assetNum == 48) {
      return CLOTHING_SHIRT___BLUE_WAGMI_SHIRT;
    } else if (assetNum == 49) {
      return CLOTHING_SHIRT___BLUE_WITH_BLACK_STRIPES_SOCCER_JERSEY;
    } else if (assetNum == 50) {
      return CLOTHING_SHIRT___BLUE_WITH_PINK_AND_GREEN_DRESS;
    } else if (assetNum == 51) {
      return CLOTHING_SHIRT___BLUE_WITH_WHITE_APRON;
    } else if (assetNum == 52) {
      return CLOTHING_SHIRT___BORAT_SWIMSUIT;
    } else if (assetNum == 53) {
      return CLOTHING_SHIRT___BUTTERFLY_WINGS;
    }
    return NONE;
  }
}

// SPDX-License-Identifier: MIT
// OpenZeppelin Contracts (last updated v4.7.0) (utils/Strings.sol)

pragma solidity ^0.8.0;

/**
 * @dev String operations.
 */
library Strings {
    bytes16 private constant _HEX_SYMBOLS = "0123456789abcdef";
    uint8 private constant _ADDRESS_LENGTH = 20;

    /**
     * @dev Converts a `uint256` to its ASCII `string` decimal representation.
     */
    function toString(uint256 value) internal pure returns (string memory) {
        // Inspired by OraclizeAPI's implementation - MIT licence
        // https://github.com/oraclize/ethereum-api/blob/b42146b063c7d6ee1358846c198246239e9360e8/oraclizeAPI_0.4.25.sol

        if (value == 0) {
            return "0";
        }
        uint256 temp = value;
        uint256 digits;
        while (temp != 0) {
            digits++;
            temp /= 10;
        }
        bytes memory buffer = new bytes(digits);
        while (value != 0) {
            digits -= 1;
            buffer[digits] = bytes1(uint8(48 + uint256(value % 10)));
            value /= 10;
        }
        return string(buffer);
    }

    /**
     * @dev Converts a `uint256` to its ASCII `string` hexadecimal representation.
     */
    function toHexString(uint256 value) internal pure returns (string memory) {
        if (value == 0) {
            return "0x00";
        }
        uint256 temp = value;
        uint256 length = 0;
        while (temp != 0) {
            length++;
            temp >>= 8;
        }
        return toHexString(value, length);
    }

    /**
     * @dev Converts a `uint256` to its ASCII `string` hexadecimal representation with fixed length.
     */
    function toHexString(uint256 value, uint256 length) internal pure returns (string memory) {
        bytes memory buffer = new bytes(2 * length + 2);
        buffer[0] = "0";
        buffer[1] = "x";
        for (uint256 i = 2 * length + 1; i > 1; --i) {
            buffer[i] = _HEX_SYMBOLS[value & 0xf];
            value >>= 4;
        }
        require(value == 0, "Strings: hex length insufficient");
        return string(buffer);
    }

    /**
     * @dev Converts an `address` with fixed length of 20 bytes to its not checksummed ASCII `string` hexadecimal representation.
     */
    function toHexString(address addr) internal pure returns (string memory) {
        return toHexString(uint256(uint160(addr)), _ADDRESS_LENGTH);
    }
}