// SPDX-License-Identifier: MIT
pragma solidity ^0.8.9;

import "@openzeppelin/contracts/utils/Strings.sol";

library ClothingB {
  using Strings for uint256;

  string constant CLOTHING_SHIRT___DUSTY_MAROON_MINERS_GARB =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABhQTFRFZy0tZDg4XU9PUUJCAAAAWykpYSoq////qxctYgAAAAh0Uk5T/////////wDeg71ZAAABHElEQVR42uyV227EIAxExxfI//9xx4aCVKEG2qeqEGWzkJ3jwQYWzy8bLuACLuACLuAPAPx14FuAO768ANy3Ae5mBsgcEbDJErEAMLooCaGKvoUY8QnfAXgLp6EShHlAmx7qO4D4PaWK3iRw7Cl9bQA8NJay9qURsmMLCwtABLMe/fM52g4gVDb00j2gPk9lJd4BkT56LX0SPQ2FhLrjoNWQkCIzh2xFdD0HrHIoqYhMdAp52jOyBQjLVNv0QAKahz0AIqLNCcCUjkiQ7SmUsfqyrLDSl4O/74VEFMwllNbbwMGBUuNujFwXxycSy17HDJjQc4BCtW2BvE4BGVo0M5CbE+eALOG45QenMlW9Evef6QIu4AL+B+BDgAEAZxpjq8iVcncAAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___DUSTY_NAVY_MINERS_GARB =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABhQTFRFNThePkFdUVJbREVPAAAAMDNUMjVZ////rgUluAAAAAh0Uk5T/////////wDeg71ZAAABHElEQVR42uyV227EIAxExxfI//9xx4aCVKEG2qeqEGWzkJ3jwQYWzy8bLuACLuACLuAPAPx14FuAO768ANy3Ae5mBsgcEbDJErEAMLooCaGKvoUY8QnfAXgLp6EShHlAmx7qO4D4PaWK3iRw7Cl9bQA8NJay9qURsmMLCwtABLMe/fM52g4gVDb00j2gPk9lJd4BkT56LX0SPQ2FhLrjoNWQkCIzh2xFdD0HrHIoqYhMdAp52jOyBQjLVNv0QAKahz0AIqLNCcCUjkiQ7SmUsfqyrLDSl4O/74VEFMwllNbbwMGBUuNujFwXxycSy17HDJjQc4BCtW2BvE4BGVo0M5CbE+eALOG45QenMlW9Evef6QIu4AL+B+BDgAEAZxpjq8iVcncAAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___GRASS_SKIRT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFd6N5bpZwAAAA////lmA8jwAAAAR0Uk5T////AEAqqfQAAACESURBVHja7NPbCoAgEATQmfH//zkXQxEU1noSpqUbNselDOXnBgMGDBgwYMCAAQMGrgIIYneXAVATjFgU2uUBoJZAP7RSFhCnHDukHKA+d9sHt+oBq/63pVwH6on5BKVfosrIjumV/4xiDHH0Hg9ChyuRdVAxL1/101KWf2cDdwCPAAMAME0uEEJObu0AAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___LEDERHOSEN =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABhQTFRFd2A1aVUviW8+AAAARUVFnIFN6sU3////x3O6tgAAAAh0Uk5T/////////wDeg71ZAAAAhElEQVR42uzWwQrDMAwDUEt21///47ZJ2AZpIXEPY5uUiyD4QcCH2HozJkCAAAECBIwBb1fIAeibgA8AS0keWB48DtMAWYX8E1iiPfhmIKJv4wDMIqzlaJgD9iVkBFtKwwTgYA8QPg7YWf4WwKulALg/5yeAJtQZr+1iXv8DAb8CbAIMAKlkaHxLDpaNAAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___MAGICIAN_UNIFORM_WITH_BLUE_CAPE =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABhQTFRFAAAANTU1UGv/////QFbNQkJCzs7O////Ekul9gAAAAh0Uk5T/////////wDeg71ZAAAA90lEQVR42uzW2w6DIAwA0LbU+f9/PEBuxQlFkyUm7RMUeyyyOGF/GGCAAQYYYMALALh9YUojbu18Q4QVAHzg1gSGjB6AFA5juDzXAlCAFDAQYFCfhSbxFwCgE0RiBaACjJ7CNUB0CFG53QF0O1AAMIlVAPEh8MoO3Kf9+ZUOYvLj1O+JfXZnLVA6WH6lgbKFUx4lUE9BLI8AvjqLkGcN4KMK7SisTAFMQCoUA2aiOcAZ2Mu+88DXKwB/UQLqWhqoAeLfJ0ZqgKjMuWL8FIgLiGMAOyA8eAHQGPD1x79ZWyTxGdC1KBJhctrD4gfG6Q72kWVAjK8AAwCK/V6NGr5TOAAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___MAGICIAN_UNIFORM_WITH_RED_CAPE =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABVQTFRF////AAAAzUBIzs7O/1BZ5eXl////InmUiQAAAAd0Uk5T////////ABpLA0YAAAEDSURBVHja7NbRDoMgDAXQFgr//8kDCkhhQpnJEhP6BOg9FueM4B8WHOAABzjAAV4A4HJhDqC1tp2HKe4ACABWVFhAPRDzsZDDdaoFSgAwF0wEmOSL0Mz/AjTnsyDmOwBVYHYX7gEiFpLycwcgd6ABZGAo3AXSM/gEeGUHVjx+tQNetah+I/WX3n6l9R3sAuPutQBK4PoVbl6NI0DfG2CBNEAo70rKXSMfjywBZMDnoPPZcmFEZMwaIAY46MQg5BVAOImBEHReDNSAoRwsi3lg1IAxdZ67KQ08AtIBxDmAHRBvvADMHAh5/te1IYmvgK5FsRAnwx42PzCGK5yPrAOk+ggwAPeDURokxlaxAAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___NAKEY =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAZQTFRF////AAAAVcLTfgAAAAF0Uk5TAEDm2GYAAAAdSURBVHja7MGBAAAAAMOg+VPf4ARVAQAAAHwTYAAQQAABpAJfkQAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___NODE_OPERATORS_VEST =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF/40Szs7O9f+I////uL3xVwAAAAR0Uk5T////AEAqqfQAAABwSURBVHja7NXRCsAgCAXQq/3/P08XtMVgmIPcw71PRnQQfQjtY0CAAAECBAhEAKiI9tIr5ADMVQVg1ygGPATKAFW9ADssA+KvRkQSwJz9wNn3SGIGNrtbsLwFPLIZAKLCywxCDfBjIUCAwI+AQ4ABAJbLLS7e3N1BAAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___ORANGE_INFLATABLE_WATER_WINGS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABJQTFRF3H4xUGv/xnErS2LeAAAA////zib4ZAAAAAZ0Uk5T//////8As7+kvwAAAHJJREFUeNrs08EKgDAMA9Atxv//ZYV1tFaxB/EyEnYK7YMN1vaPaQIECBAgQMDqAN/GWQNsI0hzFlbA3E+Ct/wZOPe7nQRYjSxkoHtiH+oC2DyxD3UBYN4VlyuEmsUjAg/7QwDu+/pMAgQIECBgNeAQYAAqtE1Z1OYJ4QAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___ORANGE_PRISON_UNIFORM =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABJQTFRF234x3H4xxnErAAAA////////5Dpp5wAAAAZ0Uk5T//////8As7+kvwAAARFJREFUeNrs1ssSgyAMBdDkhv7/LzdAEDqmvJyuShYITnOMFlB6PQw6wAEOcIAD/AEgIoMTXUCEYrAGYsNp6BMeYOlJAFPMN2IOEPs5U6nATrgCeflcSwDXAlxhDqAFIOaz5WuDZhBbmQGaKyoQJAQpw1mgGmAJIqHc0kIFyEetQAsIOpy8BSF7higO1SM7j/EbAPoEUmcKsGnzceUGwLiCNHfhAen8EIDFDbD4OVDiDizuSLDZ9BRg8C5gawhcVtUagLgK44yyo65rrOyJKNtA3hDTvnj/A3oA572U21gB2Is9AA8BoOnOA5egSdIvYATI1ccOgApgB8AFuOtw9HovSXmBb34fyNWcb6QDdOMtwAAwBkOSOdCqnAAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___PINK_TUTU =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF6Jr/yqLVAAAA////nUtfkwAAAAR0Uk5T////AEAqqfQAAAB1SURBVHja7NPbDoAgDAPQrv7/P3vFjDiSqk+aEnDhYaeRAKaXAwYMGDBgwIABAwYMfAoIIEY7BUBgbWoFY6EE2LpPYCtUAabYNGsBVf8ley8ARaDPTYvqL1TA8qF8iIyu8YjnzYuUgcc3kaxz/RoN/A6YBRgA8LsuBJvLa3cAAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___PINK_AND_TEAL_DEFI_LENDING_TANKTOP =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABVQTFRFTt7x6Jr/qYK1acfT////Td7x////zF+RrAAAAAd0Uk5T////////ABpLA0YAAACTSURBVHja7NXLCoUwDATQyUP//5OtpdyqCyEJKHInuyzmkD5osRYLBAgQIEDgHwAVvWkfAU6R1kSB9QqEN9FkhlQyAGTM3VaTA7DntMeTAORQYQDognsJQIv7ywBKgO81hAywtAGAAoAOoAD4byfrgCZPAeM+xQG7AtH3wM6CJoApmGkc6MQs5c9EgACBDwCbAAMA7P1aN3IM5KEAAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___RED_BEAR_LOVE_SHIRT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABJQTFRF/1BZAAAA6Jr/zUBI////////Xe6vrQAAAAZ0Uk5T//////8As7+kvwAAAL1JREFUeNrs1eEKgzAMBOCk6d7/lZdcW+dYRBP3Y4MEQQXvw+qJ9Lg5VEABBRRQwO8DbHN4egowk83uKhuf8IARd4avAYd5V6BI3hMolHcEiuU/ha8DmyDUdOwIe7m6hPXWLa/lUQE7FeStGedVHsCc1iT8LdidayOxtSTAC+A8cGcJeHrcOwBKAkj3LAChd+RzAM2nYHXKASjhqGMYmNVdeS1iFNiEmY8D8voCReIAiN3Ur62AAgr4A+ApwABAkkgVO3f5jwAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___RED_BEAR_MARKET_SHIRT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABJQTFRF/1BZzUBIAAAAmzIxUf9a////2KNKwgAAAAZ0Uk5T//////8As7+kvwAAAJtJREFUeNrs1VEOQDAQBNCdlvtfmS0VjS22/UDMfEgk5qWrFTJ2RggQIECAwPuBoKneXgIhiGb3lMYmLGCpGwn3gGrfFMTTtwRx9Q1BfP2jcALEJmATUAq4O0LedaQlDPN1WAUUJ+P6KC9DqJEWAve3kN9DJ6AD9AF5O54FVPgjACkFwAsUQkQDsBPQACRiSwR/bQQIEPgAMAkwAPh8R1rI3W1LAAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___RED_BULL_MARKET_SHIRT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABJQTFRF/1BZzUBIAAAAUf9amzIx////0InoVwAAAAZ0Uk5T//////8As7+kvwAAAJxJREFUeNrs1esKgCAMhuFN6/5vOVQ8L3Taj4RvEKHwPlQU0b05BAAAAAAA/g8YN6/LIWAMuckb1i1lQgJCXo4NJzMH9H0EJIFm+gQIAql6QaCJvgQ64XMgCVz3PHsLfq/uwwUwV2/G+FXOcejV30Lsrx3AbgKuJn8sA3lWgLJffognA9wCrAW46fUAV7ka8EQx+LUBAADgAOARYAAlv0dYQnwcWwAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___RED_DRESS_WITH_WHITE_DOTS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRF/1BZzUBIAAAA////////n3wz5QAAAAV0Uk5T/////wD7tg5TAAAAy0lEQVR42uyWgQ6DIAxEr+f+/5snKKEUgtWFJVvaIKSVPq6AiXh9aAhAAAIQgAAE4GsA+Of8KQDKngCwQbUnALgkLAXoGu4DAJ+ElYDmFPCDJWzw3aRlCgAnAc4K7gIAr4RBmDVHDIMOAJkUyy5aUhMUN/fkBYDMywrKIFpJ8i0CbXpNroDq5MEg0KRn1YAqAqOIRkDtnaBZS/s2xBGgvLx89o7DEopEUXLFBI/G8SYyWye3Wf6YM71IJ8YC+tT5t8DO4g8lABN7CzAA6/03ZRYRDFwAAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___RED_DRESS_WITH_WHITE_LACE =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRF/1BZzUBIAAAA////////n3wz5QAAAAV0Uk5T/////wD7tg5TAAAAx0lEQVR42uzWiw7CIAwF0Nvq/3+zsldfyEgXXWKKYwaye+iYJsPzYkMBBRRQQAEF/AzA/DV/CuAhnwyg8wPhM2DyuKMCXKwA0AKQAlQ+CUg+Cxz5NLDn8wDuAoBJ4VsAMCt0plky5AyeAJj3JLWDFPQ+M58ALU4qb4Bl7AnYuIQFkMHy5QiYuM1vPc5oAmrvCGYtPfZT3AMI6BUQe6uhewt2URjw2FByjxNmD1sL5Zrl12uGP6SN8UCMjv8LHFq9oRQwaC8BBgC4cTc9RVw6OQAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___RED_DRESS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRF/1BZ3ktTAAAA901W////rqJ+JAAAAAV0Uk5T/////wD7tg5TAAAAkklEQVR42uzVwQrEIAxF0ZvY///misN0LE0hWkrL8LIJaN5BdCHLxUKAAAECBAjIAYxOvQ/47bE8BbDvw3fAJ1mbzQD0ZVcBHgAofb4wCRS+fRyg1Grh1ieA3CX8MQBJ4S4AskK47FHezLPAST4WGMiHwhHwOhimYyE6gXsbPqbds6/QBq2rbVG/swABdwGrAAMAEJk6iXr20NwAAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___RED_ETH_SHIRT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRF/1BZzUBIuTpBAAAA////fW8e6gAAAAV0Uk5T/////wD7tg5TAAAArklEQVR42uzV2wrDIBAE0JnY///mZtW22phuNgbawuxDQHAO3pbgNlkQIECAAAG/DySr3aELpASrZpbVmBgBJT6odAzYzQ8FOPmFjgAnv9AR8Hn9G2AjwFnACjAEPAWWvAGsw0NbeNw60QPI38hTrvkMrFmGe+EKoD3Ekyso1zizBXuJE1swAfUav3IGFwCvXggDfGtnMgr0LcQTALt4GMhEU/q1CRAg4A+AuwADAKHIOZyruYN8AAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___RED_FANNY_PACK =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRF/1BZ////3ktT5eXl////yoEvZAAAAAV0Uk5T/////wD7tg5TAAAAS0lEQVR42uzSsQoAIAgAUbP+/5sTxXYNnO42hx4iyflMAAAAAAAAAAAAAOaA5UmmMZcB7QPb01fM9RvkAv0j2mOLjwQAADADXAEGALEnPyE1LjVAAAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___RED_HOOLA_HOOP =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAlQTFRFAAAA/1BZ////6Q/r/QAAAAN0Uk5T//8A18oNQQAAAHxJREFUeNrs08sOgCAMRNFb//+j1SIRjbVNiCvHHaE9Di+WyQ8BAgQIECBAgAABfwCYawDLAIMYwCxPcKvhMkdhS7aUxEBp20LAI5D9n3gJvsDdIGz2grdTaSWOjEwbHzPZuffSzlzHxZs4tj0lKt68M4GeswAB3wOrAAMAE1AfEcd7K6MAAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___RED_HOOT_SHIRT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRF/1BZuTpBzUBIAAAA////v/zfjgAAAAV0Uk5T/////wD7tg5TAAAAlUlEQVR42uzV6QqAIBAE4HXs/Z+5tAOPFd0KLJixfgTN16GRLA8jBAgQIEDg+4APaR52Ae8lJDkrRCc0YK8r8WNAs68KYulrgpj6iiC2fi28DlwC8h5GH+GcdZRXBrKV0V/KTrbhrh3mbyECx9i2GYCbfgfJS7wFlLP4PwDVQrQCKPp2AFndDEQiCX9tBAgQ+AGwCjAAvKk5Zh18qpkAAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___RED_JESTERS_COLLAR =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRF/1BZzUBIAAAA6sU3////lA/GAwAAAAV0Uk5T/////wD7tg5TAAAAgElEQVR42uzT2wrAIAwD0Cb1/7953hCcbqvsNYUhBnIEcZZ+jgkQIECAgA+AjGVPAG0TmzEK5P4qlIwxoPbvQssYAXp/IkbEI2AzIQBmwNotGRi6RCB/tYJRNbQ8BHiqAFJ3xs5PXmI/Dm3dHv4O+Ly6fmcBAgQIECBAQHQuAQYAMAI9ysAZ6R4AAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___RED_KNIT_SWEATER =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABhQTFRF/1BZ////uTpB3ktT6sU3bpZwAAAA////6RWwuQAAAAh0Uk5T/////////wDeg71ZAAAAt0lEQVR42uyVSw7DMAhEx8El979x1cSOYgMxqLsWZmWkefJAPti/LCQgAQlIQAL+AMC87jwAmAs+6ufzpCM0AKPoYh/A9KsEKP6XKWIPYIMpD+DJrxEQSaBlkIA2LxrnR63ruUE9RLXcRa27BFwJaPBXsjLAl8DOACuBmL+RQQB6gnmDLYPjBkcRzU8xne0l4KpxhqWGPyiTv4QB8xaiAPkWBAHCv8UA6Mu4Vf5YEpCABPw84C3AAJMLZQNVCsV6AAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___RED_LEG_WARMERS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF/1BZ3ktTAAAA////hP6nfQAAAAR0Uk5T////AEAqqfQAAABeSURBVHja7NLBCgAhCEVRn/P//zwpFszSghbDdfUQPFRmz2EZAAAAAAAAAAAAAADAXcBnW+5asQVk3yyAyj1gTEXFUGU1AZ0BefwPoI0tqK49X6G/Ri2Ar/x34BVgAAYBLzkR21hbAAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___RED_OVERALLS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRF/1BZ3ktTAAAAzs7O////A2UrSAAAAAV0Uk5T/////wD7tg5TAAAApElEQVR42uzW6wrDIAwF4HNi3/+Z11nj6GWRpJQxzPkVaPNBaxSx3AwSSCCBBBKYBID3rdMjnKsEpgMIUPu18gGlbH1AKQGAaxtalHICpAJrFQH2CQFsiQPtC/4T4BGgF8ABgA9oM7BjHID0GdJFrKU4AFzEA+AyvwEYAj4CRez+IVDPI+MfDoB3k5ir+H0v9CYxJ9k4E+sQ9anMK04CzwIvAQYATmg55uy4GY8AAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___RED_PINK_UNICORN_DEX_TANKTOP =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABJQTFRF/1BZzUBI23z46Jr//1Nc////nSBtUwAAAAZ0Uk5T//////8As7+kvwAAAJ9JREFUeNrs1cEKwzAMA1DZXv7/l5c6KW16GFiBwZh8KMlBDzspLdpmQYAAAQIE/ANgsA/brwBLpG+qQHsCrQ5cIXtxwOzbckkBB2FzUQZ6yB1XMcAh+BaQQsRGB/mIJKgzAAJnCwRwju9kBx5zijEDA8S4SLaDnnbEEOhrHAD9JiJvgQQMaxnxQVnzdcDu6TqQxK30ZxIgQMAPAG8BBgCraErGJlXB6QAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___RED_PONCHO =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRF/8rN/6uwAAAA/9PV////SH0e4QAAAAV0Uk5T/////wD7tg5TAAAAxUlEQVR42uzWUQ6DIBAE0Jmx9z9z1aplFWTBmrTNzpdA9kUBUTwuBgEEEEAAAXw/INV7TgAJ2A2MHXkiB0zlMMTSIR+w1o/h1Oa7LQ+Q1M8C07bqgKkfBdq2WoF9qkBaT49wH0ALsAdIBS8glICSgJMbMJe/AwxcslVwnYRXBlVWYc0e2Ea8J5JZBgLNR9pVwEwdgaJwF4AjAD+gdPXSPaCmQ/V4Cz0A0Q+YDcxeAJ8CGh9he6NsBvm/jfnEH0oAfww8BRgAtJ80z7xqP48AAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___RED_PORTAL_SHIRT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRF/1BZzUBIuTpBAAAA////fW8e6gAAAAV0Uk5T/////wD7tg5TAAAAv0lEQVR42uzV7Q6DMAgFUCi+/zNPPqzTYC34RxNoolmye4oOJywPCwoooIACCng/QFyXH28BIuD6+xaXT3iAxp2iOeAy7woQyXsChPKOAKM8ag2FEYCn8xTQBeScNYA7QjM/457fGhDrMBn3o9xbUAzDz4IF7djSAEJb1wNA0utKAhxXIg5suzfJZwDb3I4JQIUmLWRuYt9fewgDMoSyud4GxCigY2xXwBMZBvD0WIf/1vFQ9WoroIACPgD8BBgAbXU5ezvoUlYAAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___RED_PROOF_OF_STAKE_SHIRT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRF/1BZzUBIuTpBAAAA////fW8e6gAAAAV0Uk5T/////wD7tg5TAAAAoUlEQVR42uzV4QqDMAwE4LvU939ml24VqxFN3Y/JLqIgeF+jrRTTzYIAAQIECPh9oHgd3p4CpcBr9ZRXTETAOx5UuQYc5kMBmXwkIJUPBOTye+HrwCKwz/HqK7RZ53ZkslsZ50sZMLN61gvT/8IrtxzewAhgn7h3MdYB2vg2DrTvMAL0k/CHAHcLMQtwk88D7OJpoBKr0tYmQICABwCzAAMAOEc5SWQl0jUAAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___RED_PROOF_OF_WORK_SHIRT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRF/1BZzUBIuTpBAAAA////fW8e6gAAAAV0Uk5T/////wD7tg5TAAAAmklEQVR42uzVUQ5AMBAE0Jmt+5+ZaojWCls+iJnGh8S8VlqB4WYgQIAAAQLeD6Scw9tTICXkbJ7K8QkPKHUn6Rpw2HcFRPqegFDfERDr74XHgVVg3ePVV1h2ne3MZHUyzo8yzKxcU9HA8LcAW0cvYHeBubiMXmBaRVlEB9Bswg8B7g5iFGDTjwOs6mFgJjbRr02AAAEfAEYBBgBGbTlL5pGu5gAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___RED_PUFFY_VEST =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRF/1BZ3ktTzUBIAAAA/////8GG7wAAAAV0Uk5T/////wD7tg5TAAAAqElEQVR42uzV4QrDIAwE4Fzi+z/z2lo37YblImMMLn+KQj5iatDKYpgAAQIECPgDIG435kCYoV/DLBhgyx8E7OtgKvgEFBZ4CUd+AmhCzc8AVTjzOaAT5vl3gKHlZwHLAu4j4E5X4DVQP+PFzByBBcoFAD3OrQmYt2BWQd+DRAXLR/h5D3DpAf0bsXgP8D4LIIAAnlPYmrhFcO8ChtDbKECAgO8DDwEGAGFxOu854dqRAAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___RED_REKT_SHIRT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRF/1BZuTpBzUBIAAAA////v/zfjgAAAAV0Uk5T/////wD7tg5TAAAArklEQVR42uzVUQ6EIAwE0HbY+5/ZILsgyBaoH2oyjTExkWc7YpTPxRICBAgQIPB8IMT6ezkEQpBYh7ti9YkekJZ3KswBeb2msgWxn6/7YQli998CZ0GM9bF91UEOMhvgLJAF1ClidoTfW0dJIA0BVDtjvJUbAMvfQjO6Eygh+DvQSx1I3gneEfL5rhBLDv4Mvq9hGUDbAVYB1BE4AFTLl4GdOBR/bQQIEHgBsAkwAO/eOWmD0pTuAAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___RED_RASPBERRY_PI_NODE_TANKTOP =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABhQTFRF/1BZzUBIXRpwhy6hV9RdR65N/1Nc////iFJznwAAAAh0Uk5T/////////wDeg71ZAAAAl0lEQVR42uzVwQoDIQwE0EzU+v9/3MYKWg8FR2hZdsIiepinqKxWD8sECBAgQMAdABi+DH8CfEReg12grkDdB0YIDw7o60brUkAQ6J1twJaigJxHSwElsjkXGgih50nAPCU/2APzAJwHWryv4T/AO+6JB5K3j7+JHvM7dZWxHCOIH8pcIADM6X2gEVPpZRIgQMAFgKcAAwAYqWiyvHTVtwAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___RED_SKIRT_WITH_BLACK_AND_WHITE_DOTS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABJQTFRF/1BZAAAAzUBI////3ktT////mG+gsQAAAAZ0Uk5T//////8As7+kvwAAAJ9JREFUeNrslNsOgyAQRGeG7f//chHshXZtIMY+zQY38sA5Iyq4nSwYYIABBhhggAEGGGDAPwHgOC+xCtjqfbIIQAGIsS8ACOG7xFkAM7/AlIADfx+7+tEzArL1dSQZkGZIANqlwhhFiODcI3Rb7WMWBSc3UXgGeGWJzH/0Gtl2vdvV7kOFXPiQyE2pam2tXvnyHz8TP8oHigGXAu4CDADJ9kuCLqH6NAAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___RED_SKIRT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRF/1BZzUBIAAAA3ktT////sXbtHwAAAAV0Uk5T/////wD7tg5TAAAAkUlEQVR42uzUSw6AIAwE0Gnr/c8siAHE1kCMrqZRJDHzil9sLwsECBAgQIAAAQIECPwJYDgBWwbQjDxfBHAvWwAU4giis4Cbl0BAkC9bzcYCwnwz2ugIDiDogbYUgZnOXQKuRj2YTt5EwSVcpub1jx5jt4gTstReF14k1dxSUtdjSLsff/iYdCj+UAh8CuwCDACVWzxGrh3vrwAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___RED_STRIPED_NECKTIE =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAlQTFRF/1BZuTpB////3AVB+QAAAAN0Uk5T//8A18oNQQAAAElJREFUeNrs1MEJADAIBMG99F900oGPAyGw/h08QTllISAgICAgsAgQ0k0w9Y9A6IBQRnj9tEvECEaoI9S34EsTEBAQ+Au4AgwAeycfqdWs1wcAAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___RED_SUIT_JACKET_WITH_GOLD_TIE =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABhQTFRF/1BZzUBI////AAAA6sU38uOpuTpB////Z6itygAAAAh0Uk5T/////////wDeg71ZAAAA1ElEQVR42uzV2w6EIAwE0E6p6///8XJRAsqt7OO2L0SSORkxQTp/HDLAAAMMMOAPAOfmOwPAOQrDLMchcjDHxzbRAlI8CkU+EGtAznuAQz4DLYEG+VihKNAUJkA4AyVQ5onCGVQbTgn4vAeEtwFKedkAcL8Dffzcj3MgF0DdBL0KNC7wFrSAb19tYBFApwHmAK55NbhmCrBwnGeDtCvsVi+UZwP1jfRsoAXodQabQP4IWgBUfU+ogTMlESn086Nr3RNIaz8++S+gWuzfaIABBoznK8AAFZ1h2q7B4g8AAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___RED_TANKTOP =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRF/1BZzUBIAAAA/1Nc////dXX3mQAAAAV0Uk5T/////wD7tg5TAAAAeUlEQVR42uzVwQrAIAwD0Kbr/3/z3JBtKmyk7iKkp+bQh4JUi8kyAQIECBCwAODuL/EbcBieuUTnTjAC5BXQjJTAAtEDwQP3ELYcUM+Ns00BB4HaJIGreMC6EiDgD4B+iegBzAFAYiM14/xGCjSlr02AAAELALsAAwAOWzttt1K3WAAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___RED_TOGA =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF/1BZ3ktTAAAA////hP6nfQAAAAR0Uk5T////AEAqqfQAAACXSURBVHja7NXLDoAgDETRW/z/f1ZRHguD0FkZy4KwmRNoKLCJgwACCCCAAH4JJA0wLCmAgSk7GOSnAI4DoACj/AyACOS8AJxpGUAA7rwboADOe1DzToA2XAAigAj0aQ9AK6AL6PN5tfoeYNYMB2BWky/CI5C6HHUnz6/iHHBNabGI5QTjdmKij9zd2G5SfK4BBPABYBdgAJjYLNcRmxqrAAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___RED_TUBE_TOP =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAlQTFRF/1BZzUBI////gty5ygAAAAN0Uk5T//8A18oNQQAAAEVJREFUeNrs1CEOACAMQ9GW+x+aBMUyA5lq8r+q2ZPTGiYAAAAAAIBHwG0AxAHWXSLgCvgfqPcTwCceCgAAAABABrAFGADpGR9PORU0BwAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___RED_VEST =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABJQTFRF/1BZ3ktTAAAA////6sU3////v5SXtwAAAAZ0Uk5T//////8As7+kvwAAAKZJREFUeNrs1eEKgzAMBOBLur7/Ky86GKmoJVf3Y3BF0CL3kVaN6IsDAgQIECDgDwB3v5nOAQeGOzH1CrDlYUMe5pUKzoDaHgyRm/zvAEshMMAuZKAzwEeIcyMAJKC1RgKbsOdpIIg4YvDAy8BtIlIJTwC2ugTj3oOVCh4DyCX4oYDLfjID7LubNSDlZwKm3xLbDw4dqf4Uutn5tX6uAgQIuBhvAQYAPXNKJwyo5N0AAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___RED_WAGMI_SHIRT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRF/1BZuTpBzUBIAAAA////v/zfjgAAAAV0Uk5T/////wD7tg5TAAAAqElEQVR42uzVUQqEMAwE0Enq/c+81qhra0QTBXdh4kcRnFfbRsRws0CAAAECBH4fKLUOb0+BUlBr81Qtn/AAiztVrgGHeVdAJO8JCOUdAbH8XngcWAVtc3p1Ccupaz+zatMZ560MGQMCGwQa/hbG5PfCDUBsTABT1ubPLaHbwxRg7yCSBeYNFLwIYD6HBKC7RowC2uXjgDbxMDARm+KvjQABAn8AfAQYAJGeOWKplSgTAAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___RED_WITH_PINK_AND_GREEN_DRESS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRF/1BZ4YGAiP/EAAAA////ujlt4QAAAAV0Uk5T/////wD7tg5TAAABF0lEQVR42uzW4W7DIAwE4PN57//MA84mI01pwqT9mEBViarwYYxBxdcvGzawgQ1sYAMb+DMA99/5pwABGFi/sAKUYewAlwCrQA2DkxA+AG0VqwDr9GyALQBlbAL1iYuArQMswwh9sAQYNb1SuQQoAW0B77dhAsQeNsCeAy36yOQKELEfgD0GKAAK5CnQTpHSnwBuAw6dIRFKJrQivwG4MwpQZaSHpNw/AO7Q+CwhOzTl5EzgPHsv3gCYncIoykjgNLsNC/gxuO8JbSAw5I5H5HEMiX4kFZXq0y+BvMJyzVlGfSvzesAlUENA33nmZRhbOgp+nURvLRGtPvLJ/FXvTAspmMhedKV/GTo/C/7S9j+UDUzatwADACJGOA0u6TEiAAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___RED_WITH_WHITE_APRON =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRF/1BZzUBI////AAAA////kusZyQAAAAV0Uk5T/////wD7tg5TAAAAb0lEQVR42uzW0QqAIAyF4X/V+z9zKgnpVW6RCeeI7MZ9iKDIEQwCBAgQIEDAQ4ChRQJ+CRj3rAi0/dj3wEYzHDvohOlngAOwHGoZBlInZV5lBkDZei0eIHaIAt4Aopep68fzKqfsKfpgCFgBOAUYAEoBOwJog1HxAAAAAElFTkSuQmCC";

  string constant CLOTHING_SHIRT___RED_WITH_WHITE_STRIPES_SOCCER_JERSEY =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRF/1BZ////zUBIAAAA////IGP2JgAAAAV0Uk5T/////wD7tg5TAAAAoUlEQVR42uzVgQrDIAwE0FzS///mLWnpRM2mtbAN7oSCaJ9RLJVtMUKAAAECBH4fME/a/QiYCUSKoWcX0id6gMX8IyiajQGGDICNACY50KlBkvUDAGqgrUGS9RHvt0BTwxsAl4BzC+qPF6CjW/D4TG3OwImZq1wBOv0t3AAgTnGpguIiEfgGoDWgs4AuA1oAOg8E4cHe+GsjQIDAHwAPAQYAFo45yJHUSk0AAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___TAN_CARGO_SHORTS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABVQTFRFnIFNiW8+AAAA5eXlkXhIzs7O////c7ZgkwAAAAd0Uk5T////////ABpLA0YAAACWSURBVHja7NRLDoMwDARQe+xy/yPXIQlEKh+nlSoWE7EwEfNiGYEsPy4hQIAAAQIECBAgQOCfgHz9YN9Xubi9ByQS5aqr1hMAVFtO5NULVWQByHD60IUgC+gxoGkg2v0EYgvpGewd+NAB8m8B2oIO9Op4hmdAPxh1pJF3nwEWM1tTBfCixcbst2DWQlvB/wGBBwNvAQYAwvNbbtiELhUAAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___VAMPIRE_BAT_WINGS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFRUVFAAAANTU1////uJgBVgAAAAR0Uk5T////AEAqqfQAAAD1SURBVHja7NZbDoQgDAXQW9z/nseCBugLyDiJmeAPiaXHAoLi+PLCBjawgd8ARHF/FRcApRQKOo5jRTCirwMIIwDhHBAQCZwPIUDmj4FegMw/AU848zPQCVD5iAAoASrfHUQpQArQ+TwIC7gGIIQeKMHkTWKqD1FAkx9sUGjBAMLNGwLDAtoSBDBZgFEClgowSngImFsDcx2wVoAu4RlgfgR6DC8CrvxJoE7CvwAs3ECK81MFxItUI+HzHYC/SM36YLSVuZG7kUmaA0o/EidSvsMOhz2ACHc/daSVO7khD6C+nzjWm8b7Msl++z9xAxt4E/ARYAD+xijnidMGgQAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___WHITE_TUXEDO =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABJQTFRF////AAAA5eXlysrK8vLy////254sTwAAAAZ0Uk5T//////8As7+kvwAAAMBJREFUeNrsldsOxCAIRGFs//+Xt6TiramKzW6aLL5ICXMYGyO0P1zkAAc4wAEO+AMA8zjTATCTrLhR+pwFRN0hqbYjmAOkelFK9yIxA8jlIpdVJn4AKMtPQp1YAjAvA86f+BRgOkKq32rhdkf4OiCERUBjICesAHUwD+BwuX7FpQzMsw9K68D8IrUOrABqHdAiYGiBBvrsgEwAqAo5sh0hCqEswDwXoF1x374/WKAydPTdyYRL4NPZAQ54MeAjwABY+ETG7RBcCQAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___WHITE_AND_RED_STRIPED_BIB =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF/////1BZ5eXl////FQoEIgAAAAR0Uk5T////AEAqqfQAAABLSURBVHja7NMxEgAgDAJBxP//2UYzloqWR53ZUCTqjxEAAAAAAMAZoNup/0CrhMAWGoQNXBXk7BK99js9Zc/wzgAAAAAAAOcZAgwAumcvAQiUdHgAAAAASUVORK5CYII=";

  string constant CLOTHING_SHIRT___WHITE_WITH_RED_DRESS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF////uTpBAAAA////6oRj4QAAAAR0Uk5T////AEAqqfQAAAB9SURBVHja7NXhCoAgEAPg3Xz/dy6SSkNpElHC5g/l5D4EQZEeBgYMGDBgwIAGRHM5FXC2RfoIAOp5FABy5z6PAqgyIwBogoE/A4AovAUAqgC1vUe0iuwB1AAG8iiTK1SAo781KJ2AHWPdUG+BvChbYfRNZBF/7wYM3GURYAAQMCu/Csc6bQAAAABJRU5ErkJggg==";

  string constant CLOTHING_SHIRT___WHITE_WITH_RED_STRIPES_TANKTOP =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF////uTpB5eXl////rZgQdQAAAAR0Uk5T////AEAqqfQAAABfSURBVHja7NVBCoAwDAXRSXr/O7tQkHShtCIinb8KhDzIJqE9DAICAgICKwBQOgQfAJT5UaD1QJsAOOtJYCfgYoM74EgQAgKLAvQAvwMyK5A5fNazxNcmICDwPrAJMADHnix+v0+20gAAAABJRU5ErkJggg==";

  // duplicate this in both clothingA & B
  string constant NONE =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAZQTFRF////AAAAVcLTfgAAAAF0Uk5TAEDm2GYAAAAdSURBVHja7MGBAAAAAMOg+VPf4ARVAQAAAHwTYAAQQAABpAJfkQAAAABJRU5ErkJggg==";

  function getAsset(uint256 assetNum) external pure returns (string memory) {
    if (assetNum == 54) {
      return CLOTHING_SHIRT___DUSTY_MAROON_MINERS_GARB;
    } else if (assetNum == 55) {
      return CLOTHING_SHIRT___DUSTY_NAVY_MINERS_GARB;
    } else if (assetNum == 56) {
      return CLOTHING_SHIRT___GRASS_SKIRT;
    } else if (assetNum == 57) {
      return CLOTHING_SHIRT___LEDERHOSEN;
    } else if (assetNum == 58) {
      return CLOTHING_SHIRT___MAGICIAN_UNIFORM_WITH_BLUE_CAPE;
    } else if (assetNum == 59) {
      return CLOTHING_SHIRT___MAGICIAN_UNIFORM_WITH_RED_CAPE;
    } else if (assetNum == 60) {
      return CLOTHING_SHIRT___NAKEY;
    } else if (assetNum == 61) {
      return CLOTHING_SHIRT___NODE_OPERATORS_VEST;
    } else if (assetNum == 62) {
      return CLOTHING_SHIRT___ORANGE_INFLATABLE_WATER_WINGS;
    } else if (assetNum == 63) {
      return CLOTHING_SHIRT___ORANGE_PRISON_UNIFORM;
    } else if (assetNum == 64) {
      return CLOTHING_SHIRT___PINK_TUTU;
    } else if (assetNum == 65) {
      return CLOTHING_SHIRT___PINK_AND_TEAL_DEFI_LENDING_TANKTOP;
    } else if (assetNum == 66) {
      return CLOTHING_SHIRT___RED_BEAR_LOVE_SHIRT;
    } else if (assetNum == 67) {
      return CLOTHING_SHIRT___RED_BEAR_MARKET_SHIRT;
    } else if (assetNum == 68) {
      return CLOTHING_SHIRT___RED_BULL_MARKET_SHIRT;
    } else if (assetNum == 69) {
      return CLOTHING_SHIRT___RED_DRESS_WITH_WHITE_DOTS;
    } else if (assetNum == 70) {
      return CLOTHING_SHIRT___RED_DRESS_WITH_WHITE_LACE;
    } else if (assetNum == 71) {
      return CLOTHING_SHIRT___RED_DRESS;
    } else if (assetNum == 72) {
      return CLOTHING_SHIRT___RED_ETH_SHIRT;
    } else if (assetNum == 73) {
      return CLOTHING_SHIRT___RED_FANNY_PACK;
    } else if (assetNum == 74) {
      return CLOTHING_SHIRT___RED_HOOLA_HOOP;
    } else if (assetNum == 75) {
      return CLOTHING_SHIRT___RED_HOOT_SHIRT;
    } else if (assetNum == 76) {
      return CLOTHING_SHIRT___RED_JESTERS_COLLAR;
    } else if (assetNum == 77) {
      return CLOTHING_SHIRT___RED_KNIT_SWEATER;
    } else if (assetNum == 78) {
      return CLOTHING_SHIRT___RED_LEG_WARMERS;
    } else if (assetNum == 79) {
      return CLOTHING_SHIRT___RED_OVERALLS;
    } else if (assetNum == 80) {
      return CLOTHING_SHIRT___RED_PINK_UNICORN_DEX_TANKTOP;
    } else if (assetNum == 81) {
      return CLOTHING_SHIRT___RED_PONCHO;
    } else if (assetNum == 82) {
      return CLOTHING_SHIRT___RED_PORTAL_SHIRT;
    } else if (assetNum == 83) {
      return CLOTHING_SHIRT___RED_PROOF_OF_STAKE_SHIRT;
    } else if (assetNum == 84) {
      return CLOTHING_SHIRT___RED_PROOF_OF_WORK_SHIRT;
    } else if (assetNum == 85) {
      return CLOTHING_SHIRT___RED_PUFFY_VEST;
    } else if (assetNum == 86) {
      return CLOTHING_SHIRT___RED_REKT_SHIRT;
    } else if (assetNum == 87) {
      return CLOTHING_SHIRT___RED_RASPBERRY_PI_NODE_TANKTOP;
    } else if (assetNum == 88) {
      return CLOTHING_SHIRT___RED_SKIRT_WITH_BLACK_AND_WHITE_DOTS;
    } else if (assetNum == 89) {
      return CLOTHING_SHIRT___RED_SKIRT;
    } else if (assetNum == 90) {
      return CLOTHING_SHIRT___RED_STRIPED_NECKTIE;
    } else if (assetNum == 91) {
      return CLOTHING_SHIRT___RED_SUIT_JACKET_WITH_GOLD_TIE;
    } else if (assetNum == 92) {
      return CLOTHING_SHIRT___RED_TANKTOP;
    } else if (assetNum == 93) {
      return CLOTHING_SHIRT___RED_TOGA;
    } else if (assetNum == 94) {
      return CLOTHING_SHIRT___RED_TUBE_TOP;
    } else if (assetNum == 95) {
      return CLOTHING_SHIRT___RED_VEST;
    } else if (assetNum == 96) {
      return CLOTHING_SHIRT___RED_WAGMI_SHIRT;
    } else if (assetNum == 97) {
      return CLOTHING_SHIRT___RED_WITH_PINK_AND_GREEN_DRESS;
    } else if (assetNum == 98) {
      return CLOTHING_SHIRT___RED_WITH_WHITE_APRON;
    } else if (assetNum == 99) {
      return CLOTHING_SHIRT___RED_WITH_WHITE_STRIPES_SOCCER_JERSEY;
    } else if (assetNum == 100) {
      return CLOTHING_SHIRT___TAN_CARGO_SHORTS;
    } else if (assetNum == 101) {
      return CLOTHING_SHIRT___VAMPIRE_BAT_WINGS;
    } else if (assetNum == 102) {
      return CLOTHING_SHIRT___WHITE_TUXEDO;
    } else if (assetNum == 103) {
      return CLOTHING_SHIRT___WHITE_AND_RED_STRIPED_BIB;
    } else if (assetNum == 104) {
      return CLOTHING_SHIRT___WHITE_WITH_RED_DRESS;
    } else if (assetNum == 105) {
      return CLOTHING_SHIRT___WHITE_WITH_RED_STRIPES_TANKTOP;
    }
    return NONE;
  }
}

// SPDX-License-Identifier: MIT
// OpenZeppelin Contracts (last updated v4.7.0) (utils/Strings.sol)

pragma solidity ^0.8.0;

/**
 * @dev String operations.
 */
library Strings {
    bytes16 private constant _HEX_SYMBOLS = "0123456789abcdef";
    uint8 private constant _ADDRESS_LENGTH = 20;

    /**
     * @dev Converts a `uint256` to its ASCII `string` decimal representation.
     */
    function toString(uint256 value) internal pure returns (string memory) {
        // Inspired by OraclizeAPI's implementation - MIT licence
        // https://github.com/oraclize/ethereum-api/blob/b42146b063c7d6ee1358846c198246239e9360e8/oraclizeAPI_0.4.25.sol

        if (value == 0) {
            return "0";
        }
        uint256 temp = value;
        uint256 digits;
        while (temp != 0) {
            digits++;
            temp /= 10;
        }
        bytes memory buffer = new bytes(digits);
        while (value != 0) {
            digits -= 1;
            buffer[digits] = bytes1(uint8(48 + uint256(value % 10)));
            value /= 10;
        }
        return string(buffer);
    }

    /**
     * @dev Converts a `uint256` to its ASCII `string` hexadecimal representation.
     */
    function toHexString(uint256 value) internal pure returns (string memory) {
        if (value == 0) {
            return "0x00";
        }
        uint256 temp = value;
        uint256 length = 0;
        while (temp != 0) {
            length++;
            temp >>= 8;
        }
        return toHexString(value, length);
    }

    /**
     * @dev Converts a `uint256` to its ASCII `string` hexadecimal representation with fixed length.
     */
    function toHexString(uint256 value, uint256 length) internal pure returns (string memory) {
        bytes memory buffer = new bytes(2 * length + 2);
        buffer[0] = "0";
        buffer[1] = "x";
        for (uint256 i = 2 * length + 1; i > 1; --i) {
            buffer[i] = _HEX_SYMBOLS[value & 0xf];
            value >>= 4;
        }
        require(value == 0, "Strings: hex length insufficient");
        return string(buffer);
    }

    /**
     * @dev Converts an `address` with fixed length of 20 bytes to its not checksummed ASCII `string` hexadecimal representation.
     */
    function toHexString(address addr) internal pure returns (string memory) {
        return toHexString(uint256(uint160(addr)), _ADDRESS_LENGTH);
    }
}