// SPDX-License-Identifier: MIT

pragma solidity ^0.8.9;

contract VF_Film_Metadata {
//***ITEM DATA SEPARATOR BEGIN
    bytes constant public data = '"name":"Vertifilms NFT collection, ABCDEFGHIJKLM    ... this is 400 bytes of metadata example",\n'
'"description":"Name of the movie 1 ... ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJK. ABCDEFGHIJKLMNOPQRSTUVWXYZ_ABCDEFGHIJKLMNOPQRSTUVWXYZ_ABCDEFGHIJKLMNOPQRSTUVWXYZ_ABCDEFGHIJKLMNOPQRSTUVWXYZ_ABCDEFGHIJKLMNOPQRSTUVWXYZ_ABCDEFGHIJKLMNOPQRSTUVWXYZ_ABCDEFGHIJKLMNOPQRSTUVWXYZ_ABCDEFGHIJKLMNOPQRSTUVWXYZ_ABCDE"';
//***ITEM DATA SEPARATOR END
}