/**
 *Submitted for verification at Etherscan.io on 2023-01-15
*/

// File: SquiggleOwl.sol


   //'ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc'    ,ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
  //.kWMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo   'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN
   //'::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::;.   .,::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::;
   // ,llllllllllllllllllll;.,llllllllllllllllllll,.;llllll;     .cllllll'.:llllll,.:lllllllllllllllllllc..cllllllllllllllllllll:.'llllllc.            'cllllllllllllllllll,       ;llllllllllllllllllll,.:llllll, .clllllc' .clllllc..clllllc'             
   //.xMMMMMMMMMMMMMMMMMMMMx;OMMMMMMMMMMMMMMMMMMMWd:0MMMMMWx.    cNMMMMMNlcXMMMMMWocXMMMMMMMMMMMMMMMMMMMXclNMMMMMMMMMMMMMMMMMMMMK:oWMMMMMX;            oWMMMMMMMMMMMMMMMMMWo      .OMMMMMMMMMMMMMMMMMMMWdlXMMMMMWo.cNMMMMMNc.oWMMMMMXclNMMMMMNc             
   //.OMMMMMMMMMMMMMMMMMMMWd:0MMMMMMMMMMMMMMMMMMMNl:XMMMMMWo     lWMMMMMXclNMMMMMNllNMMMMMMMMMMMMMMMMMMMK:oWMMMMMMMMMMMMMMMMMMMMO;xMMMMMM0'           .xWMMMMMMMMMMMMMMMMMNc      ,0MMMMMMMMMMMMMMMMMMMNolNMMMMMNc.oWMMMMMX;.dWMMMMM0:oWMMMMMX;             
   //'0MMMMMMMMMMMMMMMMMMMNl:XMMMMMMMMMMMMMMMMMMMXccNMMMMMNc    .dWMMMMMK:oWMMMMMXcoWMMMMMMMMMMMMMMMMMMMO;xWMMMMMMMMMMMMMMMMMMMWx;OMMMMMMO.           .OMMMMMMMMMMMMMMMMMMX;      ;XMMMMMMMMMMMMMMMMMMMXloWMMMMMX;.xWMMMMM0,.kMMMMMMO;xMMMMMM0'             
   //;XMMMMMWOllllo0WMMMMMXccNMMMMMWklllloKMMMMMMK:oWMMMMMX;    .kMMMMMMO;xWMMMMM0:xWMMMMMXxllllxXMMMMMMx;kMMMMMMKdllllkNMMMMMWNd:0MMMMMMx.           '0MMMMMMXkxxxxxxxxxxo.      cNMMMMMWklllloKMMMMMMKcxWMMMMM0'.kMMMMMMO.'0MMMMMMx;kMMMMMMO.             
   //cNMMMMMNc    .dWMMMMMK:oWMMMMMX;    .kMMMMMMO;xWMMMMM0,    '0MMMMMMk;kMMMMMMO:kMMMMMMO.    ,0WWWWWNo;0MMMMMMx.    :XWWWWWNKl:XMMMMMWo            ;XMMMMMWo.                  oWMMMMMX;    .kMMMMMMOckMMMMMMO.'0MMMMMMx.,KMMMMMWd;0MMMMMWx.             
   //oWMMMMMX;     ;oooooo:'xWMMMMM0,    '0MMMMMMk;kMMMMMMO.    ,KMMMMMWd:0MMMMMMx:0MMMMMMx.    .',,,,,,.;XMMMMMWo     .,,,,,,,'.cNMMMMMNc            cNMMMMMNc                  .xWMMMMM0,    'OMMMMMMkc0MMMMMMx.;KMMMMMWo.:NMMMMMNl:KMMMMMWo              
  //.xWMMMMMXo,,,,,,,,,,,,.'kMMMMMMO.    ,KMMMMMWd:0MMMMMMx.    :XMMMMMWl:KMMMMMWdcKMMMMMWo  .,,,,,,,,,'.cNMMMMMNc  .,,,,,,,,,'..oWMMMMMX;            oWMMMMMNkcccccccccc;.      .kMMMMMMO.    ,KMMMMMWdcKMMMMMWo.:NMMMMMNl.lWMMMMMXccNMMMMMNc              
  //.kMMMMMMMWWWWWWWWWWWWNo;0MMMMMMx.    :XMMMMMWl:KMMMMMWo     lNMMMMMNccNMMMMMNllNMMMMMNc .xWWWWWWWWW0:oWMMMMMX; .OWWWWWWWWWOl;dWMMMMMK,           .dWMMMMMMMMMMMMMMMMM0'      '0MMMMMMx.    :XMMMMMWolNMMMMMNc.lWMMMMMX:.dWMMMMMK:lWMMMMMX:              
  //'0MMMMMMMMMMMMMMMMMMMWl:KMMMMMWo     lNMMMMMNccNMMMMMNc     dWMMMMMK:oWMMMMMXcoWMMMMMX: .OMMMMMMMMM0;dWMMMMMK, ,KMMMMMMMMMk;;kMMMMMMO.           .kMMMMMMMMMMMMMMMMMMO.      ;KMMMMMWo     lNMMMMMNloWMMMMMX;.dWMMMMMK,.kMMMMMMO;dWMMMMMK,              
  //;KMMMMMMMMMMMMMMMMMMMNccNMMMMMNl     dWMMMMMK:oWMMMMMX:    .kMMMMMM0;dWMMMMMK:dWMMMMMK, ,KMMMMMMMMMk;kMMMMMMO. :XMMMMMMMMWd.;0MMMMMMk.           '0MMMMMMMMMMMMMMMMMWx.      :NMMMMMNl     dWMMMMMKcdWMMMMMK,.kMMMMMMO.'OMMMMMMk;kMMMMMMO.              
  //'dxxxxxxxxxxxkXMMMMMMK:lWMMMMMX:    .xMMMMMM0;dWMMMMMK,    .OMMMMMMk;kMMMMMMO:kMMMMMMO. .ox0WMMMMMWd;0MMMMMMx. 'dk0WMMMMMWo.:KMMMMMWd            ,KMMMMMWXOOkkOOOkkOk:       lWMMMMMX:    .xMMMMMM0ckMMMMMMO.'0MMMMMMk.,KMMMMMWd;0MMMMMMx.              
  //.''''''..    .kMMMMMM0;dWMMMMMK,    .OMMMMMMk;kMMMMMMO.    ,KMMMMMWd;OMMMMMMk:OMMMMMMk.    :XMMMMMWo:KMMMMMWd     lNMMMMMNc.cXMMMMMNl            :NMMMMMNl.                 .dWMMMMMK,    .OMMMMMMkc0MMMMMMk.,KMMMMMWd.:XMMMMMWo:KMMMMMWd.              
 //.oNNNNNNO'    .OMMMMMMk;kMMMMMMO.    ,KMMMMMWd;OMMMMMMk.    ;XMMMMMWo:KMMMMMWdcKMMMMMWd     cNMMMMMNccXMMMMMNl     oWMMMMMX:.lNMMMMMX:            lNMMMMMX:                  .kMMMMMMO.    ,KMMMMMWxcKMMMMMWd.:XMMMMMWl.lNMMMMMNccXMMMMMNl               
 //.kMMMMMM0;....:KMMMMMWx;OMMMMMMO,....lXMMMMMWo:KMMMMMWk'....oNMMMMMNccXMMMMMNocXMMMMMWd.....xWMMMMMK:lNMMMMMNl....'kWMMMMM0;.dWMMMMMNo;;;;;;;;;;'.dWMMMMMNo;;;;;;;,;;,.      '0MMMMMMO,....lXMMMMMWolXMMMMMNl.lNMMMMMN:.oWMMMMMK:lNMMMMMNx;;;;;,;;,;'.   
 //'0MMMMMMWXKKKKXWMMMMMWo:KMMMMMMWXKKKKNWMMMMMNlcXMMMMMMNXKKKXNMMMMMMX:lNMMMMMXloNMMMMMWNKKKKXNMMMMMM0;dWMMMMMWNKKKKXWMMMMMMk;;kMMMMMMMWWWWWWWWWWWk;kMMMMMMMWWWWWWWWWWWX:      ,KMMMMMMNXKKKKNWMMMMMNloNMMMMMNd;kWMMMMMXo:OMMMMMM0;dWMMMMMMWWWWWWWWWWWO'   
 //,KMMMMMMMMMMMMMMMMMMMNccXMMMMMMMMMMMMMMMMMMMX:lNMMMMMMMMMMMMMMMMMMM0:dWMMMMMKcdWMMMMMMMMMMMMMMMMMMMk;xMMMMMMMMMMMMMMMMMMMWx;cOMMMMMMMMMMMMMMMMMMx;OMMMMMMMMMMMMMMMMMMK;      :XMMMMMMMMMMMMMMMMMMMXcdWMMMMMMWNWMMMMMMMWWWMMMMMMk;xMMMMMMMMMMMMMMMMMMO.   
 //:XMMMMMMMMMMMMMMMMMMMX:lNMMMMMMMMMMMMMMMMMMM0:dWMMMMMMMMMMMMMMMMMMMk;xMMMMMMO:xMMMMMMMMMMMMMMMMMMMMx;OMMMMMMMMMMMMMMMMMMMWo:dKMMMMMMMMMMMMMMMMMWo:KMMMMMMMMMMMMMMMMMM0'      lNMMMMMMMMMMMMMMMMMMM0cxMMMMMMMMMMMMMMMMMMMMMMMMMWd;OMMMMMMMMMMMMMMMMMWx.   
 //:0KKKKKKKKKKKKKKKKKKKx,c0KKKKKXWMMMMWXKKKKKKd,lKKKKKKKKKKKKKKKKKKKKo,dKKKKKKo,dKKKKKKKKKKKKKKKKKKK0c,xKKKKKKKKKKKKKKKKKKK0:;dkKKKKKKKKKKKKKKKKK0:;OKKKKKKKKKKKKKKKKKKd.      c0KKKKKKKKKKKKKKKKKKKd;dKKKKKKKKKKKKKKKKKKKKKKKKK0c,xKKKKKKKKKKKKKKKKK0c    
//..''''''''''''''''''''...''''''cKMMMM0:''''''...''''''''''''''''''''...''''''...''''''''''''''''''''...'''''''''''''''''''.....'''''''''''''''''...'''''''''''''''''''..     ..''''''''''''''''''''...''''''''''''''''''''''''''...''''''''''''''''''.    
//O000000000000000000000000000000KWMMMMNK00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000d.   :O000000000000000000000000000000000000000000000000000000000000000000000000l.  
//00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000d.   c0000000000000000000000000000000000000000000000000000000000000000000000000c   

pragma solidity ^0.5.10;


contract SquiggleOwl {


    string public message;

 
    constructor(string memory initMessage) public {

        message = initMessage;
    }

    function update(string memory newMessage) public {
        message = newMessage;
    }
}