// SPDX-License-Identifier: MIT
pragma solidity ^0.8.9;

import "@openzeppelin/contracts/utils/Strings.sol";

library Hat {
  using Strings for uint256;
  string constant HAT_HAT___ASTRONAUT_HELMET =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABhQTFRFQFbNs7vrAAAAS2LeOk65UGv/6Ov5////kv0KBAAAAAh0Uk5T/////////wDeg71ZAAAA00lEQVR42uzV2w7CIAyA4bYDfP83lnKYBS3SmV2YtJfG/7ObGYPHjwO3AtTmIkB0tFkR8D2HPDqhAZzHGGteCBtAnMMwZAE+9JoAy77+CUtBAUpPhJgQsRPbAC/A38faM6ELoC4g+i4YgKlvwj5wVOBFJDMw9XUFMyB6IzDegoTXgKFnIFg3kL0ZEMLZbwPTCssFdGC8CHUB7XEGISx79UCRwqrXjzQK/Tigcv3WIy0/j6EN8O8bj7T8+duY3wtb+d2vNgcccMABBxxwwIH/BJ4CDADNMmO1DGqiPwAAAABJRU5ErkJggg==";

  string constant HAT_HAT___BAG_OF_ETHEREUM =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABJQTFRFspJTAAAAjH9/f3JyMiMV////vWa9KwAAAAZ0Uk5T//////8As7+kvwAAAGJJREFUeNrs0EkOgDAMQ9EM7f2vTAv7GuEd+tlGfnISU0zmeR8qH5EOsPJCUMAY6TTQBc7AnTdO2PlSggCqygO62gDmatC7wfwOPD9wgLCANwMAAAAAAAAAAAAAAPBj4BJgAB87Towu1B9ZAAAAAElFTkSuQmCC";

  string constant HAT_HAT___BLACK_BOWLER_HAT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAZQTFRFAAAA////pdmf3QAAAAJ0Uk5T/wDltzBKAAAAPElEQVR42uzSsQkAIBAEwfv+mxaMPhOUD4TZAiba1GMBTAPZ3QPJWZgE0vIBAAAAAAAAAAAAAPwJLAEGADaZD98VtpqsAAAAAElFTkSuQmCC";

  string constant HAT_HAT___BLACK_TOP_HAT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAZQTFRFAAAA////pdmf3QAAAAJ0Uk5T/wDltzBKAAAAOElEQVR42uzSsQkAMAwEsff+S6dJkd4EY9ANoOpSzfIVyA2wGMjT1EgAAAAAAAAAAAAAAOh1BBgAMcgPvRKkebAAAAAASUVORK5CYII=";

  string constant HAT_HAT___BLACK_AND_WHITE_STRIPED_JAIL_CAP =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFAAAA////zs7O////IzDhUgAAAAR0Uk5T////AEAqqfQAAABkSURBVHja7NJBDoAwCETRgd7/ziqa6MY2GRYu/JN0RfqgDRrNaF6t2IAUlSmhVfvVEO8l5X0/5QCRcSVNYO9csSc4PvE83wDjCbiLVO/Pxia2VxkAAAAAAAAAAAAAAODfwCbAABLfLurW3p3aAAAAAElFTkSuQmCC";

  string constant HAT_HAT___BLACK_WITH_BLUE_HEADPHONES =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAlQTFRFAAAAUGv/////v7SHiAAAAAN0Uk5T//8A18oNQQAAAFVJREFUeNrs0zEKwCAQBdHR+x86nSCYZY2NxvmlMK9YkLo4tgZo+wTQbR7ookAg00cCqT4QyPXvwvCVMgIKNwHLR/zPbxQQEBAQEBAQEBAQOBp4BBgAApMfXVc0ju8AAAAASUVORK5CYII=";

  string constant HAT_HAT___BLACK_WITH_BLUE_TOP_HAT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFAAAAUGv/S2Le////GFS2BwAAAAR0Uk5T////AEAqqfQAAAA9SURBVHja7NKhEQAgEASx5+i/ZxAI/A+DyRYQtTWb1VOgToAGkGTs8guoq18jAQAAAAAAAAAAAACg1xJgAMovL02Jgj8HAAAAAElFTkSuQmCC";

  string constant HAT_HAT___BLUE_BASEBALL_CAP =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFSGz/AAAAOlfV////hul92gAAAAR0Uk5T////AEAqqfQAAABWSURBVHja7NNBDgAQDETRDve/sxhrKrWTXyI289I0RH+s+B2Qqw4o2lyqAjPvrRrgfCpElvd5EHJgtbAd5iXgix7eQaUD/gIAAAAAAAAAAAAAAMAQYABuYy8sFMG46QAAAABJRU5ErkJggg==";

  string constant HAT_HAT___BLUE_UMBRELLA_HAT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFUGv/S2LeAAAA////rmvP5AAAAAR0Uk5T////AEAqqfQAAACGSURBVHja7NPRCsAgCAXQq/3/P09TNgYzZL1scH3IIu6BojA2C98GNOsdYEERgQBYGSjjgHjYERtKAou4572FUxCPgJ65mKSkXUCvVAJpaQ+45ROoBTzmdVhkbtvCuwHzYNoB4rpyAxJd4mq1dYTFy/rdXyBAgAABAgQIECBAgACBnToEGABRVi6KAJCJVwAAAABJRU5ErkJggg==";

  string constant HAT_HAT___BULB_HELMET =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABhQTFRFq6KZfW1tAAAA9vOZW2mA//7gLzYz////cFdYaAAAAAh0Uk5T/////////wDeg71ZAAAAk0lEQVR42uzUzQqAIBAE4G0ye/83biejH1AxPXRo5tCC4Ye6oq2DsfpveEYALB70A1hmBj8GgLin2ogaYGe6AHvkPWDWJlh+8wQmD6emmkbbAN6/6PNC4MyjxsKdzABg6xwIHgKpxkJDsysoAWg+A37S0q96DL+4Bzy8e+16D4YfFAECBAgQIECAAAECBHwGbAIMAJDFa9/XI/3JAAAAAElFTkSuQmCC";

  string constant HAT_HAT___CHERRY_ON_TOP =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRFgCEgAAAAbpZw1VdW////VaIaLQAAAAV0Uk5T/////wD7tg5TAAAAUUlEQVR42uzSsQ2AUAwDUV9g/5nZgHzJSDSXOnlO4dzlZN2ADmCGBmC6D3iPXwEyoQDIlYQGyBdA1YP1/qBIAgICAgICAgICAgICAv8BjwADAHRiP3omvhMlAAAAAElFTkSuQmCC";

  string constant HAT_HAT___CRYPTO_INFLUENCER_BLUEBIRD =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRFW6zhAAAAUaHW6sU3////ODu4hwAAAAV0Uk5T/////wD7tg5TAAAAWklEQVR42uzSQQ7AIAhE0Rno/c9calzbBNJ08//eF0V0DdOngD0DLHkCOK1wH3CmClg1b1BP2Lk9g1W4/QvxHD/P4WUPovpzkQAAAAAAAAAAAAAAAABm3QIMAMaXP0tNIpWYAAAAAElFTkSuQmCC";

  string constant HAT_HAT___GIANT_SUNFLOWER =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRF6sU3AAAA07M2a1cx////BrLbjgAAAAV0Uk5T/////wD7tg5TAAABQElEQVR42uyW3RaEIAiEYfT9n3n9Qa0OINvupV500povZIii7A4uw7+DfD0Rgb8GzMdW/SQYwZD+WOInYK3uAF3V7mXCANyC2QIghKWSxRgAJDFILEW2zkI5aIRyWDJbr7sgMUCOcPR6HdwJffdWQeiF1AlpDrILyqjESkhJJo1gFaRRiUUw9Q1RcxqrRBbPrvpKEGd5B+CRtnRfTyOj7AOG4wpg+MEegJd3KkCJgfQAoAEQAADuFioF7OZgIp4uYMh5ayP6SI8A2uLeRuldjxBaGeg9jaxeeiW0UlYbmg3AhSBlGAfM/jFeRpBNIEdPyzqbYDZVIE8OckVAJVhtHe0irXMYIRgA9It9G32CMABDIiGMCaJtvWw4a4DLevjrLCl8/3kXO94Dcn2BfvnBCIwDOIADOIADOIAD+DPgI8AAbcQ3unsV8Z4AAAAASUVORK5CYII=";

  string constant HAT_HAT___GOLD_CHALICE =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABJQTFRFAAAA0bA73sdfq5Qzj0Eq////NS+KlAAAAAZ0Uk5T//////8As7+kvwAAAGBJREFUeNrs0UEOwCAIRFGmyP2vXFr3kEi66h+WmoegRRXbKa+Uh1dGcjsHlrLOgRTUPOBr4BG86RGN4F2LDtAQCMUMyB2MgPcXZiPEcAQAAAAAAAAAAAAAAIA/A7cAAwALG08jVMTV2QAAAABJRU5ErkJggg==";

  string constant HAT_HAT___GRADUATION_CAP_WITH_BLUE_TASSEL =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFAAAANTU1UGv/////Wu4LrwAAAAR0Uk5T////AEAqqfQAAABZSURBVHja7NLRCoBACAXRUf//n1s26DFCCQrmgk/iQVBqGN4GYASw0wa40gPgiXDTyukGWXGOR3UBYhGr+sAepw8Mz5jfeGUBAQEBAQEBAQEBAYEfA4cAAwBT9i8xSenp1QAAAABJRU5ErkJggg==";

  string constant HAT_HAT___GRADUATION_CAP_WITH_RED_TASSEL =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFAAAANTU1/1BZ////DFVn2gAAAAR0Uk5T////AEAqqfQAAABZSURBVHja7NLRCoBACAXRUf//n1s26DFCCQrmgk/iQVBqGN4GYASw0wa40gPgiXDTyukGWXGOR3UBYhGr+sAepw8Mz5jfeGUBAQEBAQEBAQEBAYEfA4cAAwBT9i8xSenp1QAAAABJRU5ErkJggg==";

  string constant HAT_HAT___GREEN_GOO =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFUf9aV9RdAAAA////8OJe4gAAAAR0Uk5T////AEAqqfQAAABZSURBVHja7NMxDsAwCATBA/7/54DdpwDFLrInWgYkhGIYAXwOeGYCuCTz8C6w+lOQ9YDqrso0N1DY3mFwhZqu0Rlfx58B4jbANwIAAAAAAAAAAAD8FngEGACpVi+IuGeNiwAAAABJRU5ErkJggg==";

  string constant HAT_HAT___NODE_OPERATORS_YELLOW_HARDHAT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRF6sU32rg0AAAA6sU2////adQM4wAAAAV0Uk5T/////wD7tg5TAAAAZklEQVR42uzSQQoAIQxD0bZ6/zNPI4K7LjrIMPADXeYRRJsvY3eBWOkDYSvRBcJcfS+FEsi+65qABqheT6gWHGB+A+T7DQEjr7lgx739kVQu69e/MgAAAAAAAAAAAAAAwK+BR4ABAHTtPsbMRIz4AAAAAElFTkSuQmCC";

  string constant HAT_HAT___NONE =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAZQTFRF////AAAAVcLTfgAAAAF0Uk5TAEDm2GYAAAAdSURBVHja7MGBAAAAAMOg+VPf4ARVAQAAAHwTYAAQQAABpAJfkQAAAABJRU5ErkJggg==";

  string constant HAT_HAT___PINK_BUTTERFLY =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFyqLVwkvlRUVF////T//+XQAAAAR0Uk5T////AEAqqfQAAABZSURBVHja7NMxCgAgDEPRtN7/zmpxF5pNv6BOPpqAGubS40Ce3QSk9Tr31QUilPtoR5Ai4zLApcQ1gVViTWAAqg6MCBXf64C/AAAAAAAAAAAAAADwNzAFGACPxy+cXbN/7gAAAABJRU5ErkJggg==";

  string constant HAT_HAT___PINK_SUNHAT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF6Jr/AAAAyqLV////Ci+i2QAAAAR0Uk5T////AEAqqfQAAABiSURBVHja7NNBCoAwDETRmXj/O7uwIBUTagsi8ie7Qh5DS7UtRt8G3DIJ2IpjKiIHHDrHz4FuvxByoNsPv9mgXf2lQfYeuulexMMNho/1878AAAAAAAAAAAAAAACwkl2AAQAHsi65WX3y4QAAAABJRU5ErkJggg==";

  string constant HAT_HAT___POLICE_CAP =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFKjFYAAAA////////dNMazAAAAAR0Uk5T////AEAqqfQAAABUSURBVHja7NIxDgAgCENRqve/sxsyMdRBTX6ZeYnFmIeJpwFlPECRkQOU/U7ogLHHAWbZD6uD+gSvxGxBunPGJD7+ygAAAAAAAAAAAAAAAHeBJcAASGsvC6AT5bIAAAAASUVORK5CYII=";

  string constant HAT_HAT___RED_ASTRONAUT_HELMET =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABhQTFRFzUBI67O2AAAA3ktTuTpB+ejp/1BZ////IcbzjgAAAAh0Uk5T/////////wDeg71ZAAAA00lEQVR42uzV2w7CIAyA4bYDfP83lnKYBS3SmV2YtJfG/7ObGYPHjwO3AtTmIkB0tFkR8D2HPDqhAZynlGpeCBtAnMMwZAE+9JoAy77+CUtBAUpPhBgRsRPbAC/A38faM6ELoC4g+i4YgKlvwj5wVOBFRDMw9XUFMyB6IzDegojXgKFnIFg3kL0ZEMLZbwPTCssFdGC8CHUB7XEGISx79UCRwqrXjzQK/Tigcv3WIy0/j6EN8O8bj7T8+duY3wtb+d2vNgcccMABBxxwwIH/BJ4CDADjCWO1fTN4AwAAAABJRU5ErkJggg==";

  string constant HAT_HAT___RED_BASEBALL_CAP =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF/1BZAAAAzUBI////ldQ1tgAAAAR0Uk5T////AEAqqfQAAABcSURBVHja7NJBCsAgDETRjL3/ncVxbVPiQik/iriZRwiJZ7PickCuOqBo46gKjLyvaoDzqRBZ3u+LkAOzheUwPwL+aGMPKh38ZJUBAAAAAAAAAAAAAABOAl2AAQA4Ti8sNA+R7wAAAABJRU5ErkJggg==";

  string constant HAT_HAT___RED_DEFI_WIZARD_HAT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRF/1BZAAAAzUBI6sU3////FtBcqgAAAAV0Uk5T/////wD7tg5TAAAAaklEQVR42uzSMQ7AMAgDQAP5/5vrkJ1Wzlh7DhcsgXUZfHgTzAUQASRCBSIKBcgb8Pd5/gU48yUDXD9JTPMjwPlOqkDX3w2WDOwGRFSg+3ODlC8xT65P2YABAwYMGDBgwIABAwb+CjwCDACqJj7wsv4GLgAAAABJRU5ErkJggg==";

  string constant HAT_HAT___RED_SHOWER_CAP =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAlQTFRF/1BZzUBI////gty5ygAAAAN0Uk5T//8A18oNQQAAAIBJREFUeNrs00sOgCAMBNCp9z8031ai1lCIcTOgiTHOQ1vBsTnwLQAIsArUcD7quQBYviNBICd0cRUkAoxvb1cyD5xpU8T7DAdoSR1vdfCBEuxTjUANyvK4zkgRW2TsifdHOW28PR5s49Nt/LKZCBAgQIAAAQIECBAgQGBjJAEGAIGBHsa3dBv/AAAAAElFTkSuQmCC";

  string constant HAT_HAT___RED_SPORTS_HELMET =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRFAAAA/1BZ3ktTNTU1////BJreHQAAAAV0Uk5T/////wD7tg5TAAAAcUlEQVR42uzVQQ6AIBBD0c/A/c+sgsadizJGje16eAkJU2iT4eUAPTpA6UEF9vMl0ABKHUC9Eu4F9hvEBBAjEoAwlgqgzeUByIMG8oDn30HCLrSzDNHW+WiEkDtxzVYG3/5YDBgwYMCAAQMG/gksAgwAPmU+k3i4SEUAAAAASUVORK5CYII=";

  string constant HAT_HAT___RED_UMBRELLA_HAT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF/1BZ3ktTAAAA////hP6nfQAAAAR0Uk5T////AEAqqfQAAACGSURBVHja7NPRCsAgCAXQq/3/P09TNgYzZL1scH3IIu6BojA2C98GNOsdYEERgQBYGSjjgHjYERtKAou4572FUxCPgJ65mKSkXUCvVAJpaQ+45ROoBTzmdVhkbtvCuwHzYNoB4rpyAxJd4mq1dYTFy/rdXyBAgAABAgQIECBAgACBnToEGABRVi6KAJCJVwAAAABJRU5ErkJggg==";

  string constant HAT_HAT___TAN_COWBOY_HAT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFnIFNAAAAiW8+////s4CSSAAAAAR0Uk5T////AEAqqfQAAAB7SURBVHja7NNLCsAgDATQmfT+d64frNkYia4Kk01AmYemFc9lIdgj6VoeIAB+LQ/UIIytBcIGgFl3joFeJ4DPl3MwB5TB03zeuPoWCK4/48EgEJ/ebMRXArb3nxIzM6hbrsZa7le+fgsCBAgQIECAAAECBAgQ8HPgFWAAHsIuMYdXW0IAAAAASUVORK5CYII=";

  string constant HAT_HAT___TAN_SUNHAT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFnIFNAAAAiW8+////s4CSSAAAAAR0Uk5T////AEAqqfQAAABiSURBVHja7NNBCoAwDETRmXj/O7uwIBUTagsi8ie7Qh5DS7UtRt8G3DIJ2IpjKiIHHDrHz4FuvxByoNsPv9mgXf2lQfYeuulexMMNho/1878AAAAAAAAAAAAAAACwkl2AAQAHsi65WX3y4QAAAABJRU5ErkJggg==";

  string constant HAT_HAT___TINY_BLUE_HAT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFAAAAUGv/S2Le////GFS2BwAAAAR0Uk5T////AEAqqfQAAABBSURBVHja7NLBCQAgEAPBnPbfs2IDgveT2QKGPJLZLIALkFMHqF0DSMbYQN6BqusEPwAAAAAAAAAAAACAr4ElwABPPi+9mXrDgwAAAABJRU5ErkJggg==";

  string constant HAT_HAT___TINY_RED_HAT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF/1BZAAAA3ktT////4F6kDAAAAAR0Uk5T////AEAqqfQAAABASURBVHja7NKxDQAwCANBIPvvHJQFKOii+wFOLhxnWQAmILsNkNHlBqhaAW/AIPgBAAAAAAAAAAAAAHwNXAEGAORLL8ds9TzwAAAAAElFTkSuQmCC";

  string constant HAT_HAT___WHITE_BOWLER_HAT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF////AAAA5eXl////vy5XywAAAAR0Uk5T////AEAqqfQAAABNSURBVHja7NIxCgAgDATBO/3/n4UgwSpCLGx2+wxXRPMxAVwAR33AitwF9n0tqNqfgDtAntcbigXjiE8EAAAAAAAAAAAAAAD4AiwBBgASDy9vioThbAAAAABJRU5ErkJggg==";

  string constant HAT_HAT___WHITE_TOP_HAT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF////AAAA5eXl////vy5XywAAAAR0Uk5T////AEAqqfQAAABLSURBVHja7NIhDgAgDEPRFe5/Z8wCqIpNIPi1y14qGrOZcEdlqoAiI4BngA6gCrDffQfTYFwpLrE9ZQAAAAAAAAAAAAAAgM+BJcAAxBQu9Xnq5qoAAAAASUVORK5CYII=";

  string constant HAT_HAT___WHITE_AND_RED_BASEBALL_CAP =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRF////AAAAzUBI5eXl////AWgimgAAAAV0Uk5T/////wD7tg5TAAAAXklEQVR42uzSQQrAIAxE0Yn1/mcWgxQX1UDc1T+Ku7wEVfUw+jtgnjxgKn1ZFuj1vi0HeH0oKKr3cyNofXkDCEbQd/O3dw4Yz/dMufcrAwAAAAAAAAAAAAAAHKQJMACYKT7BzliRQQAAAABJRU5ErkJggg==";

  string constant HAT_HAT___WHITE_WITH_RED_HEADPHONES =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF////AAAA/1BZ////kuAAcAAAAAR0Uk5T////AEAqqfQAAABrSURBVHja7NPRCoAgEETRHfv/fy6EJHB3s8SXuvOmOEcR1rbJ2EpALa8AyVoSIgQu9Uo8BVTvPZMIlvTD5T3QFWLBBVS644dQNArIfMB9w0eB6U+sUzCwtX4aAQAAAAAAAAAAAAD+DewCDADEWi6TIEdx5AAAAABJRU5ErkJggg==";

  string constant HAT_HAT___WHITE_WITH_RED_TOP_HAT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABJQTFRF////AAAA5eXl3ktT/1BZ////42DItQAAAAZ0Uk5T//////8As7+kvwAAAFJJREFUeNrs0jEOwDAIBEHOOP//slOgOBXFufRuizQCiXgOi26oygUUlQB8IDPnW5qANiAH+A7oj2g2GL/MTzx+ZQAAAAAAAAAAAAAAgMuBJcAAz8NOWX9yyCQAAAAASUVORK5CYII=";

  // TODO: Will need to remap hats & OptionsHats
  function getAsset(uint256 assetNum) external pure returns (string memory) {
    if (assetNum == 0) {
      return HAT_HAT___ASTRONAUT_HELMET;
    } else if (assetNum == 1) {
      return HAT_HAT___BAG_OF_ETHEREUM;
    } else if (assetNum == 2) {
      return HAT_HAT___BLACK_BOWLER_HAT;
    } else if (assetNum == 3) {
      return HAT_HAT___BLACK_TOP_HAT;
    } else if (assetNum == 4) {
      return HAT_HAT___BLACK_AND_WHITE_STRIPED_JAIL_CAP;
    } else if (assetNum == 5) {
      return HAT_HAT___BLACK_WITH_BLUE_HEADPHONES;
    } else if (assetNum == 6) {
      return HAT_HAT___BLACK_WITH_BLUE_TOP_HAT;
    } else if (assetNum == 7) {
      return HAT_HAT___BLUE_BASEBALL_CAP;
    } else if (assetNum == 8) {
      return HAT_HAT___BLUE_UMBRELLA_HAT;
    } else if (assetNum == 9) {
      return HAT_HAT___BULB_HELMET;
    } else if (assetNum == 10) {
      return HAT_HAT___CHERRY_ON_TOP;
    } else if (assetNum == 11) {
      return HAT_HAT___CRYPTO_INFLUENCER_BLUEBIRD;
    } else if (assetNum == 12) {
      return HAT_HAT___GIANT_SUNFLOWER;
    } else if (assetNum == 13) {
      return HAT_HAT___GOLD_CHALICE;
    } else if (assetNum == 14) {
      return HAT_HAT___GRADUATION_CAP_WITH_BLUE_TASSEL;
    } else if (assetNum == 15) {
      return HAT_HAT___GRADUATION_CAP_WITH_RED_TASSEL;
    } else if (assetNum == 16) {
      return HAT_HAT___GREEN_GOO;
    } else if (assetNum == 17) {
      return HAT_HAT___NODE_OPERATORS_YELLOW_HARDHAT;
    } else if (assetNum == 18) {
      return HAT_HAT___NONE;
    } else if (assetNum == 19) {
      return HAT_HAT___PINK_BUTTERFLY;
    } else if (assetNum == 20) {
      return HAT_HAT___PINK_SUNHAT;
    } else if (assetNum == 21) {
      return HAT_HAT___POLICE_CAP;
    } else if (assetNum == 22) {
      return HAT_HAT___RED_ASTRONAUT_HELMET;
    } else if (assetNum == 23) {
      return HAT_HAT___RED_BASEBALL_CAP;
    } else if (assetNum == 24) {
      return HAT_HAT___RED_DEFI_WIZARD_HAT;
    } else if (assetNum == 25) {
      return HAT_HAT___RED_SHOWER_CAP;
    } else if (assetNum == 26) {
      return HAT_HAT___RED_SPORTS_HELMET;
    } else if (assetNum == 27) {
      return HAT_HAT___RED_UMBRELLA_HAT;
    } else if (assetNum == 28) {
      return HAT_HAT___TAN_COWBOY_HAT;
    } else if (assetNum == 29) {
      return HAT_HAT___TAN_SUNHAT;
    } else if (assetNum == 30) {
      return HAT_HAT___TINY_BLUE_HAT;
    } else if (assetNum == 31) {
      return HAT_HAT___TINY_RED_HAT;
    } else if (assetNum == 32) {
      return HAT_HAT___WHITE_BOWLER_HAT;
    } else if (assetNum == 33) {
      return HAT_HAT___WHITE_TOP_HAT;
    } else if (assetNum == 34) {
      return HAT_HAT___WHITE_AND_RED_BASEBALL_CAP;
    } else if (assetNum == 35) {
      return HAT_HAT___WHITE_WITH_RED_HEADPHONES;
    } else if (assetNum == 36) {
      return HAT_HAT___WHITE_WITH_RED_TOP_HAT;
    }
    return HAT_HAT___ASTRONAUT_HELMET;
  }
}

// SPDX-License-Identifier: MIT
// OpenZeppelin Contracts (last updated v4.7.0) (utils/Strings.sol)

pragma solidity ^0.8.0;

/**
 * @dev String operations.
 */
library Strings {
    bytes16 private constant _HEX_SYMBOLS = "0123456789abcdef";
    uint8 private constant _ADDRESS_LENGTH = 20;

    /**
     * @dev Converts a `uint256` to its ASCII `string` decimal representation.
     */
    function toString(uint256 value) internal pure returns (string memory) {
        // Inspired by OraclizeAPI's implementation - MIT licence
        // https://github.com/oraclize/ethereum-api/blob/b42146b063c7d6ee1358846c198246239e9360e8/oraclizeAPI_0.4.25.sol

        if (value == 0) {
            return "0";
        }
        uint256 temp = value;
        uint256 digits;
        while (temp != 0) {
            digits++;
            temp /= 10;
        }
        bytes memory buffer = new bytes(digits);
        while (value != 0) {
            digits -= 1;
            buffer[digits] = bytes1(uint8(48 + uint256(value % 10)));
            value /= 10;
        }
        return string(buffer);
    }

    /**
     * @dev Converts a `uint256` to its ASCII `string` hexadecimal representation.
     */
    function toHexString(uint256 value) internal pure returns (string memory) {
        if (value == 0) {
            return "0x00";
        }
        uint256 temp = value;
        uint256 length = 0;
        while (temp != 0) {
            length++;
            temp >>= 8;
        }
        return toHexString(value, length);
    }

    /**
     * @dev Converts a `uint256` to its ASCII `string` hexadecimal representation with fixed length.
     */
    function toHexString(uint256 value, uint256 length) internal pure returns (string memory) {
        bytes memory buffer = new bytes(2 * length + 2);
        buffer[0] = "0";
        buffer[1] = "x";
        for (uint256 i = 2 * length + 1; i > 1; --i) {
            buffer[i] = _HEX_SYMBOLS[value & 0xf];
            value >>= 4;
        }
        require(value == 0, "Strings: hex length insufficient");
        return string(buffer);
    }

    /**
     * @dev Converts an `address` with fixed length of 20 bytes to its not checksummed ASCII `string` hexadecimal representation.
     */
    function toHexString(address addr) internal pure returns (string memory) {
        return toHexString(uint256(uint160(addr)), _ADDRESS_LENGTH);
    }
}