/**
 *Submitted for verification at Etherscan.io on 2022-03-21
*/

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

contract GenesisFaces {
    function G_Face(uint32 traitId_) public pure returns (string[2] memory) {
        string memory _header = "iVBORw0KGgoAAAANSUhEUgAAACIAAAAiBAMAAADIaRbxAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAZdEVYdFNvZnR3YXJlAEFkb2JlIEltYWdlUmVhZHlxyWU8AAAAGFBMVEVHcE";
        if (traitId_ == 0) return  ["Face1", string(abi.encodePacked(_header, "z/z4QAAADjuXbHoGSsilVvWTeEakISyhCDAAAAAXRSTlMAQObYZgAAAKhJREFUKM/dkEEOwiAQRcmcwMEL2BG7p9MLVOgFCuyNSS/g/RdOKaU1bl35E1g8Psz/KPVPIlq2ywEEJgVOVwDzgEjtgMUkp9EizrJWAoky4Upu3INjFLQRoxsIuGolV/2A2Z7tTsSj2tDfqaMyHRyegNL0nF5bHtOL2aTAzCUPUDYu6vYaJj+Mew0J9UXGFL0fD+Xb6G3NU9q7z0tyzfs6fItA+R9/pjdTFxnoDQsrmwAAAABJRU5ErkJggg=="))];
        if (traitId_ == 1) return  ["Face2", string(abi.encodePacked(_header, "zAnGMAAACri1mWeEuCaEBUQyljUDKnHTBhAAAAAXRSTlMAQObYZgAAAKhJREFUKM/dkEEOwiAQRcmcwMEL2BG7p9MLVOgFCuyNSS/g/RdOKaU1bl35E1g8Psz/KPVPIlq2ywEEJgVOVwDzgEjtgMUkp9EizrJWAoky4Upu3INjFLQRoxsIuGolV/2A2Z7tTsSj2tDfqaMyHRyegNL0nF5bHtOL2aTAzCUPUDYu6vYaJj+Mew0J9UXGFL0fD+Xb6G3NU9q7z0tyzfs6fItA+R9/pjdTFxnoDQsrmwAAAABJRU5ErkJggg=="))];
        if (traitId_ == 2) return  ["Face3", string(abi.encodePacked(_header, "yAaEIAAAByXTtkUDJWRSs4LRxCNSHL20s4AAAAAXRSTlMAQObYZgAAAKhJREFUKM/dkEEOwiAQRcmcwMEL2BG7p9MLVOgFCuyNSS/g/RdOKaU1bl35E1g8Psz/KPVPIlq2ywEEJgVOVwDzgEjtgMUkp9EizrJWAoky4Upu3INjFLQRoxsIuGolV/2A2Z7tTsSj2tDfqaMyHRyegNL0nF5bHtOL2aTAzCUPUDYu6vYaJj+Mew0J9UXGFL0fD+Xb6G3NU9q7z0tyzfs6fItA+R9/pjdTFxnoDQsrmwAAAABJRU5ErkJggg=="))];
        if (traitId_ == 3) return  ["Face4", string(abi.encodePacked(_header, "xANCEAAAA5Lh4yKBkrIxUcFg4hGxH3tvhKAAAAAXRSTlMAQObYZgAAAKhJREFUKM/dkEEOwiAQRcmcwMEL2BG7p9MLVOgFCuyNSS/g/RdOKaU1bl35E1g8Psz/KPVPIlq2ywEEJgVOVwDzgEjtgMUkp9EizrJWAoky4Upu3INjFLQRoxsIuGolV/2A2Z7tTsSj2tDfqaMyHRyegNL0nF5bHtOL2aTAzCUPUDYu6vYaJj+Mew0J9UXGFL0fD+Xb6G3NU9q7z0tyzfs6fItA+R9/pjdTFxnoDQsrmwAAAABJRU5ErkJggg=="))];
        if (traitId_ == 4) return  ["Face5", string(abi.encodePacked(_header, "wAAAD/jSC3ZBV9PwpPJgQQBQAgDQD59sM9AAAAAXRSTlMAQObYZgAAAKhJREFUKM/dkDESwiAQRdkbuEpSy3qCsLmAgRwgA/Ra5ADev3FDCIlja+WfgeLxYf9HqX8S4rKdDiAwKnCmApgHImwHKiY5jZZolrUSSJgJV9JwD45J0Ea0OUOgVSu5mAfM9mZ3Ih7Vhv6OHZbp4OgKmKbn9Nry6F7MOgVmLnkAs3FRt9fQ+WHaa0ioLzKm6P14KN9Gb2ue0t59XpJr3tfhWwTM//gzvQFcHxsHssJ5uwAAAABJRU5ErkJggg=="))];
        if (traitId_ == 5) return  ["face6", string(abi.encodePacked(_header, "wAAAD/kYTjg3bHb2SsX1VvPTeESULx00trAAAAAXRSTlMAQObYZgAAAKhJREFUKM/dkDESwiAQRdkbuEpSy3qCsLmAgRwgA/Ra5ADev3FDCIlja+WfgeLxYf9HqX8S4rKdDiAwKnCmApgHImwHKiY5jZZolrUSSJgJV9JwD45J0Ea0OUOgVSu5mAfM9mZ3Ih7Vhv6OHZbp4OgKmKbn9Nry6F7MOgVmLnkAs3FRt9fQ+WHaa0ioLzKm6P14KN9Gb2ue0t59XpJr3tfhWwTM//gzvQFcHxsHssJ5uwAAAABJRU5ErkJggg=="))];
        if (traitId_ == 6) return  ["face7", string(abi.encodePacked(_header, "wAAAD/hLTjdqDHZIusVXdvN02EQlx8bd08AAAAAXRSTlMAQObYZgAAAKhJREFUKM/dkDESwiAQRdkbuEpSy3qCsLmAgRwgA/Ra5ADev3FDCIlja+WfgeLxYf9HqX8S4rKdDiAwKnCmApgHImwHKiY5jZZolrUSSJgJV9JwD45J0Ea0OUOgVSu5mAfM9mZ3Ih7Vhv6OHZbp4OgKmKbn9Nry6F7MOgVmLnkAs3FRt9fQ+WHaa0ioLzKm6P14KN9Gb2ue0t59XpJr3tfhWwTM//gzvQFcHxsHssJ5uwAAAABJRU5ErkJggg=="))];
        if (traitId_ == 7) return  ["face8", string(abi.encodePacked(_header, "wAAAD/hPHjdtbHZLysVaJvN2mEQn0itsgdAAAAAXRSTlMAQObYZgAAAKhJREFUKM/dkDESwiAQRdkbuEpSy3qCsLmAgRwgA/Ra5ADev3FDCIlja+WfgeLxYf9HqX8S4rKdDiAwKnCmApgHImwHKiY5jZZolrUSSJgJV9JwD45J0Ea0OUOgVSu5mAfM9mZ3Ih7Vhv6OHZbp4OgKmKbn9Nry6F7MOgVmLnkAs3FRt9fQ+WHaa0ioLzKm6P14KN9Gb2ue0t59XpJr3tfhWwTM//gzvQFcHxsHssJ5uwAAAABJRU5ErkJggg=="))];
        if (traitId_ == 8) return  ["face9", string(abi.encodePacked(_header, "zOhP8AAAC5duOgZMeKVaxZN29qQoRWXhUiAAAAAXRSTlMAQObYZgAAAKhJREFUKM/dkEEOwiAQRcmcwMEL2BG7p9MLVOgFCuyNSS/g/RdOKaU1bl35E1g8Psz/KPVPIlq2ywEEJgVOVwDzgEjtgMUkp9EizrJWAoky4Upu3INjFLQRoxsIuGolV/2A2Z7tTsSj2tDfqaMyHRyegNL0nF5bHtOL2aTAzCUPUDYu6vYaJj+Mew0J9UXGFL0fD+Xb6G3NU9q7z0tyzfs6fItA+R9/pjdTFxnoDQsrmwAAAABJRU5ErkJggg=="))];
        if (traitId_ == 9) return  ["face10", string(abi.encodePacked(_header, "yRhP8AAACDduNvZMdfVaw9N29JQoTbKO80AAAAAXRSTlMAQObYZgAAAKhJREFUKM/dkEEOwiAQRcmcwMEL2BG7p9MLVOgFCuyNSS/g/RdOKaU1bl35E1g8Psz/KPVPIlq2ywEEJgVOVwDzgEjtgMUkp9EizrJWAoky4Upu3INjFLQRoxsIuGolV/2A2Z7tTsSj2tDfqaMyHRyegNL0nF5bHtOL2aTAzCUPUDYu6vYaJj+Mew0J9UXGFL0fD+Xb6G3NU9q7z0tyzfs6fItA+R9/pjdTFxnoDQsrmwAAAABJRU5ErkJggg=="))];
        if (traitId_ == 10) return ["face11", string(abi.encodePacked(_header, "yEtP8AAAB2oONki8dVd6w3TW9CXITh/G1qAAAAAXRSTlMAQObYZgAAAKhJREFUKM/dkEEOwiAQRcmcwMEL2BG7p9MLVOgFCuyNSS/g/RdOKaU1bl35E1g8Psz/KPVPIlq2ywEEJgVOVwDzgEjtgMUkp9EizrJWAoky4Upu3INjFLQRoxsIuGolV/2A2Z7tTsSj2tDfqaMyHRyegNL0nF5bHtOL2aTAzCUPUDYu6vYaJj+Mew0J9UXGFL0fD+Xb6G3NU9q7z0tyzfs6fItA+R9/pjdTFxnoDQsrmwAAAABJRU5ErkJggg=="))];
        if (traitId_ == 11) return ["face12", string(abi.encodePacked(_header, "wAAACE8f921uNkvMdVoqw3aW9CfYSrI886AAAAAXRSTlMAQObYZgAAAKhJREFUKM/dkDESwiAQRdkbuEpSy3qCsLmAgRwgA/Ra5ADev3FDCIlja+WfgeLxYf9HqX8S4rKdDiAwKnCmApgHImwHKiY5jZZolrUSSJgJV9JwD45J0Ea0OUOgVSu5mAfM9mZ3Ih7Vhv6OHZbp4OgKmKbn9Nry6F7MOgVmLnkAs3FRt9fQ+WHaa0ioLzKm6P14KN9Gb2ue0t59XpJr3tfhWwTM//gzvQFcHxsHssJ5uwAAAABJRU5ErkJggg=="))];
        if (traitId_ == 12) return ["face13", string(abi.encodePacked(_header, "wAAACE/85247lkx6BVrIo3b1lChGomxIssAAAAAXRSTlMAQObYZgAAAKhJREFUKM/dkDESwiAQRdkbuEpSy3qCsLmAgRwgA/Ra5ADev3FDCIlja+WfgeLxYf9HqX8S4rKdDiAwKnCmApgHImwHKiY5jZZolrUSSJgJV9JwD45J0Ea0OUOgVSu5mAfM9mZ3Ih7Vhv6OHZbp4OgKmKbn9Nry6F7MOgVmLnkAs3FRt9fQ+WHaa0ioLzKm6P14KN9Gb2ue0t59XpJr3tfhWwTM//gzvQFcHxsHssJ5uwAAAABJRU5ErkJggg=="))];
        if (traitId_ == 13) return ["face14", string(abi.encodePacked(_header, "wAAACE/5F244Nkx29VrF83bz1ChEk7PceTAAAAAXRSTlMAQObYZgAAAKhJREFUKM/dkDESwiAQRdkbuEpSy3qCsLmAgRwgA/Ra5ADev3FDCIlja+WfgeLxYf9HqX8S4rKdDiAwKnCmApgHImwHKiY5jZZolrUSSJgJV9JwD45J0Ea0OUOgVSu5mAfM9mZ3Ih7Vhv6OHZbp4OgKmKbn9Nry6F7MOgVmLnkAs3FRt9fQ+WHaa0ioLzKm6P14KN9Gb2ue0t59XpJr3tfhWwTM//gzvQFcHxsHssJ5uwAAAABJRU5ErkJggg=="))];
        if (traitId_ == 14) return ["face15", string(abi.encodePacked(_header, "y0/4QAAACg43aLx2R3rFVNbzdchEKu6LPFAAAAAXRSTlMAQObYZgAAAKhJREFUKM/dkEEOwiAQRcmcwMEL2BG7p9MLVOgFCuyNSS/g/RdOKaU1bl35E1g8Psz/KPVPIlq2ywEEJgVOVwDzgEjtgMUkp9EizrJWAoky4Upu3INjFLQRoxsIuGolV/2A2Z7tTsSj2tDfqaMyHRyegNL0nF5bHtOL2aTAzCUPUDYu6vYaJj+Mew0J9UXGFL0fD+Xb6G3NU9q7z0tyzfs6fItA+R9/pjdTFxnoDQsrmwAAAABJRU5ErkJggg=="))];
        if (traitId_ == 15) return ["face16", string(abi.encodePacked(_header, "zx/4QAAADW43a8x2SirFVpbzd9hEJoH8dFAAAAAXRSTlMAQObYZgAAAKhJREFUKM/dkEEOwiAQRcmcwMEL2BG7p9MLVOgFCuyNSS/g/RdOKaU1bl35E1g8Psz/KPVPIlq2ywEEJgVOVwDzgEjtgMUkp9EizrJWAoky4Upu3INjFLQRoxsIuGolV/2A2Z7tTsSj2tDfqaMyHRyegNL0nF5bHtOL2aTAzCUPUDYu6vYaJj+Mew0J9UXGFL0fD+Xb6G3NU9q7z0tyzfs6fItA+R9/pjdTFxnoDQsrmwAAAABJRU5ErkJggg=="))];
        return ["",""];
    }
}