// SPDX-License-Identifier: MIT
pragma solidity ^0.8.9;

import "@openzeppelin/contracts/utils/Strings.sol";

library Footwear {
  using Strings for uint256;
  string constant FOOTWEAR_FOOTWEAR___BEARFOOT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAZQTFRF////AAAAVcLTfgAAAAF0Uk5TAEDm2GYAAAAdSURBVHja7MGBAAAAAMOg+VPf4ARVAQAAAHwTYAAQQAABpAJfkQAAAABJRU5ErkJggg==";

  string constant FOOTWEAR_FOOTWEAR___BLACK_GLADIATOR_SANDALS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAZQTFRFAAAA////pdmf3QAAAAJ0Uk5T/wDltzBKAAAAf0lEQVR42uyTUQrAIAxDn/e/9GCC2jpniwz2EUWQWF5DipTDhQACCCCAAAIIIIAAAgggQBZAf2RX96zXba9xAP3w7uEzB/gMIDsF5yAVInc/TBULD6w0yuigaREAQ9fqx6QRALTqBsC+BAGd5IVtBrjySYhMwYQ+CX/6zpcAAwBGVg+X6K8IkgAAAABJRU5ErkJggg==";

  string constant FOOTWEAR_FOOTWEAR___BLACK_SNEAKERS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAlQTFRFAAAANTU1////eV5mqQAAAAN0Uk5T//8A18oNQQAAAHdJREFUeNrs09EKgCAQRNG7/f9HZyppou5CL0Fj6MPgHKyQ4+VAgAABAgQIECBAgAABAn4LENmxiaFMf+eYYnktQCYM4kDqp4cG1CAKtL5dgG0FZn26ficwExZA17+FOGDP/ixxvoHlwS7x/sJ43NULfOEunAIMAEFDHt/2yl1PAAAAAElFTkSuQmCC";

  string constant FOOTWEAR_FOOTWEAR___BLACK_AND_BLUE_SNEAKERS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRFAAAAQFbNNTU1Ok65////ExF1mwAAAAV0Uk5T/////wD7tg5TAAAAh0lEQVR42uyTSwrAQAhDo/b+Z26dTztQUoRuWogrDfiSEQbby4IAAggggAACCCCAAAIIIMDfAMiiYwXg7qBjNUG3Xdo6oDkiJuBoaARw/8jFHFrDMoD4+1gbCaJrNcB8c1w3CH4H8PsdZQmwVakAzgUzdMFWYCGBjZp+d6V2AzxK3/lMuwADAMKEPN0rbdJFAAAAAElFTkSuQmCC";

  string constant FOOTWEAR_FOOTWEAR___BLACK_AND_WHITE_SNEAKERS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFAAAARUVFzs7O////PUlx0AAAAAR0Uk5T////AEAqqfQAAAB9SURBVHja7NPBCoAwDAPQpP7/P1u76YZIV/AimI15CM07bIjt5YIAAQIECBAgQIAAAQIE/BZAZSKJgXbWk/cUjG8DgiBQB7zvGwPoQRUYfR4AU+Ehg9nUnwTPq4CPXv1TiLQG0GKYGEnUjSjeAWMhS1av0N8uSb7zL+wCDAB7aS5pEKrMVwAAAABJRU5ErkJggg==";

  string constant FOOTWEAR_FOOTWEAR___BLUE_BASKETBALL_SNEAKERS_WITH_BLACK_STRIPE =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRFUGv/AAAAQFbNOk65/////WvZMQAAAAV0Uk5T/////wD7tg5TAAAAiklEQVR42uzTwQ6AIAwD0Hbz/79Zl6lw2YLxokl3EQi8VYzYXhYECBAgQIAAAQIECBAg4GcAETXtiuIjwN1nIKZ8nCC7zuNVIAOATOB41hFQ9+cAWGdA0d/zWL5CDL3IgCbAuIMmApobBCwAG/NF4Dphxpzb5C1domXx3M97YfkzZjULX/qZdgEGAOgYPSkdBXNjAAAAAElFTkSuQmCC";

  string constant FOOTWEAR_FOOTWEAR___BLUE_CROCS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFUGv/QFbNAAAA////e4+K7QAAAAR0Uk5T////AEAqqfQAAACHSURBVHja7NLRDoAgCAVQuP3/P5eAs9LEVo+XhzaYHtCU7WMIAQIECBAgQIAAAQIECBB4CUBKnFaVwDrg+5sQKVYBqKgDtgUOHEWsAYj10fSW5gDqAMen9IRKzXUgyOgAtaPP3BVyQK9n7ivJHcTMbbXNoMMBHv6CBWaV5B1YzCu/PeVdgAEAOP4uMXpWMqcAAAAASUVORK5CYII=";

  string constant FOOTWEAR_FOOTWEAR___BLUE_FLIP_FLOPS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFUGv/AAAAOk65////ucZOEwAAAAR0Uk5T////AEAqqfQAAACGSURBVHja7NLbCsAgDAPQpPv/f571LhQsDPaUgkNCeyZzeD4WBAgQIECAAAECBAgQIEDAzwDjXmYB4hiZc2AO4Ep9ZHIIz4D4/WUBGIBva2dwhgjo0+VpDljdtjQLtLTOD8Fbk4DhmN+EmVw+YhFK2eqm9YjJazQvbt3sUfpH8rpGrV4BBgDn0y7rApH2nwAAAABJRU5ErkJggg==";

  string constant FOOTWEAR_FOOTWEAR___BLUE_HIGH_HEELS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFUGv/AAAAS2Le////23idyAAAAAR0Uk5T////AEAqqfQAAACESURBVHja7NJRDoAgDAPQrt7/zsrGYjS4zPBb/mzoywBxbC4IECBAgAABAgQIECBAgICfgC1iWB8wzJh2Y1gLqPoIoBRQ9ROoBHxewNVjAEyiB8wBRt8CsBR8og4Qi5aACxF1AN/NGN+DkZF5pMYdcLTtsff6JFf99TO+2lW6/yufAgwARaQus8v8p3AAAAAASUVORK5CYII=";

  string constant FOOTWEAR_FOOTWEAR___BLUE_SNEAKERS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRFUGv/AAAAOk65QFbN////MeuL8wAAAAV0Uk5T/////wD7tg5TAAAAgklEQVR42uzTwQ6AIAwD0Hbz/79ZQAQ0iku8mNh5gFT7DhiwvBwIECBAgAABAgQIECBAwO8A9pWnKASwxuBxHwUIWH6HDUD+yHAt4KafHnSgBowB9Na3DFgTnEHAh/4geBxIROvvQk6DgHkhjD0pdTcGD9HKcJY8/MYy8+Q7d2EVYADA/D4NHRs+PQAAAABJRU5ErkJggg==";

  string constant FOOTWEAR_FOOTWEAR___BLUE_TOENAIL_POLISH =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAZQTFRFUGv/////mbDXhwAAAAJ0Uk5T/wDltzBKAAAAOklEQVR42uzRwQkAMAwCQLP/0h2gUCg+c34jB8FMmQAAAAAAAAAAAAAAAPALpO+2L+Q65FFdP+MRYAAP/w/7AEwtVAAAAABJRU5ErkJggg==";

  string constant FOOTWEAR_FOOTWEAR___BLUE_WORK_BOOTS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRFAAAAQFbNOk65RUVF////MzCQEAAAAAV0Uk5T/////wD7tg5TAAAAh0lEQVR42uzTUQ6AIAwD0Lpx/zO7sUlMBJH4p+0PgvaFLBHlZUCAAAECBAgQIECAAAECfwOwWdRir+Gr77ECaABIwEFdAKyvDiAAW2w3EDDsW0QckPo8EnDbPwMDAb0BatYTkHaHziAvJ4jPvYyYgSeNKk5vIBErH0BBO3w0g8zs7DP/wi7AAOl7PabgxTbJAAAAAElFTkSuQmCC";

  string constant FOOTWEAR_FOOTWEAR___BLUE_AND_GRAY_BASKETBALL_SNEAKERS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRFUGv/AAAANTU1RUVF////D76rVwAAAAV0Uk5T/////wD7tg5TAAAAiklEQVR42uzTUQqAMAwD0LTx/md2tRUUtuHwS0n/Npa3oAzby4EAAQIECBAgQIAAAQIEfAwwxFxOxdgS4PQrEEtbbgCwhYy1WACywA0YVsDkftAD8LNCV0AvzyxAT+AQ2hZ7AoYF2PIFODms0AN4xv0IhJAE7eE3YMXrvBVBe/wXciYbv3pMuwADAJnjPcGRET9iAAAAAElFTkSuQmCC";

  string constant FOOTWEAR_FOOTWEAR___PINK_HIGH_HEELS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF6Jr/AAAAyqLV////Ci+i2QAAAAR0Uk5T////AEAqqfQAAACESURBVHja7NJRDoAgDAPQrt7/zsrGYjS4zPBb/mzoywBxbC4IECBAgAABAgQIECBAgICfgC1iWB8wzJh2Y1gLqPoIoBRQ9ROoBHxewNVjAEyiB8wBRt8CsBR8og4Qi5aACxF1AN/NGN+DkZF5pMYdcLTtsff6JFf99TO+2lW6/yufAgwARaQus8v8p3AAAAAASUVORK5CYII=";

  string constant FOOTWEAR_FOOTWEAR___PINK_TOENAIL_POLISH =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAZQTFRF6Jr/////Gn0/cgAAAAJ0Uk5T/wDltzBKAAAAOklEQVR42uzRwQkAMAwCQLP/0h2gUCg+c34jB8FMmQAAAAAAAAAAAAAAAPALpO+2L+Q65FFdP+MRYAAP/w/7AEwtVAAAAABJRU5ErkJggg==";

  string constant FOOTWEAR_FOOTWEAR___PINK_WORK_BOOTS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABJQTFRF6Jr/RUVFAAAAyqLVNTU1////dtmZGgAAAAZ0Uk5T//////8As7+kvwAAAJFJREFUeNrs09sKgCAQBNC99f+/3GxaKGQWvQTNEKWLezAjWV5GCBAgQIAAAQIECBAgQOBvgAmiiGGcT0zdngBagKhA5PQBgH5NIAoQAUAHggz7c9e5bfNtPBLkor8HBoKcHeDR3wFZtjlwrPf2K3izpRmgXoLuHcC1F+3GK2iNLbYtx72p3TnEmlntK//CKsAA7JRMfn/jYOMAAAAASUVORK5CYII=";

  string constant FOOTWEAR_FOOTWEAR___RED_BASKETBALL_SNEAKERS_WITH_WHITE_STRIPE =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABJQTFRF/1BZAAAAzUBIuTpB////////WeF5aAAAAAZ0Uk5T//////8As7+kvwAAAItJREFUeNrs00sOgCAMBNDpx/tfWZuqdFOCcaPJdCMQeB0xYntZIECAAAECBAgQIECAAIGfAYKositKHgFmVoGYyuME2bWOV4EMAPcEjmcfAX1/H4D3GdD0tzyWrxBDazJgEmDcwSQCJjcIaAA65ovAdUJVcq7FW7pEzZJzv9wLy58xa7LwpZ9pF2AAy2hMgyGvO7sAAAAASUVORK5CYII=";

  string constant FOOTWEAR_FOOTWEAR___RED_CROCS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF/1BZzUBIAAAA////KQANqwAAAAR0Uk5T////AEAqqfQAAACHSURBVHja7NLRDoAgCAVQuP3/P5eAs9LEVo+XhzaYHtCU7WMIAQIECBAgQIAAAQIECBB4CUBKnFaVwDrg+5sQKVYBqKgDtgUOHEWsAYj10fSW5gDqAMen9IRKzXUgyOgAtaPP3BVyQK9n7ivJHcTMbbXNoMMBHv6CBWaV5B1YzCu/PeVdgAEAOP4uMXpWMqcAAAAASUVORK5CYII=";

  string constant FOOTWEAR_FOOTWEAR___RED_FLIP_FLOPS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF/1BZAAAAuTpB////yw3NhQAAAAR0Uk5T////AEAqqfQAAACGSURBVHja7NLbCsAgDAPQpPv/f571LhQsDPaUgkNCeyZzeD4WBAgQIECAAAECBAgQIEDAzwDjXmYB4hiZc2AO4Ep9ZHIIz4D4/WUBGIBva2dwhgjo0+VpDljdtjQLtLTOD8Fbk4DhmN+EmVw+YhFK2eqm9YjJazQvbt3sUfpH8rpGrV4BBgDn0y7rApH2nwAAAABJRU5ErkJggg==";

  string constant FOOTWEAR_FOOTWEAR___RED_HIGH_HEELS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAlQTFRF/1BZAAAA////KfmcOwAAAAN0Uk5T//8A18oNQQAAAHdJREFUeNrs0lEKwCAMA9Bk9z+0qC3O0ZWKv/EzmGdR8VwuCBAgQIAAAQIECBAgQICAQ4BBDNYBAqvkGGIBaX8CqYC0b0Am4PcCgAUYUQNsgFGfAF2IRggBW3TgFZ0AvTyCPStdYj9928s5BYvP+Gln6f1XbgIMAMdTHwvim8UAAAAAAElFTkSuQmCC";

  string constant FOOTWEAR_FOOTWEAR___RED_TOENAIL_POLISH =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAZQTFRF/1BZ////zwu78gAAAAJ0Uk5T/wDltzBKAAAAOklEQVR42uzRwQkAMAwCQLP/0h2gUCg+c34jB8FMmQAAAAAAAAAAAAAAAPALpO+2L+Q65FFdP+MRYAAP/w/7AEwtVAAAAABJRU5ErkJggg==";

  string constant FOOTWEAR_FOOTWEAR___RED_WORK_BOOTS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRF////zUBIAAAAuTpB////MVcWZQAAAAV0Uk5T/////wD7tg5TAAAAi0lEQVR42uzTUQ6AIAwD0Lpx/zM7YBIiIBB/TGw/FAl90SUivAwIECBAgAABAgQIECBA4G+AHBZYxNbxHp9lB0ALYAOwPu4ABgKGfYtqBDStRwIe+zUwENAbILzugJZ36AyyASQft1Y9AzeSOAOgOda+AEHZlIVPgEeCpON2rfZWhuiZ7X3lXzgFGAB/uz1t//AxWQAAAABJRU5ErkJggg==";

  string constant FOOTWEAR_FOOTWEAR___RED_AND_GRAY_BASKETBALL_SNEAKERS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABJQTFRF/1BZAAAAysrKurq6////////Vgjz/AAAAAZ0Uk5T//////8As7+kvwAAAJVJREFUeNrs08EKxDAIBFB13P//5cZqSgtJSdjLLow3Jb4MLZHPlyUECBAgQIAAAQIECBAg8GeAStTtVJRuAQa7A9HqdgIRtCVFNRtABngA0wjycr/AArAeYSjIaB8ZAJbAKbQRRoJMA6DtF2DANMIIQF83D8CtE1gEHLXumn0RcF38iJ6ldV6vwfJvzHoZ/NJjOgQYAATZTNMRijgsAAAAAElFTkSuQmCC";

  string constant FOOTWEAR_FOOTWEAR___STEPPED_IN_A_PUMPKIN =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRF3H4xxnErAAAAv7+/////OtLG0AAAAAV0Uk5T/////wD7tg5TAAAAZ0lEQVR42uzTuwrAMAxDUVnu/39zncdYKDiULldDPOmAwdF1GAEAAAAAAAAAAAAAAABU7DMgJbcAR65+PAp670tZqREK94DQfppAtbdxBAzjF6CEWR4LhFt34CJm7O4heeWbv3ALMAASoT6VYD0TNgAAAABJRU5ErkJggg==";

  string constant FOOTWEAR_FOOTWEAR___TAN_COWBOY_BOOTS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFnIFNiW8+AAAA////ushiWgAAAAR0Uk5T////AEAqqfQAAACUSURBVHja7NPBDoAgDAPQdv7/P6swFMMQ0YuH7qDJQp8DIpaPBQECBAgQIECAAAECBAiYAwAMGveAkdcAQNoMAC//eCqbncBDjr2ZgAXg7ATGnGcGmIV4BMR5tgBjAd18s4VYQLR/ojr540YcHAHVeqaTt/2N7l32gS1dADuFBwBL2WJp+fasm+MzKDVs/uR3XgUYABTXLYHfBa9KAAAAAElFTkSuQmCC";

  string constant FOOTWEAR_FOOTWEAR___TAN_WORK_BOOTS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFnIFNiW8+AAAA////ushiWgAAAAR0Uk5T////AEAqqfQAAACFSURBVHja7NNRDoAgDAPQrtz/zg5FgggC8cfE7kNxoS/KIsLLggABAgQIECBAgAABAgT8DSC8zIu+jvf4zBXA7oAtAJ63GrCOgG4e6bWZlh0Bj/kS6AhoHWDOX4DY5hgo9ldTQHMUaA7gyPMEmAXjxCdYKgbu2/1a9GYOMdWo95V/YRNgAGtrLe9GZ97wAAAAAElFTkSuQmCC";

  string constant FOOTWEAR_FOOTWEAR___WATERMELON_SHOES =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRFUf9aAAAA4YGAV9Rd////GtyL9AAAAAV0Uk5T/////wD7tg5TAAAAnElEQVR42uzTUQrEIAwE0Jmk9z/zGqPSLQpZ9rMjRZtgnoFaXH8OCBAgQIAAAQIECBAgQMDLALKe3QH0lWV/xlZnDSDM1ivpMzADK0Cr4BDMnI3LsshuBGwbiM0xIQCfcXglwG2UIAGsuAok0dYOxNqPxw8AkDMz7kgViK+4Sh4Ai/cAswneWtrXH27iAHhvycH6v8Ach/BrfAQYALQTPWXGbH2RAAAAAElFTkSuQmCC";

  string constant FOOTWEAR_FOOTWEAR___WHITE_SNEAKERS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF////AAAAysrK////8hTnlQAAAAR0Uk5T////AEAqqfQAAAB4SURBVHja7NPBDoAwCAPQgv//zzqcyhJkGC8mlnlYqn2HLWJ5OSBAgAABAgQIECBAgACB3wJiz7GtA9JjyLivAgJoe4cdQPtIEQu46W8LF9ADqQGurw3QVIgB13fCE8D1T6EO6NiPkskhqo1kyeQabfLkO//CKsAAfD8uc7Djs80AAAAASUVORK5CYII=";

  string constant FOOTWEAR_FOOTWEAR___WHITE_AND_RED_SNEAKERS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABJQTFRF////AAAAzUBIysrKuTpB////qhKu4wAAAAZ0Uk5T//////8As7+kvwAAAIxJREFUeNrs00sOgDAIBUCgeP8rC5IqG/qJG00ebiixA5JIx8sgAAAAAAAAAAAAAAAAAPgZwOSR3vLgLaC1lgE/8vYE0TXnq0AMQNoBS8oRqO6v9lyAJ+UMVPRvca1PoFHjFeD+Zn12oPUeBoCFOCCpsATcF0Q4CpLBOWAXIpirymSJPYal7/xMpwADAEnqTCfSnHo6AAAAAElFTkSuQmCC";

  string constant FOOTWEAR_FOOTWEAR___YELLOW_RAIN_BOOTS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRF6sU3AAAAz68x/+ue////5D3IEgAAAAV0Uk5T/////wD7tg5TAAAAbUlEQVR42uzT0QqAIAyF4ePs/Z+5JkUJuSFBUPznagzOBypqeRgBAAAAAAAAAAAAAAC8DBRVeUo3fgzQCWgeOEpXYCAoOoDMAduGOhSU9TNBwQFsLzRhCrCuf7NI78A8JVikr+AJF3/6jasAAwA9LD1hKIBN8gAAAABJRU5ErkJggg==";

  function getAsset(uint256 assetNum) external pure returns (string memory) {
    if (assetNum == 0) {
      return FOOTWEAR_FOOTWEAR___BLACK_GLADIATOR_SANDALS;
    } else if (assetNum == 1) {
      return FOOTWEAR_FOOTWEAR___BLACK_SNEAKERS;
    } else if (assetNum == 2) {
      return FOOTWEAR_FOOTWEAR___BLACK_AND_BLUE_SNEAKERS;
    } else if (assetNum == 3) {
      return FOOTWEAR_FOOTWEAR___BLACK_AND_WHITE_SNEAKERS;
    } else if (assetNum == 4) {
      return FOOTWEAR_FOOTWEAR___BLUE_BASKETBALL_SNEAKERS_WITH_BLACK_STRIPE;
    } else if (assetNum == 5) {
      return FOOTWEAR_FOOTWEAR___BLUE_CROCS;
    } else if (assetNum == 6) {
      return FOOTWEAR_FOOTWEAR___BLUE_FLIP_FLOPS;
    } else if (assetNum == 7) {
      return FOOTWEAR_FOOTWEAR___BLUE_HIGH_HEELS;
    } else if (assetNum == 8) {
      return FOOTWEAR_FOOTWEAR___BLUE_SNEAKERS;
    } else if (assetNum == 9) {
      return FOOTWEAR_FOOTWEAR___BLUE_TOENAIL_POLISH;
    } else if (assetNum == 10) {
      return FOOTWEAR_FOOTWEAR___BLUE_WORK_BOOTS;
    } else if (assetNum == 11) {
      return FOOTWEAR_FOOTWEAR___BLUE_AND_GRAY_BASKETBALL_SNEAKERS;
    } else if (assetNum == 12) {
      return FOOTWEAR_FOOTWEAR___PINK_HIGH_HEELS;
    } else if (assetNum == 13) {
      return FOOTWEAR_FOOTWEAR___PINK_TOENAIL_POLISH;
    } else if (assetNum == 14) {
      return FOOTWEAR_FOOTWEAR___PINK_WORK_BOOTS;
    } else if (assetNum == 15) {
      return FOOTWEAR_FOOTWEAR___RED_BASKETBALL_SNEAKERS_WITH_WHITE_STRIPE;
    } else if (assetNum == 16) {
      return FOOTWEAR_FOOTWEAR___RED_CROCS;
    } else if (assetNum == 17) {
      return FOOTWEAR_FOOTWEAR___RED_FLIP_FLOPS;
    } else if (assetNum == 18) {
      return FOOTWEAR_FOOTWEAR___RED_HIGH_HEELS;
    } else if (assetNum == 19) {
      return FOOTWEAR_FOOTWEAR___RED_TOENAIL_POLISH;
    } else if (assetNum == 20) {
      return FOOTWEAR_FOOTWEAR___RED_WORK_BOOTS;
    } else if (assetNum == 21) {
      return FOOTWEAR_FOOTWEAR___RED_AND_GRAY_BASKETBALL_SNEAKERS;
    } else if (assetNum == 22) {
      return FOOTWEAR_FOOTWEAR___STEPPED_IN_A_PUMPKIN;
    } else if (assetNum == 23) {
      return FOOTWEAR_FOOTWEAR___TAN_COWBOY_BOOTS;
    } else if (assetNum == 24) {
      return FOOTWEAR_FOOTWEAR___TAN_WORK_BOOTS;
    } else if (assetNum == 25) {
      return FOOTWEAR_FOOTWEAR___WATERMELON_SHOES;
    } else if (assetNum == 26) {
      return FOOTWEAR_FOOTWEAR___WHITE_SNEAKERS;
    } else if (assetNum == 27) {
      return FOOTWEAR_FOOTWEAR___WHITE_AND_RED_SNEAKERS;
    } else if (assetNum == 28) {
      return FOOTWEAR_FOOTWEAR___YELLOW_RAIN_BOOTS;
    }
    return FOOTWEAR_FOOTWEAR___BEARFOOT;
  }
}

// SPDX-License-Identifier: MIT
// OpenZeppelin Contracts (last updated v4.7.0) (utils/Strings.sol)

pragma solidity ^0.8.0;

/**
 * @dev String operations.
 */
library Strings {
    bytes16 private constant _HEX_SYMBOLS = "0123456789abcdef";
    uint8 private constant _ADDRESS_LENGTH = 20;

    /**
     * @dev Converts a `uint256` to its ASCII `string` decimal representation.
     */
    function toString(uint256 value) internal pure returns (string memory) {
        // Inspired by OraclizeAPI's implementation - MIT licence
        // https://github.com/oraclize/ethereum-api/blob/b42146b063c7d6ee1358846c198246239e9360e8/oraclizeAPI_0.4.25.sol

        if (value == 0) {
            return "0";
        }
        uint256 temp = value;
        uint256 digits;
        while (temp != 0) {
            digits++;
            temp /= 10;
        }
        bytes memory buffer = new bytes(digits);
        while (value != 0) {
            digits -= 1;
            buffer[digits] = bytes1(uint8(48 + uint256(value % 10)));
            value /= 10;
        }
        return string(buffer);
    }

    /**
     * @dev Converts a `uint256` to its ASCII `string` hexadecimal representation.
     */
    function toHexString(uint256 value) internal pure returns (string memory) {
        if (value == 0) {
            return "0x00";
        }
        uint256 temp = value;
        uint256 length = 0;
        while (temp != 0) {
            length++;
            temp >>= 8;
        }
        return toHexString(value, length);
    }

    /**
     * @dev Converts a `uint256` to its ASCII `string` hexadecimal representation with fixed length.
     */
    function toHexString(uint256 value, uint256 length) internal pure returns (string memory) {
        bytes memory buffer = new bytes(2 * length + 2);
        buffer[0] = "0";
        buffer[1] = "x";
        for (uint256 i = 2 * length + 1; i > 1; --i) {
            buffer[i] = _HEX_SYMBOLS[value & 0xf];
            value >>= 4;
        }
        require(value == 0, "Strings: hex length insufficient");
        return string(buffer);
    }

    /**
     * @dev Converts an `address` with fixed length of 20 bytes to its not checksummed ASCII `string` hexadecimal representation.
     */
    function toHexString(address addr) internal pure returns (string memory) {
        return toHexString(uint256(uint160(addr)), _ADDRESS_LENGTH);
    }
}