/**
 *Submitted for verification at Etherscan.io on 2022-03-21
*/

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

contract BabyFaces {
    string private constant _bodyHeader = "AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAZdEVYdFNvZnR3YXJlAEFkb2JlIEltYWdlUmVhZHlxyWU8AAAA";
    string private constant _faceBodySuffix = "VUElb4fMJMSkoexBBjYP6gEzgggMymShz0JylaOqTLTI5O5XolbVddMhqPoPvsm0v6RyO72qOH5X1dK51fZGX8rIkhJOjz50HjwRdP9dj";
    function B_Face(uint32 traitId_) public pure returns (string[2] memory) {
        if (traitId_ == 0 ) return ["bFace1",               string(abi.encodePacked("iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvw", _bodyHeader, "NlBMVEVHcEzIomaIbkWsilbHoGSsilVvWTf/z4QAAADjuXaEakKWeErbsXGcflDAnGLTqmvkuHWefk8WP9h0AAAAAXRSTlMAQObYZgAAALhJREFUOMvt0stSxDAMRFFlpiXd5s3//ywLz4TECbCEBb2xq3zssmVF/OcvBWCdnYO0DRGB3My7I6hUd3cDpe6d4fL+TJByd3dXjpGtWJaX/CT2TLgsBgW6r/UYN+TxFektuJ2/ZkPyC", _faceBodySuffix, "4ApbsJqGjPXPkAAAAASUVORK5CYII="))];
        if (traitId_ == 1 ) return ["bFace2",               string(abi.encodePacked("iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvw", _bodyHeader, "NlBMVEVHcEyXek1mUzSCaEGWeEuCaEBUQynAnGMAAACri1ljUDJxWjilhVWfgFGRdUp3Xzt1Xzysi1hHX8VkAAAAAXRSTlMAQObYZgAAALhJREFUOMvt0stSxDAMRFFlpiXd5s3//ywLz4TECbCEBb2xq3zssmVF/OcvBWCdnYO0DRGB3My7I6hUd3cDpe6d4fL6RpByd3dXjpGtWJaX/CT2TLgsBgW6r/UYN+TxGek9uJ2/ZkPyC", _faceBodySuffix, "4AphsJqJVi1/MAAAAASUVORK5CYII="))];
        if (traitId_ == 2 ) return ["bFace3",               string(abi.encodePacked("iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvw", _bodyHeader, "M1BMVEVHcExkUTNENyNCNSFkUDJWRSs4LRyAaEIAAAByXTtuWTlLPCVPPyhOPyhgTjFyXDtqVTZuQu1GAAAAAXRSTlMAQObYZgAAALZJREFUOMvt0stWxCAQhOHOWEX/5f39n9YFMzHJRF3qwtrAOXxwoOmq//ylAKyzc+AkUFUozXF3FcPq7m5gqHtnuDy/UFjp7u7hObIVy/LqT5IcCZcloEK3tZ7jhjy9I70V1/PXbIgf0ahiOLcDjmQIKdNEAgLsHzQEcRVgm4F52JNiJPKcynZmDsamrlVdczDci+6zb8LJj0RJd2YNz/96WDq/ys7kW1GFJenuyXeNB1803W/nA42aCZ58RLVpAAAAAElFTkSuQmCC"))];
        if (traitId_ == 3 ) return ["bFace4",               string(abi.encodePacked("iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvw", _bodyHeader, "NlBMVEVHcEwiHBEyKRorIxYyKBkrIxUcFg5ANCEAAAA5Lh4hGxEmHhM3LBwwJxk1KxsoIBQnIBQ5Lh0RJEBdAAAAAXRSTlMAQObYZgAAALhJREFUOMvt0stSxDAMRFFNpiXd5s3//ywLz4TECbCEBb2xq3zssmVF/OcvBWCdnYO0DRGB3My7I6hUd3cDpe6d4fL6RpByd3dXjpGtWJbn/CT2TLgsBgW6r/UYN+TxBek9uJ2/ZkPyC", _faceBodySuffix, "4ApbIJqDIoR6sAAAAASUVORK5CYII="))];
        if (traitId_ == 4 ) return ["bFace5",               string(abi.encodePacked("iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvw", _bodyHeader, "SFBMVEVHcEyjTgATCAFpMgBTKQd/QQ29XAD/jiMAAAC5ZhjabQCCPgC+XgA1GQQ+HQUjEAInEgPRZwCORQDJYQC3WgDaaQCVSgCWSAA0BipoAAAAAXRSTlMAQObYZgAAAL9JREFUOMvtkssWwiAMRIsNMMH6fv3/nzpArZSiLnXhLCAcLglD6Lq/fkmgpqgNiKqmPVj1qE9zWIn1UVxtYlQyWN+u6CA8GrWVPKMkhuFsngirVQiJALhYf9zzeS6Q4wnOXZhlBB4qEHOA69N19ZGgRnrHLCEzai0N0TnmhsggmORdRLCHYDdHyITgTA4tIc2qGGPQja86qWKwJLxvtSk26SNiNRlPZLvX7KRtX2XG6FsilaIWlhcfD3jx6b6tO6xUCgtIVFaQAAAAAElFTkSuQmCC"))];
        if (traitId_ == 5 ) return ["bFace6",               string(abi.encodePacked("iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvw", _bodyHeader, "NlBMVEVHcEy9yGaAiEWjrFa8x2SirFVpbzfx/4QAAADW43Z9hEKOlkrP23HI02uWnk+1wGLY5HWUnFC2EORNAAAAAXRSTlMAQObYZgAAALhJREFUOMvt0stSxDAMRFFlpiXd5s3//ywLz4TECbCEBb2xq3zssmVF/OcvBWCdnYO0DRGB3My7I6hUd3cDpe6d4fLyTpByd3dXjpGtWJbX/CT2TLgsBgW6r/UYN+TxGektuJ2/ZkPyC", _faceBodySuffix, "4ApmEJqLHYuWkAAAAASUVORK5CYII="))];
        if (traitId_ == 6 ) return ["bFace7",               string(abi.encodePacked("iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvw", _bodyHeader, "NlBMVEVHcEyMyGZfiEV4rFaLx2R3rFVNbze0/4QAAACg43ZchEJolkqb23GU02tvnk+GwGKh5HVunFAzblLRAAAAAXRSTlMAQObYZgAAALhJREFUOMvt0stSxDAMRFFlpiXd5s3//ywLz4TECbCEBb2xq3zssmVF/OcvBWCdnYO0DRGB3My7I6hUd3cDpe6d4fLyTpByd3dXjpGtWJbX/CT2TLgsBgW6r/UYN+TxGektuJ2/ZkPyC", _faceBodySuffix, "4ApmEJqLHYuWkAAAAASUVORK5CYII="))];
        if (traitId_ == 7 ) return ["bFace8",               string(abi.encodePacked("iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvw", _bodyHeader, "NlBMVEVHcExmyHFFiE1WrF9kx29VrF83bz0AAACE/5F244NChElx23xKllJPnldQnFhr03ZiwG115IERRA2LAAAAAXRSTlMAQObYZgAAALhJREFUOMvt0stSxDAMRFFlpqWr5s3//ywLz4TECbCEBb2xq3zssmVF/OcvBWCdnYO0DRGB3My7I6hUd3cDpe6d4fL8QpByd3dXjpGtWJa3/CT2TLgsBgW6r/UYN+TpFek9uJ2/ZkPyE", _faceBodySuffix, "4AzX8JwQ4FX4QAAAAASUVORK5CYII="))];
        if (traitId_ == 8 ) return ["bFace9",               string(abi.encodePacked("iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvw", _bodyHeader, "NlBMVEVHcExFiG5myKJWrIpkx6BVrIo3b1kAAACE/85247lChGpKlnhx27FPnn5iwJxQnH515Lhr06q4evxpAAAAAXRSTlMAQObYZgAAALhJREFUOMvt0stSxDAMRFFNpqWr5s3//ywLz4TECbCEBb2xq3zssmVF/OcvBWCdnYO0DRGB3My7I6hUd3cDpe6d4fL8SpByd3dXjpGtWJaX/CT2TLgsBgW6r/UYN+TxHektuJ2/ZkPyC", _faceBodySuffix, "4AzRkJwY7MBvkAAAAASUVORK5CYII="))];
        if (traitId_ == 9 ) return ["bFace10",              string(abi.encodePacked("iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvw", _bodyHeader, "NlBMVEVHcExmvchFgIhWo6xkvMdVoqw3aW8AAACE8f921uNCfYRxz9tKjpZ12ORPlp5ryNNQlJxitcAuEl2VAAAAAXRSTlMAQObYZgAAALhJREFUOMvt0stSxDAMRFFlpqWr5s3//ywLz4TECbCEBb2xq3zssmVF/OcvBWCdnYO0DRGB3My7I6hUd3cDpe6d4fLyRpByd3dXjpGtWJb3/CT2TLgsBgW6r/UYN+TpFek5uJ2/ZkPyE", _faceBodySuffix, "4AzwUJwdx83WAAAAAASUVORK5CYII="))];
        if (traitId_ == 10) return ["bFace11",              string(abi.encodePacked("iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvw", _bodyHeader, "NlBMVEVHcExFX4hmjMhWeKxki8dVd6w3TW+EtP8AAAB2oONCXIRKaJZxm9t1oeRQbpxPb55rlNNihsALYLZCAAAAAXRSTlMAQObYZgAAALhJREFUOMvt0stSxDAMRFFNpiXd5s3//ywLz4TECbCEBb2xq3zssmVF/OcvBWCdnYO0DRGB3My7I6hUd3cDpe6d4fL6QpByd3dXjpGtWJb3/CT2TLgsBgW6r/UYN+TxDek5uJ2/ZkPyC", _faceBodySuffix, "4ApgIJqJvueg4AAAAASUVORK5CYII="))];
        if (traitId_ == 11) return ["bFace12",              string(abi.encodePacked("iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvw", _bodyHeader, "NlBMVEVHcEzIcWaITUWsX1bHb2SsX1VvPTcAAAD/kYTjg3aESUKWUkrbfHHTdmueV0+cWFDkgXXAbWLcKX23AAAAAXRSTlMAQObYZgAAALhJREFUOMvt0stSxDAMRFFlpqWr5s3//ywLz4TECbCEBb2xq3zssmVF/OcvBWCdnYO0DRGB3My7I6hUd3cDpe6d4fLySpByd3dXjpGtWJb3/CT2TLgsBgW6r/UYN+TxGektuJ2/ZkPyC", _faceBodySuffix, "4Azm8JwdmcwoQAAAAASUVORK5CYII="))];
        if (traitId_ == 12) return ["bFace13",              string(abi.encodePacked("iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvw", _bodyHeader, "NlBMVEVHcEzIZoyIRV+sVnjHZIusVXdvN00AAAD/hLTjdqCEQlyWSmjbcZucUG6eT2/AYobkdaHTa5QEvTEmAAAAAXRSTlMAQObYZgAAALhJREFUOMvt0stSxDAMRFFlpqWr5s3//ywLz4TECbCEBb2xq3zssmVF/OcvBWCdnYO0DRGB3My7I6hUd3cDpe6d4fLyTJByd3dXjpGtWJbX/CT2TLgsBgW6r/UYN+TxHektuJ2/ZkPyC", _faceBodySuffix, "4AzR0JwVOyAJEAAAAASUVORK5CYII="))];
        if (traitId_ == 13) return ["bFace14",              string(abi.encodePacked("iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvw", _bodyHeader, "NlBMVEVHcEzIZr2IRYCsVqPHZLysVaJvN2kAAAD/hPHjdtaEQn2WSo7bcc/AYrXTa8ieT5bkddicUJSMEseYAAAAAXRSTlMAQObYZgAAALhJREFUOMvt0stSxDAMRFFlpqWr5s3//ywLz4TECbCEBb2xq3zssmVF/OcvBWCdnYO0DRGB3My7I6hUd3cDpe6d4fL6TpByd3dXjpGtWJbn/CT2TLgsBgW6r/UYN+TxBektuJ2/ZkPyC", _faceBodySuffix, "4AzpYJwZL8U/4AAAAASUVORK5CYII="))];
        if (traitId_ == 14) return ["bFace15",              string(abi.encodePacked("iVBORw0KGgoAAAANSUhEUgAAACIAAAAiBAMAAADIaRbx", _bodyHeader, "LVBMVEVHcEzOhP8AAAC5duOgZMeKVaxZN2+KVqx7TJlqQoSxcdt4Spaqa9NuRIq4deSiyrYrAAAAAXRSTlMAQObYZgAAALdJREFUKM/d0T0OwjAMBWDLN3jtBSoTsqfuBdp0RlV/FiZUyMjMCXoBzsPhGJrQSqxMeMsnJ89WiP6pRIhIih0MKsQ+S8eCQw2IrbE28X3m0QHBIYpdFh4doEk4lIa9AtAkL3PiAWutcjYXDi53m9yMJztUjZQS021z6Fimfu6fUfhadURmGlQ1Dm0fBbEHAJSxSYiMAwBk22JH/RLvcnXYLW/HGkC+Ew5+ezhea9tPeAoUkV/+yhu+Qh5eH29/gwAAAABJRU5ErkJggg=="))];
        if (traitId_ == 15) return ["bFace16",              string(abi.encodePacked("iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvw", _bodyHeader, "NlBMVEVHcExNRYhxZshfVqxvZMdfVaw9N2+RhP8AAACDduNJQoR8cdtSSpZtYsB2a9NYUJxXT56BdeTwJsbkAAAAAXRSTlMAQObYZgAAALhJREFUOMvt0stSxDAMRFFNpiXd5s3//ywLz4TECbCEBb2xq3zssmVF/OcvBWCdnYO0DRGB3My7I6hUd3cDpe6d4fL2SpByd3dXjpGtWJbn/CT2TLgsBgW6r/UYN+TpBek9uJ2/ZkPyE", _faceBodySuffix, "4ApdcJqItcW7QAAAAASUVORK5CYII="))];
        return ["",""];
    }
}