/**
 *Submitted for verification at Etherscan.io on 2022-03-21
*/

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

contract BabyHats {
    string private constant _bodyHeader = "AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAZdEVYdFNvZnR3YXJlAEFkb2JlIEltYWdlUmVhZHlxyWU8AAAA";
    function B_Hats(uint32 traitId_) public pure returns (string[2] memory) {
        if (traitId_ == 0 ) return ["Gold Laurel Wreath",   string(abi.encodePacked("iVBORw0KGgoAAAANSUhEUgAAACIAAAAiAgMAAABHKeNR", _bodyHeader, "DFBMVEVHcEzx2QTQvA6tnRKmBofsAAAAAXRSTlMAQObYZgAAAEBJREFUGNNjYKAWYGFlYAwA0qyskioMTA5Alo6k6hIGhgNAlsXKuFSIqmehzg0Q1j/nCw4QFv+EDzBDnjAMAwAAzgkLGImTK3sAAAAASUVORK5CYII="))];
        if (traitId_ == 1 ) return ["Kongson Helmet",       string(abi.encodePacked("iVBORw0KGgoAAAANSUhEUgAAACIAAAAiBAMAAADIaRbx", _bodyHeader, "ElBMVEVHcEy5ubl7e3vd3bbHx57///+zOcN9AAAAAXRSTlMAQObYZgAAAHZJREFUGBntwbENwkAMhtFfJgt8lujPFgMkOgaIlFuA/ZfBF4kiHQ0d7+l7lkUfh5RBECndVpWjGzg4OfqqMvoGAQSP566y9L45xfGhaRl9izuvO+G7TmMQTE7TKSBLeGZqMnAVa5JpMmi6yIymi5Q1XTT9/dwbmu8M8Ohlj/YAAAAASUVORK5CYII="))];
        if (traitId_ == 2 ) return ["Cyberbrain",           string(abi.encodePacked("iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvw", _bodyHeader, "SFBMVEVHcExPT0//mQA8mL6urq64x8dMq9EgdJM4ja49p9LxCAh6enqYmJjfERFwg4Ii/wC3JSX/XgD/AACLpKMn8Qgs3xFgYGA5tyV2/HFVAAAAAXRSTlMAQObYZgAAAGVJREFUGBntwTkSwkAQA0DZ1qwk7pv//5QiZAtnkG03/ueBVfN5xtuECSsmmFVNVvDV/uSIKTlVbM87ehvEMklbJTq4obOTskjlqJFswhWfvHW0KHTkVkp0QM/G8QLAQIhhGH7pBefwAu87wWIuAAAAAElFTkSuQmCC"))];
        if (traitId_ == 3 ) return ["Unripe Banana Hat",    string(abi.encodePacked("iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvw", _bodyHeader, "llBMVEVHcEz78gD58gDI4QDA4wDw8wDf6wAAAADSyRz+8gC55ADNyhy05gDm7gDRyRy8xBz98wCgvxyqvRzd6gDQyhzJyhzAxhzV5gDC4gDO4wC5wxytvRyWwRy94wCO7gCm6QDZ6ADFyBzF4QCRwxyovRyo6ACu5wCw5gC65ADI4AD/8gDQyRz38wD18wD98gD68gDk7QDMyRw3DMAAAAAAAXRSTlMAQObYZgAAAI5JREFUGBntwdUSglAARdGDxL6o2N3d+f8/p+MYIKjvDmspDv3CAH3F1ZArfQDT+SKfdVqTNSgB9Jb5lTPrNkfeKQhQDOVs3wE6jbG7h/MOvaFi220kQe5oWWChKLyqV0Q3bP0DGB9FUHdddIfvIwwKI5fJoAfMBglFUCuhJwyKoYBeMCgGg0JQApRK/ZsL2IoHBLIU098AAAAASUVORK5CYII="))];
        if (traitId_ == 4 ) return ["Pinkish Headband",     string(abi.encodePacked("iVBORw0KGgoAAAANSUhEUgAAACIAAAAiAgMAAABHKeNR", _bodyHeader, "CVBMVEVHcEzolv////9sgWIvAAAAAXRSTlMAQObYZgAAAB9JREFUGNNjYKASYAwNDXUAs7RWrVq1ACYUGsIw4gAAp28FsoyVMLgAAAAASUVORK5CYII="))];
        if (traitId_ == 5 ) return ["BK Cap",               string(abi.encodePacked("iVBORw0KGgoAAAANSUhEUgAAACIAAAAiBAMAAADIaRbx", _bodyHeader, "FVBMVEVHcEwAAAD/RT/fPTeoIR3LOjWEGRbht0dVAAAAAXRSTlMAQObYZgAAAGJJREFUKM9jYMADBAUFBVAEGJWUlBRRFAgJKgkpIvGNk4VAAKaN0dnYzFBJEAhhIiLGRkmKhkoINYzOwWZKwmARqEEirqFJSqKGIJMhIowuLmGhxiLBxkAAFRFEAgyjYFADAB7ZDMbn7cQ/AAAAAElFTkSuQmCC"))];
        if (traitId_ == 6 ) return ["White Top Hat",        string(abi.encodePacked("iVBORw0KGgoAAAANSUhEUgAAACIAAAAiBAMAAADIaRbx", _bodyHeader, "HlBMVEVHcEz////18/Pg39/6+vrx7+/4+Pj6+Pj7+/v8/Pwi6aTKAAAAAXRSTlMAQObYZgAAAEpJREFUKM9jYMAGTBMFoUAAKmIEEREWNISLOIJFDIUFUUWAStBEgEpQRUBKUEVASuDWgUTASpSAQIGBQVW9U0gJAqB6IOKjYGgAAN8rDJ/Yg5n8AAAAAElFTkSuQmCC"))];
        if (traitId_ == 7 ) return ["Coconut Helmet",       string(abi.encodePacked("iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvw", _bodyHeader, "nFBMVEVHcExSKwlJJQdiNg8+HQERCABIJAQrFABpOxJULQnHwLs5GgCYVSBBHwEgDwBGIwQ+HgO8trIuFQCvrKl7RhWDShkhDwAwFwBkNQo8HQAyGADEvbmNTxyBSBk3GQCKTxsPBwEVCgEbDgFNJwZxPxBfNA1oNw5qORBwPhLGv7q5tbGxrapAHgByPxMMBgEZDAEXCwEWCwEJBQGVVB6YUi9cAAAAAXRSTlMAQObYZgAAAMRJREFUOMvtkEUOAzEMRQNObHeYysyM979b066mNFK3VZ+8sOSnbydCfAfeq3IuMEVAV+EH143oBtPOh/cGcVwcR1wc9gPq+QgvBljF6uKdyfeG5Npe9zkoZc/qmKg4jZgHirRiP304COzCMsfEtwzSuaaYg3IOitDOrY1kX0ZSa7ntk4qi9rIcgtzyZoAMJkeU7mkScgylKe8JpkEbTZZtsnWSJJ3aqlNzlBQMWpMmNqo+1jRCwKapVMZ1UzdG/PnzW1wBDkoK3JBBckIAAAAASUVORK5CYII="))];
        if (traitId_ == 8 ) return ["Rose Gold Headphones", string(abi.encodePacked("iVBORw0KGgoAAAANSUhEUgAAACIAAAAiBAMAAADIaRbx", _bodyHeader, "ElBMVEVHcEwAAAC/qoyuk22Xe1Ti2cx6uRmrAAAAAXRSTlMAQObYZgAAAF9JREFUKM9jYCAaMAoKCgqgCAgpKSkpIosABQRQNQkJCqKZoohhLoaIkABBEWoZoxSIJiKsFIqqiNFZUBRVEaOjUSCGiCJhEWNFRXSThdAcLWJsjB5eLo7ojkYP0sEOAJ/zCbaMNbYVAAAAAElFTkSuQmCC"))];
        if (traitId_ == 9 ) return ["Apprentice Hard Hat",  string(abi.encodePacked("iVBORw0KGgoAAAANSUhEUgAAACIAAAAiBAMAAADIaRbx", _bodyHeader, "FVBMVEVHcEwAAAAEXdoAav8DY+zN3vUpffcwPL9lAAAAAXRSTlMAQObYZgAAAFlJREFUKM9jYMAFGAUFBVAEBIWNnAMFkQVUjI2MzVIRqhhdnI1VjI3NAuEiQk5gEWNjuCIhIBcsAlPEqAQHUAuFlFRcgMAZpMoQVQlQwhHqOAQQYBgFgxkAADdgDzWF2wyNAAAAAElFTkSuQmCC"))];
        if (traitId_ == 10) return ["Organic Straw Hat",    string(abi.encodePacked("iVBORw0KGgoAAAANSUhEUgAAACIAAAAiBAMAAADIaRbx", _bodyHeader, "HlBMVEVHcEwAAADUwigAmP/AryKvoSUEaa4HftCklykEWZQ1RyD+AAAAAXRSTlMAQObYZgAAAFBJREFUKM9jYMAFBAUFUfiMgkpKSoICSAIiTkARJUWEkGiIEhgowpW0ujhBhAQQpsIAVEQyLb3cGAwMYRYhgADUmFAXFxeEQcgqEKpGwSAFALvUDPUwnpqIAAAAAElFTkSuQmCC"))];
        if (traitId_ == 11) return ["Paper Boat",           string(abi.encodePacked("iVBORw0KGgoAAAANSUhEUgAAACIAAAAiBAMAAADIaRbx", _bodyHeader, "IVBMVEVHcEypvMP////n7O7W3+LJ1dng5un19/jd5efQ297v8vRGTwc/AAAAAXRSTlMAQObYZgAAAHFJREFUKM9jYMAJBAXRBRyVBGBsRkEQcC5UUgQzgCLCjcLGqSJGikpKQEIIpFLYJFDM0VkJKKLoKFwEEmE0TgkUNAKJCAovV1IEGSRsnBIqKGioKOhmpAQxntHYOMUzVFDUzVgJogTkFDgQYBgFQwwAAFJ0D/mM7t2kAAAAAElFTkSuQmCC"))];
        if (traitId_ == 12) return ["Toy Head Mirror",      string(abi.encodePacked("iVBORw0KGgoAAAANSUhEUgAAACIAAAAiBAMAAADIaRbx", _bodyHeader, "FVBMVEVHcEwAAADd9/TR8u09n7++3tr///9z+ZwxAAAAAXRSTlMAQObYZgAAAE5JREFUKM9jYCAJCAqiCTAqqQmgiggpqSWiKglWUkoTQBVRFFKCiTAKgkCwohJcRMQFCBxDjY2VBOHWgoBosLKiIKpBxsYChFw4CgYaAABTtwg7ucdTMAAAAABJRU5ErkJggg=="))];
        if (traitId_ == 13) return ["Propeller Hat",        string(abi.encodePacked("iVBORw0KGgoAAAANSUhEUgAAACIAAAAiBAMAAADIaRbx", _bodyHeader, "LVBMVEVHcEwAAAD/4ABB/wABmP3/LwABkfH22ADSJwA75gDozAA97gA/9gABieO0IQB+v6kJAAAAAXRSTlMAQObYZgAAAF5JREFUKM9jYMAOGAXBAE0QmxoBJAHRYGMjJRVHhJBE6GSgiJJLIlxJa6SxsVGRkoubAFzJbGNj8yIlFZgixhcgEatyoLZcAahI5+w9Z6xWFSmlwUQEEUCAYRQMagAAs48U2l8cSMAAAAAASUVORK5CYII="))];
        if (traitId_ == 14) return ["Green Beanie",         string(abi.encodePacked("iVBORw0KGgoAAAANSUhEUgAAACIAAAAiAgMAAABHKeNR", _bodyHeader, "DFBMVEVHcEwTjw0AAAAQqwgqORpWAAAAAXRSTlMAQObYZgAAAEJJREFUGNNjYCAAmFatWgFhad4tv9cAZm0vv/v9AVjyfvn92hsgFnft9/u130As1VAQACnUvQsCIJbWKhBoYBgZAAB4lhthdWriogAAAABJRU5ErkJggg=="))];
        if (traitId_ == 15) return ["Blue Bandana",         string(abi.encodePacked("iVBORw0KGgoAAAANSUhEUgAAACIAAAAiAgMAAABHKeNR", _bodyHeader, "CVBMVEVHcEwWbbUSYKFTZGqGAAAAAXRSTlMAQObYZgAAAD9JREFUGNNjYCAEtFatgDCYpoaGNYBZnKGhoQlgliqQFQGk2ZiWQlmcs1atmhq1CiQpAdS8AKwzAWYYF8MIAADVng0FSLV2IQAAAABJRU5ErkJggg=="))];
        if (traitId_ == 16) return ["Grey Beanie",          string(abi.encodePacked("iVBORw0KGgoAAAANSUhEUgAAACIAAAAiAgMAAABHKeNR", _bodyHeader, "DFBMVEVHcExqamp6enoAAACxT+7nAAAAAXRSTlMAQObYZgAAAEJJREFUGNNjYCAAmP///wNh2c5Mm30AzHqWNnPZBrDkrLRZmXNALL7MZbMyl4NYpqEgAFJoORMEQCz7/yBwgGFkAAC3uhrH08ZcGwAAAABJRU5ErkJggg=="))];
        if (traitId_ == 17) return ["Green Bandana",        string(abi.encodePacked("iVBORw0KGgoAAAANSUhEUgAAACIAAAAiAgMAAABHKeNR", _bodyHeader, "CVBMVEVHcExatRZPoRIpSJs4AAAAAXRSTlMAQObYZgAAAD9JREFUGNNjYCAEtFatgDCYpoaGNYBZnKGhoQlgliqQFQGk2ZiWQlmcs1atmhq1CiQpAdS8AKwzAWYYF8MIAADVng0FSLV2IQAAAABJRU5ErkJggg=="))];
        if (traitId_ == 18) return ["Afro",                 string(abi.encodePacked("iVBORw0KGgoAAAANSUhEUgAAACIAAAAiAQMAAAAAiZmB", _bodyHeader, "BlBMVEVHcEwAAACfKoRRAAAAAXRSTlMAQObYZgAAAE1JREFUCNdjYJD/38DAwGD//wEDA+P//z8YGNjBJP///39gpDwSaQ8h//HUAMkfDDYMDPUfGDjAJBDUPwCRNQkgskIBRBZASAbsJFUBALYpJG+1oD1zAAAAAElFTkSuQmCC"))];
        if (traitId_ == 19) return ["Yellow Bandana",       string(abi.encodePacked("iVBORw0KGgoAAAANSUhEUgAAACIAAAAiAgMAAABHKeNR", _bodyHeader, "CVBMVEVHcEy1khahghKgbkuwAAAAAXRSTlMAQObYZgAAAD9JREFUGNNjYCAEtFatgDCYpoaGNYBZnKGhoQlgliqQFQGk2ZiWQlmcs1atmhq1CiQpAdS8AKwzAWYYF8MIAADVng0FSLV2IQAAAABJRU5ErkJggg=="))];
        if (traitId_ == 20) return ["Flat Top",             string(abi.encodePacked("iVBORw0KGgoAAAANSUhEUgAAACIAAAAiAQMAAAAAiZmB", _bodyHeader, "BlBMVEVHcEwAAACfKoRRAAAAAXRSTlMAQObYZgAAAD5JREFUCNdjYEAG/P8fAEl5MGkPJuv/fwCS/0EkI4T8I7+DgYH5ATMHkDwA0sQOIR+ADQCTPAkgkkOBgb4AAEhUFQzMlj6NAAAAAElFTkSuQmCC"))];
        if (traitId_ == 21) return ["Purple Bandana",       string(abi.encodePacked("iVBORw0KGgoAAAANSUhEUgAAACIAAAAiAgMAAABHKeNR", _bodyHeader, "CVBMVEVHcEx1FrVnEqEcNXdjAAAAAXRSTlMAQObYZgAAAD9JREFUGNNjYCAEtFatgDCYpoaGNYBZnKGhoQlgliqQFQGk2ZiWQlmcs1atmhq1CiQpAdS8AKwzAWYYF8MIAADVng0FSLV2IQAAAABJRU5ErkJggg=="))];
        if (traitId_ == 22) return ["Orange Beanie",        string(abi.encodePacked("iVBORw0KGgoAAAANSUhEUgAAACIAAAAiAgMAAABHKeNR", _bodyHeader, "DFBMVEVHcEzVhRQAAAD/mgzh7PF3AAAAAXRSTlMAQObYZgAAAEJJREFUGNNjYCAAmFatWgFhad4tv9cAZm0vv/v9AVjyfvn92hsgFnft9/u130As1VAQACnUvQsCIJbWKhBoYBgZAAB4lhthdWriogAAAABJRU5ErkJggg=="))];
        if (traitId_ == 23) return ["Blue Beanie",          string(abi.encodePacked("iVBORw0KGgoAAAANSUhEUgAAACIAAAAiAgMAAABHKeNR", _bodyHeader, "DFBMVEVHcEwHT7UAAAAAWtlSfN4VAAAAAXRSTlMAQObYZgAAAEJJREFUGNNjYCAAmFatWgFhad4tv9cAZm0vv/v9AVjyfvn92hsgFnft9/u130As1VAQACnUvQsCIJbWKhBoYBgZAAB4lhthdWriogAAAABJRU5ErkJggg=="))];
        if (traitId_ == 24) return ["Mohawk",               string(abi.encodePacked("iVBORw0KGgoAAAANSUhEUgAAACIAAAAiAQMAAAAAiZmB", _bodyHeader, "BlBMVEVHcEwAAACfKoRRAAAAAXRSTlMAQObYZgAAABxJREFUCNdjYEABbGBSDkz+AxHM/5FEeBgGNQAAkXwCT9+brOkAAAAASUVORK5CYII="))];
        if (traitId_ == 25) return ["Hidden",               string(abi.encodePacked("iVBORw0KGgoAAAANSUhEUgAAACIAAAAiAQMAAAAAiZmB", _bodyHeader, "BlBMVEVHcEwAAACfKoRRAAAAAXRSTlMAQObYZgAAAA5JREFUCB1jGB6ggQEIAANMAIH9XxfzAAAAAElFTkSuQmCC"))];
        if (traitId_ == 26) return ["Ranger Hat",           ""];
        return ["",""];
    }
}