// SPDX-License-Identifier: MIT
pragma solidity ^0.8.9;

import "@openzeppelin/contracts/utils/Strings.sol";

library Hat {
  using Strings for uint256;

  string constant HAT_HAT___ASTRONAUT_HELMET =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFQlnRuL/sAAAA////YkVV0AAAAAR0Uk5T////AEAqqfQAAACWSURBVHja7NXbCoAgEATQdfr/fy68kdlua6EQzDxFOAdBXGX7GJkKIOclAEiORchz3SY0oKlHYgzo+qog3r4miNlPh2AKFgCEmEK4gbI+1BiCDpz6RRgCmn4WlgKXfhIILDyFuy1g/C7AtQHrOsPTNwcKHH19pKGOg/y5dqQd/7sMvwuu+uynjQABAgQIECBA4J/ALsAACykq+68x4AkAAAAASUVORK5CYII=";

  string constant HAT_HAT___BAG_OF_ETHEREUM =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFspJTBQMCiHt7////7YKQUgAAAAR0Uk5T////AEAqqfQAAABdSURBVHja7NBJCsAwDENRD/e/c5qUbqNSLQLla2v0sB0tkrmfh+pHpANcfSEoYMbYQC+wB1bfOGH2SwkCqKqTQD9AfwfuHzhAWMCbAAAAAAAAAAAAAAAA/BgYAgwAKmAvLXECd/QAAAAASUVORK5CYII=";

  string constant HAT_HAT___BLACK_BOWLER_HAT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAZQTFRFAAAA////pdmf3QAAAAJ0Uk5T/wDltzBKAAAAPElEQVR42uzSsQkAIBAEwfv+mxaMPhOUD4TZAiba1GMBTAPZ3QPJWZgE0vIBAAAAAAAAAAAAAPwJLAEGADaZD98VtpqsAAAAAElFTkSuQmCC";

  string constant HAT_HAT___BLACK_TOP_HAT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAZQTFRFAAAA////pdmf3QAAAAJ0Uk5T/wDltzBKAAAAOElEQVR42uzSsQkAMAwEsff+S6dJkd4EY9ANoOpSzfIVyA2wGMjT1EgAAAAAAAAAAAAAAOh1BBgAMcgPvRKkebAAAAAASUVORK5CYII=";

  string constant HAT_HAT___BLACK_AND_WHITE_STRIPED_JAIL_CAP =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFAAAA////zs7O////IzDhUgAAAAR0Uk5T////AEAqqfQAAABkSURBVHja7NJBDoAwCETRgd7/ziqa6MY2GRYu/JN0RfqgDRrNaF6t2IAUlSmhVfvVEO8l5X0/5QCRcSVNYO9csSc4PvE83wDjCbiLVO/Pxia2VxkAAAAAAAAAAAAAAODfwCbAABLfLurW3p3aAAAAAElFTkSuQmCC";

  string constant HAT_HAT___BLACK_WITH_BLUE_HEADPHONES =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAlQTFRFAAAAUGv/////v7SHiAAAAAN0Uk5T//8A18oNQQAAAFVJREFUeNrs0zEKwCAQBdHR+x86nSCYZY2NxvmlMK9YkLo4tgZo+wTQbR7ookAg00cCqT4QyPXvwvCVMgIKNwHLR/zPbxQQEBAQEBAQEBAQOBp4BBgAApMfXVc0ju8AAAAASUVORK5CYII=";

  string constant HAT_HAT___BLACK_WITH_BLUE_TOP_HAT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFAAAAUGv/S2Le////GFS2BwAAAAR0Uk5T////AEAqqfQAAAA9SURBVHja7NKhEQAgEASx5+i/ZxAI/A+DyRYQtTWb1VOgToAGkGTs8guoq18jAQAAAAAAAAAAAACg1xJgAMovL02Jgj8HAAAAAElFTkSuQmCC";

  string constant HAT_HAT___BLUE_BASEBALL_CAP =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFSGz/AAAAOlfV////hul92gAAAAR0Uk5T////AEAqqfQAAABWSURBVHja7NNBDgAQDETRDve/sxhrKrWTXyI289I0RH+s+B2Qqw4o2lyqAjPvrRrgfCpElvd5EHJgtbAd5iXgix7eQaUD/gIAAAAAAAAAAAAAAMAQYABuYy8sFMG46QAAAABJRU5ErkJggg==";

  string constant HAT_HAT___BLUE_UMBRELLA_HAT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFUGv/S2LeAAAA////rmvP5AAAAAR0Uk5T////AEAqqfQAAACGSURBVHja7NPRCsAgCAXQq/3/P09TNgYzZL1scH3IIu6BojA2C98GNOsdYEERgQBYGSjjgHjYERtKAou4572FUxCPgJ65mKSkXUCvVAJpaQ+45ROoBTzmdVhkbtvCuwHzYNoB4rpyAxJd4mq1dYTFy/rdXyBAgAABAgQIECBAgACBnToEGABRVi6KAJCJVwAAAABJRU5ErkJggg==";

  string constant HAT_HAT___BULB_HELMET =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFDQ8PzsiicGx0////c8RZeAAAAAR0Uk5T////AEAqqfQAAAB/SURBVHja7NRtC4AgDATgW/3//5xzagQzbRJB3H0ZWPdgL4h9MRhcTlkBICmIA7k/EH4OoCUISEsIkEueAyJzAvyHV2BL0apNW50D9OUj97RZJjqfA73/1wM84Y0dlEUrnvPuXj+1V2foPFg+UAgQIECAAAECBAgQIPAZcAgwAGn3Lmu0Kz19AAAAAElFTkSuQmCC";

  string constant HAT_HAT___CHERRY_ON_TOP =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFhCQjAAAAbpZw////wz4dmwAAAAR0Uk5T////AEAqqfQAAABOSURBVHja7NKxEcBACANBHe6/Z48bMD+j4JNTDAuB8pTJOgEdwAwNwHQf8H9+BciEAiBfuA5UPVj3D4okICAgICAgICAgICAgcA94BRgAnP4voNQRG7kAAAAASUVORK5CYII=";

  string constant HAT_HAT___CRYPTO_INFLUENCER_BLUEBIRD =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF6sU3AAAAWKne////lkVaqQAAAAR0Uk5T////AEAqqfQAAABWSURBVHja7NIxDsAwCENRm97/ziFR51AFRV2+dz8hQE8zugrYPcAR7gDWF0GbviKBlcMJcoA3Pt5B2S+uUPerP5j9Px8JAAAAAAAAAAAAAAAAoJchwABEky+stP9cpgAAAABJRU5ErkJggg==";

  string constant HAT_HAT___GIANT_SUNFLOWER =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF5cE3AAAAa1cx////r/58CwAAAAR0Uk5T////AEAqqfQAAAD1SURBVHja7JVLAoMgDEQn5P53ro2iiAwkbRddJKuIzBPzAzo12Wy+A3M9NpMw4Pys6SuBHAazz7YAdhiM9fvesesEvPdK74UAkJHnjoHtfjrOLICYeOtA/HpSSDuhnMb1rBLF9MfDTpBQJbZ6Q1guXDEQqedvV+tfPBlg8Sv39cIiCRZ/BugJYPmjgI7wbwC92maYBUvEMo2jIxQiH3cjLyQJNdNFmDXDrBsroQbADWgC2TSjfx7QeRKbyoBeQkV8qNpL9L4foD1AY4D6Ft2Da6zrKbkDmnX37XwHfHC9fw3QpX4FWFsCEpCABCQgAQn4MeAlwACGRSlA3rsHDQAAAABJRU5ErkJggg==";

  string constant HAT_HAT___GOLD_CHALICE =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFAAAAv5w33sdf////Vw5yygAAAAR0Uk5T////AEAqqfQAAABaSURBVHja7NExDsAwCENRXN//zo1oZ5BAnfq9Bj1kEq4ST8qR8vE6kRRzQJkx8ArzCnsghWaHG0Hdiq8Byzvg3GAF5C/sKnhZAQAAAAAAAAAAAAAA4M/ALcAAfikvgABWLugAAAAASUVORK5CYII=";

  string constant HAT_HAT___GRADUATION_CAP_WITH_BLUE_TASSEL =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFAAAANTU1UGv/////Wu4LrwAAAAR0Uk5T////AEAqqfQAAABZSURBVHja7NLRCoBACAXRUf//n1s26DFCCQrmgk/iQVBqGN4GYASw0wa40gPgiXDTyukGWXGOR3UBYhGr+sAepw8Mz5jfeGUBAQEBAQEBAQEBAYEfA4cAAwBT9i8xSenp1QAAAABJRU5ErkJggg==";

  string constant HAT_HAT___GRADUATION_CAP_WITH_RED_TASSEL =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFAAAANTU1/1BZ////DFVn2gAAAAR0Uk5T////AEAqqfQAAABZSURBVHja7NLRCoBACAXRUf//n1s26DFCCQrmgk/iQVBqGN4GYASw0wa40gPgiXDTyukGWXGOR3UBYhGr+sAepw8Mz5jfeGUBAQEBAQEBAQEBAYEfA4cAAwBT9i8xSenp1QAAAABJRU5ErkJggg==";

  string constant HAT_HAT___GREEN_GOO =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFUf9aV9RdAAAA////8OJe4gAAAAR0Uk5T////AEAqqfQAAABZSURBVHja7NMxDsAwCATBA/7/54DdpwDFLrInWgYkhGIYAXwOeGYCuCTz8C6w+lOQ9YDqrso0N1DY3mFwhZqu0Rlfx58B4jbANwIAAAAAAAAAAAD8FngEGACpVi+IuGeNiwAAAABJRU5ErkJggg==";

  string constant HAT_HAT___NODE_OPERATORS_YELLOW_HARDHAT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF6sU32rg0AAAA////FTJkigAAAAR0Uk5T////AEAqqfQAAABkSURBVHja7NJBCoBADEPRpnP/O2ur4K6LyCDCD8wyj1Am1svEXiA7PpDRSRfIUPU1CiNw9lXPBGpA1ecJ04IHWN8A1wH7kDIX3JHsj1Tlsb79KwMAAAAAAAAAAAAAAPwaOAQYAGg2Lx54f7biAAAAAElFTkSuQmCC";

  string constant HAT_HAT___NONE =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAZQTFRF////AAAAVcLTfgAAAAF0Uk5TAEDm2GYAAAAdSURBVHja7MGBAAAAAMOg+VPf4ARVAQAAAHwTYAAQQAABpAJfkQAAAABJRU5ErkJggg==";

  string constant HAT_HAT___PINK_BUTTERFLY =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFyqLVwkvlRUVF////T//+XQAAAAR0Uk5T////AEAqqfQAAABZSURBVHja7NMxCgAgDEPRtN7/zmpxF5pNv6BOPpqAGubS40Ce3QSk9Tr31QUilPtoR5Ai4zLApcQ1gVViTWAAqg6MCBXf64C/AAAAAAAAAAAAAADwNzAFGACPxy+cXbN/7gAAAABJRU5ErkJggg==";

  string constant HAT_HAT___PINK_SUNHAT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF6Jr/AAAAyqLV////Ci+i2QAAAAR0Uk5T////AEAqqfQAAABiSURBVHja7NNBCoAwDETRmXj/O7uwIBUTagsi8ie7Qh5DS7UtRt8G3DIJ2IpjKiIHHDrHz4FuvxByoNsPv9mgXf2lQfYeuulexMMNho/1878AAAAAAAAAAAAAAACwkl2AAQAHsi65WX3y4QAAAABJRU5ErkJggg==";

  string constant HAT_HAT___POLICE_CAP =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFKjFYAAAA////////dNMazAAAAAR0Uk5T////AEAqqfQAAABUSURBVHja7NIxDgAgCENRqve/sxsyMdRBTX6ZeYnFmIeJpwFlPECRkQOU/U7ogLHHAWbZD6uD+gSvxGxBunPGJD7+ygAAAAAAAAAAAAAAAHeBJcAASGsvC6AT5bIAAAAASUVORK5CYII=";

  string constant HAT_HAT___RED_ASTRONAUT_HELMET =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF0UJK7Li6AAAA////qObwQwAAAAR0Uk5T////AEAqqfQAAACWSURBVHja7NXbCoAgEATQdfr/fy68kdlua6EQzDxFOAdBXGX7GJkKIOclAEiORchz3SY0oKlHYgzo+qog3r4miNlPh2AKFgCEmEK4gbI+1BiCDpz6RRgCmn4WlgKXfhIILDyFuy1g/C7AtQHrOsPTNwcKHH19pKGOg/y5dqQd/7sMvwuu+uynjQABAgQIECBA4J/ALsAACykq+68x4AkAAAAASUVORK5CYII=";

  string constant HAT_HAT___RED_BASEBALL_CAP =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF/1BZAAAAzUBI////ldQ1tgAAAAR0Uk5T////AEAqqfQAAABcSURBVHja7NJBCsAgDETRjL3/ncVxbVPiQik/iriZRwiJZ7PickCuOqBo46gKjLyvaoDzqRBZ3u+LkAOzheUwPwL+aGMPKh38ZJUBAAAAAAAAAAAAAABOAl2AAQA4Ti8sNA+R7wAAAABJRU5ErkJggg==";

  string constant HAT_HAT___RED_DEFI_WIZARD_HAT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF+mpRAAAAzUBI////1GURygAAAAR0Uk5T////AEAqqfQAAABgSURBVHja7NJBEsAgCEPRgPe/c20tW9sJS3/W5iEzaDSjH29ipgFESKlwgbs+Y/9g1Tf9D+Dt28Cz/b6/BWp+uoAqwweyBWStYF9irrRPGQAAAAAAAAAAAAAA4FTgEmAAezEvIu6Q7Q0AAAAASUVORK5CYII=";

  string constant HAT_HAT___RED_SHOWER_CAP =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAlQTFRF/1BZzUBI////gty5ygAAAAN0Uk5T//8A18oNQQAAAIBJREFUeNrs00sOgCAMBNCp9z8031ai1lCIcTOgiTHOQ1vBsTnwLQAIsArUcD7quQBYviNBICd0cRUkAoxvb1cyD5xpU8T7DAdoSR1vdfCBEuxTjUANyvK4zkgRW2TsifdHOW28PR5s49Nt/LKZCBAgQIAAAQIECBAgQGBjJAEGAIGBHsa3dBv/AAAAAElFTkSuQmCC";

  string constant HAT_HAT___RED_SPORTS_HELMET =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFBAQE/1BZ3ktT////++geoQAAAAR0Uk5T////AEAqqfQAAABwSURBVHja7NVBDoAgEEPRz3D/O6sIceeiDFFjux5eIIFCnQwvB2jRAUoLKtDXl0ADKGMHd8JaoJ8gJoA4IwEIY6kA2lwegDxoIA94/h4kvIV6lSHacx6NEHIn7jnK4NsfiwEDBgwYMGDAwD+BTYABAHeBLvlfVh8NAAAAAElFTkSuQmCC";

  string constant HAT_HAT___RED_UMBRELLA_HAT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF/1BZ3ktTAAAA////hP6nfQAAAAR0Uk5T////AEAqqfQAAACGSURBVHja7NPRCsAgCAXQq/3/P09TNgYzZL1scH3IIu6BojA2C98GNOsdYEERgQBYGSjjgHjYERtKAou4572FUxCPgJ65mKSkXUCvVAJpaQ+45ROoBTzmdVhkbtvCuwHzYNoB4rpyAxJd4mq1dYTFy/rdXyBAgAABAgQIECBAgACBnToEGABRVi6KAJCJVwAAAABJRU5ErkJggg==";

  string constant HAT_HAT___TAN_COWBOY_HAT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFnIFNAAAAiW8+////s4CSSAAAAAR0Uk5T////AEAqqfQAAAB7SURBVHja7NNLCsAgDATQmfT+d64frNkYia4Kk01AmYemFc9lIdgj6VoeIAB+LQ/UIIytBcIGgFl3joFeJ4DPl3MwB5TB03zeuPoWCK4/48EgEJ/ebMRXArb3nxIzM6hbrsZa7le+fgsCBAgQIECAAAECBAgQ8HPgFWAAHsIuMYdXW0IAAAAASUVORK5CYII=";

  string constant HAT_HAT___TAN_SUNHAT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFnIFNAAAAiW8+////s4CSSAAAAAR0Uk5T////AEAqqfQAAABiSURBVHja7NNBCoAwDETRmXj/O7uwIBUTagsi8ie7Qh5DS7UtRt8G3DIJ2IpjKiIHHDrHz4FuvxByoNsPv9mgXf2lQfYeuulexMMNho/1878AAAAAAAAAAAAAAACwkl2AAQAHsi65WX3y4QAAAABJRU5ErkJggg==";

  string constant HAT_HAT___TINY_BLUE_HAT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFAAAAUGv/S2Le////GFS2BwAAAAR0Uk5T////AEAqqfQAAABBSURBVHja7NLBCQAgEAPBnPbfs2IDgveT2QKGPJLZLIALkFMHqF0DSMbYQN6BqusEPwAAAAAAAAAAAACAr4ElwABPPi+9mXrDgwAAAABJRU5ErkJggg==";

  string constant HAT_HAT___TINY_RED_HAT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF/1BZAAAA3ktT////4F6kDAAAAAR0Uk5T////AEAqqfQAAABASURBVHja7NKxDQAwCANBIPvvHJQFKOii+wFOLhxnWQAmILsNkNHlBqhaAW/AIPgBAAAAAAAAAAAAAHwNXAEGAORLL8ds9TzwAAAAAElFTkSuQmCC";

  string constant HAT_HAT___WHITE_BOWLER_HAT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF////AAAA5eXl////vy5XywAAAAR0Uk5T////AEAqqfQAAABNSURBVHja7NIxCgAgDATBO/3/n4UgwSpCLGx2+wxXRPMxAVwAR33AitwF9n0tqNqfgDtAntcbigXjiE8EAAAAAAAAAAAAAAD4AiwBBgASDy9vioThbAAAAABJRU5ErkJggg==";

  string constant HAT_HAT___WHITE_TOP_HAT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF////AAAA5eXl////vy5XywAAAAR0Uk5T////AEAqqfQAAABLSURBVHja7NIhDgAgDEPRFe5/Z8wCqIpNIPi1y14qGrOZcEdlqoAiI4BngA6gCrDffQfTYFwpLrE9ZQAAAAAAAAAAAAAAgM+BJcAAxBQu9Xnq5qoAAAAASUVORK5CYII=";

  string constant HAT_HAT___WHITE_AND_RED_BASEBALL_CAP =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF+vr6AAAAzUBI////XMoRuAAAAAR0Uk5T////AEAqqfQAAABeSURBVHja7NJBDsAgCETRod7/zgZCGhe2JLhr/2jc8SCqxmH0dcAifcB0+bIu4PWxrQdEfSmoqo/zRdDz5SVQjKB987t3D8jn05L/fmUAAAAAAAAAAAAAAICDTAEGAHGGLwZQq7zvAAAAAElFTkSuQmCC";

  string constant HAT_HAT___WHITE_WITH_RED_HEADPHONES =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF////AAAA/1BZ////kuAAcAAAAAR0Uk5T////AEAqqfQAAABrSURBVHja7NPRCoAgEETRHfv/fy6EJHB3s8SXuvOmOEcR1rbJ2EpALa8AyVoSIgQu9Uo8BVTvPZMIlvTD5T3QFWLBBVS644dQNArIfMB9w0eB6U+sUzCwtX4aAQAAAAAAAAAAAAD+DewCDADEWi6TIEdx5AAAAABJRU5ErkJggg==";

  string constant HAT_HAT___WHITE_WITH_RED_TOP_HAT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF+vr6AAAA705W////GVgrSAAAAAR0Uk5T////AEAqqfQAAABNSURBVHja7NIxCgAwCENR097/zl2kdnKIY39W4WEgsYeJ7qiMCygyAvCBlTEBFSAHuAX6Es0HL2AucTxlAAAAAAAAAAAAAACAz4EjwABFHy79vdkRwQAAAABJRU5ErkJggg==";

  string constant HAT_SHIRT___BLACK_AND_BLUE_BASEBALL_CAP =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAlQTFRFAAAAQFbN////v/HJDgAAAAN0Uk5T//8A18oNQQAAAFBJREFUeNrs0jEKACAMQ9Ho/Q+tVnASA3UR+bZ0KXl0UPXy6XdAJSoN9OzsJDDCVpDLxzwIHjAn7DcrmQX4iQAAAAAAAAAAAAAAAG8ATYABAC3aH4WHV1TDAAAAAElFTkSuQmCC";

  string constant HAT_SHIRT___RED_UMBRELLA_HAT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF/1BZ3ktTAAAA////hP6nfQAAAAR0Uk5T////AEAqqfQAAACGSURBVHja7NPRCsAgCAXQq/3/P09TNgYzZL1scH3IIu6BojA2C98GNOsdYEERgQBYGSjjgHjYERtKAou4572FUxCPgJ65mKSkXUCvVAJpaQ+45ROoBTzmdVhkbtvCuwHzYNoB4rpyAxJd4mq1dYTFy/rdXyBAgAABAgQIECBAgACBnToEGABRVi6KAJCJVwAAAABJRU5ErkJggg==";

  function getAsset(uint256 headNum) external pure returns (string memory) {
    if (headNum == 0) {
      return HAT_HAT___ASTRONAUT_HELMET;
    } else if (headNum == 1) {
      return HAT_HAT___BAG_OF_ETHEREUM;
    } else if (headNum == 2) {
      return HAT_HAT___BLACK_BOWLER_HAT;
    } else if (headNum == 3) {
      return HAT_HAT___BLACK_TOP_HAT;
    } else if (headNum == 4) {
      return HAT_HAT___BLACK_AND_WHITE_STRIPED_JAIL_CAP;
    } else if (headNum == 5) {
      return HAT_HAT___BLACK_WITH_BLUE_HEADPHONES;
    } else if (headNum == 6) {
      return HAT_HAT___BLACK_WITH_BLUE_TOP_HAT;
    } else if (headNum == 7) {
      return HAT_HAT___BLUE_BASEBALL_CAP;
    } else if (headNum == 8) {
      return HAT_HAT___BLUE_UMBRELLA_HAT;
    } else if (headNum == 9) {
      return HAT_HAT___BULB_HELMET;
    } else if (headNum == 10) {
      return HAT_HAT___CHERRY_ON_TOP;
    } else if (headNum == 11) {
      return HAT_HAT___CRYPTO_INFLUENCER_BLUEBIRD;
    } else if (headNum == 12) {
      return HAT_HAT___GIANT_SUNFLOWER;
    } else if (headNum == 13) {
      return HAT_HAT___GOLD_CHALICE;
    } else if (headNum == 14) {
      return HAT_HAT___GRADUATION_CAP_WITH_BLUE_TASSEL;
    } else if (headNum == 15) {
      return HAT_HAT___GRADUATION_CAP_WITH_RED_TASSEL;
    } else if (headNum == 16) {
      return HAT_HAT___GREEN_GOO;
    } else if (headNum == 17) {
      return HAT_HAT___NODE_OPERATORS_YELLOW_HARDHAT;
    } else if (headNum == 18) {
      return HAT_HAT___NONE;
    } else if (headNum == 19) {
      return HAT_HAT___PINK_BUTTERFLY;
    } else if (headNum == 20) {
      return HAT_HAT___PINK_SUNHAT;
    } else if (headNum == 21) {
      return HAT_HAT___POLICE_CAP;
    } else if (headNum == 22) {
      return HAT_HAT___RED_ASTRONAUT_HELMET;
    } else if (headNum == 23) {
      return HAT_HAT___RED_BASEBALL_CAP;
    } else if (headNum == 24) {
      return HAT_HAT___RED_DEFI_WIZARD_HAT;
    } else if (headNum == 25) {
      return HAT_HAT___RED_SHOWER_CAP;
    } else if (headNum == 26) {
      return HAT_HAT___RED_SPORTS_HELMET;
    } else if (headNum == 27) {
      return HAT_HAT___RED_UMBRELLA_HAT;
    } else if (headNum == 28) {
      return HAT_HAT___TAN_COWBOY_HAT;
    } else if (headNum == 29) {
      return HAT_HAT___TAN_SUNHAT;
    } else if (headNum == 30) {
      return HAT_HAT___TINY_BLUE_HAT;
    } else if (headNum == 31) {
      return HAT_HAT___TINY_RED_HAT;
    } else if (headNum == 32) {
      return HAT_HAT___WHITE_BOWLER_HAT;
    } else if (headNum == 33) {
      return HAT_HAT___WHITE_TOP_HAT;
    } else if (headNum == 34) {
      return HAT_HAT___WHITE_AND_RED_BASEBALL_CAP;
    } else if (headNum == 35) {
      return HAT_HAT___WHITE_WITH_RED_HEADPHONES;
    } else if (headNum == 36) {
      return HAT_HAT___WHITE_WITH_RED_TOP_HAT;
    } else if (headNum == 37) {
      return HAT_SHIRT___BLACK_AND_BLUE_BASEBALL_CAP;
    } else if (headNum == 38) {
      return HAT_SHIRT___RED_UMBRELLA_HAT;
    }
    return HAT_HAT___ASTRONAUT_HELMET;
  }
}

// SPDX-License-Identifier: MIT
// OpenZeppelin Contracts (last updated v4.7.0) (utils/Strings.sol)

pragma solidity ^0.8.0;

/**
 * @dev String operations.
 */
library Strings {
    bytes16 private constant _HEX_SYMBOLS = "0123456789abcdef";
    uint8 private constant _ADDRESS_LENGTH = 20;

    /**
     * @dev Converts a `uint256` to its ASCII `string` decimal representation.
     */
    function toString(uint256 value) internal pure returns (string memory) {
        // Inspired by OraclizeAPI's implementation - MIT licence
        // https://github.com/oraclize/ethereum-api/blob/b42146b063c7d6ee1358846c198246239e9360e8/oraclizeAPI_0.4.25.sol

        if (value == 0) {
            return "0";
        }
        uint256 temp = value;
        uint256 digits;
        while (temp != 0) {
            digits++;
            temp /= 10;
        }
        bytes memory buffer = new bytes(digits);
        while (value != 0) {
            digits -= 1;
            buffer[digits] = bytes1(uint8(48 + uint256(value % 10)));
            value /= 10;
        }
        return string(buffer);
    }

    /**
     * @dev Converts a `uint256` to its ASCII `string` hexadecimal representation.
     */
    function toHexString(uint256 value) internal pure returns (string memory) {
        if (value == 0) {
            return "0x00";
        }
        uint256 temp = value;
        uint256 length = 0;
        while (temp != 0) {
            length++;
            temp >>= 8;
        }
        return toHexString(value, length);
    }

    /**
     * @dev Converts a `uint256` to its ASCII `string` hexadecimal representation with fixed length.
     */
    function toHexString(uint256 value, uint256 length) internal pure returns (string memory) {
        bytes memory buffer = new bytes(2 * length + 2);
        buffer[0] = "0";
        buffer[1] = "x";
        for (uint256 i = 2 * length + 1; i > 1; --i) {
            buffer[i] = _HEX_SYMBOLS[value & 0xf];
            value >>= 4;
        }
        require(value == 0, "Strings: hex length insufficient");
        return string(buffer);
    }

    /**
     * @dev Converts an `address` with fixed length of 20 bytes to its not checksummed ASCII `string` hexadecimal representation.
     */
    function toHexString(address addr) internal pure returns (string memory) {
        return toHexString(uint256(uint160(addr)), _ADDRESS_LENGTH);
    }
}