// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

import {ICharacterSVGRenderer} from "../interfaces/ICharacterSVGRenderer.sol";

contract TwentyThroughTwentyEightCharacterRenderHelper is ICharacterSVGRenderer {
    function characterSVG(uint8 character) public pure returns (string memory) {
        if (character == 20) {
            return _santaBasic();
        } else if (character == 21) {
            return _santaZoom();
        } else if (character == 22) {
            return _skeleton();
        } else if (character == 23) {
            return _snowmanChunky();
        } else if (character == 24) {
            return _snowmanSlender();
        } else if (character == 25) {
            return _snowmanZoom();
        } else if (character == 26) {
            return _sugarPlumFairy();
        } else if (character == 27) {
            return _shortThief();
        } else if (character == 28) {
            return _tallThief();
        }
        return "";
    }

    function _santaBasic() internal pure returns (string memory) {
        return '<rect x="5" y="18" width="6" height="4" fill="#08030D"/>'
        '<rect x="4" y="21" width="1" height="1" fill="#08030D"/>'
        '<rect x="19" y="21" width="1" height="1" fill="#08030D"/>'
        '<rect width="6" height="4" transform="matrix(-1 0 0 1 19 18)" fill="#08030D"/>'
        '<rect width="14" height="4" transform="matrix(1 0 0 -1 5 15)" class="tintable"/>'
        '<rect x="6" y="2" width="1" height="1" fill="#F9F4F2"/>'
        '<rect x="20" y="8" width="1" height="1" fill="#F9F4F2"/>'
        '<rect x="3" y="15" width="1" height="1" fill="#F9F4F2"/>'
        '<rect x="9" y="19" width="1" height="2" fill="#F9F4F2"/>'
        '<rect x="17" y="19" width="1" height="2" fill="#F9F4F2"/>'
        '<rect x="13" y="13" width="1" height="2" fill="#F9F4F2"/>'
        '<rect x="7" y="9" width="11" height="4" fill="#F9F4F2"/>'
        '<rect x="14" y="4" width="2" height="1" fill="#F9F4F2"/>'
        '<rect x="7" y="2" width="2" height="1" class="tintable"/>'
        '<rect x="20" y="9" width="1" height="4" class="tintable"/>'
        '<rect x="3" y="11" width="1" height="4" class="tintable"/>'
        '<rect width="1" height="1" transform="matrix(1 0 0 -1 19 14)" class="tintable"/>'
        '<rect width="1" height="1" transform="matrix(1 0 0 -1 4 11)" class="tintable"/>'
        '<rect x="7" y="3" width="4" height="1" class="tintable"/>'
        '<rect x="8" y="4" width="4" height="1" class="tintable"/>'
        '<rect x="5" y="17" width="6" height="1" class="tintable"/>'
        '<rect x="13" y="17" width="6" height="1" class="tintable"/>'
        '<rect x="8" y="5" width="4" height="1" fill="#F9F4F2"/>'
        '<rect x="5" y="16" width="14" height="1" fill="#F9F4F2"/>'
        '<rect x="8" y="6" width="6" height="1" fill="#F38B7C"/>'
        '<rect width="1" height="1" transform="matrix(-1 0 0 1 21 7)" fill="#F38B7C"/>'
        '<rect width="1" height="1" transform="matrix(-1 0 0 1 4 16)" fill="#F38B7C"/>'
        '<rect x="7" y="7" width="7" height="2" fill="#F38B7C"/>'
        '<rect x="8" y="10" width="9" height="1" fill="#FF0E0E"/>'
        '<rect x="5" y="15" width="7" height="1" fill="#08030D"/>'
        '<rect x="15" y="15" width="4" height="1" fill="#08030D"/>'
        '<rect x="12" y="15" width="3" height="1" fill="#F0C14D"/>';
    }

    function _santaZoom() internal pure returns (string memory) {
        return '<rect y="14" width="24" height="10" class="tintable"/>'
        '<rect x="4" y="3" width="1" height="1" class="tintable"/>'
        '<rect x="5" y="2" width="5" height="1" class="tintable"/>'
        '<rect x="6" y="3" width="6" height="1" class="tintable"/>'
        '<rect x="7" y="4" width="7" height="1" class="tintable"/>'
        '<rect x="6" y="5" width="9" height="1" fill="white"/>'
        '<rect x="6" y="6" width="9" height="1" fill="#F38B7C"/>'
        '<rect x="7" y="7" width="8" height="2" fill="#F38B7C"/>'
        '<rect x="5" y="7" width="1" height="2" fill="#F38B7C"/>'
        '<rect x="6" y="7" width="1" height="2" fill="white"/>' '<rect x="4" y="4" width="1" height="1" fill="white"/>'
        '<rect x="5" y="9" width="15" height="5" fill="white"/>'
        '<rect x="6" y="14" width="14" height="1" fill="white"/>'
        '<rect x="7" y="15" width="13" height="1" fill="white"/>'
        '<rect x="8" y="16" width="12" height="1" fill="white"/>'
        '<rect x="9" y="17" width="11" height="1" fill="white"/>'
        '<rect x="10" y="18" width="10" height="1" fill="white"/>'
        '<rect x="11" y="19" width="9" height="1" fill="white"/>'
        '<rect x="12" y="20" width="8" height="1" fill="white"/>'
        '<rect x="13" y="21" width="7" height="1" fill="white"/>'
        '<rect x="14" y="22" width="6" height="1" fill="white"/>'
        '<rect x="15" y="23" width="5" height="1" fill="white"/>'
        '<rect x="8" y="10" width="11" height="1" fill="#FF0E0E"/>';
    }

    function _skeleton() internal pure returns (string memory) {
        return '<rect x="10" y="2" width="3" height="1" fill="white"/>'
        '<rect x="10" y="7" width="3" height="1" fill="white"/>' '<rect x="9" y="3" width="5" height="4" fill="white"/>'
        '<rect x="12" y="3" width="1" height="1" class="tintable"/>'
        '<rect x="10" y="3" width="1" height="1" class="tintable"/>'
        '<rect x="9" y="8" width="5" height="3" class="tintable"/>'
        '<rect x="11" y="5" width="1" height="1" class="tintable"/>'
        '<rect x="11" y="9" width="1" height="1" fill="white"/>'
        '<rect x="9" y="5" width="1" height="1" class="tintable"/>'
        '<rect x="13" y="5" width="1" height="1" class="tintable"/>'
        '<rect x="12" y="6" width="1" height="1" class="tintable"/>'
        '<rect x="14" y="12" width="1" height="1" class="tintable"/>'
        '<rect x="15" y="8" width="1" height="2" class="tintable"/>'
        '<rect x="16" y="10" width="1" height="3" class="tintable"/>'
        '<rect x="17" y="16" width="1" height="2" fill="white"/>'
        '<rect x="7" y="16" width="1" height="2" fill="white"/>'
        '<rect x="7" y="8" width="1" height="8" class="tintable"/>'
        '<rect x="17" y="13" width="1" height="3" class="tintable"/>'
        '<rect x="14" y="14" width="1" height="1" class="tintable"/>'
        '<rect x="12" y="21" width="2" height="1" class="tintable"/>'
        '<rect x="9" y="21" width="2" height="1" class="tintable"/>'
        '<rect x="12" y="8" width="1" height="13" class="tintable"/>'
        '<rect x="10" y="13" width="1" height="8" class="tintable"/>'
        '<rect x="10" y="6" width="1" height="1" class="tintable"/>'
        '<rect x="10" y="11" width="3" height="2" class="tintable"/>'
        '<rect x="12" y="13" width="2" height="1" class="tintable"/>';
    }

    function _snowmanChunky() internal pure returns (string memory) {
        return '<rect x="9" y="6" width="7" height="6" fill="#F9F4F2"/>'
        '<rect x="6" y="12" width="13" height="8" fill="#F9F4F2"/>'
        '<rect x="11" y="1" width="3" height="4" fill="#08030D"/>'
        '<rect width="7" height="1" transform="matrix(1 0 0 -1 9 6)" fill="#08030D"/>'
        '<rect x="11" y="7" width="1" height="1" fill="#08030D"/>'
        '<rect x="9" y="10" width="1" height="1" fill="#08030D"/>'
        '<rect x="11" y="10" width="1" height="1" fill="#08030D"/>'
        '<rect x="13" y="10" width="1" height="1" fill="#08030D"/>'
        '<rect x="15" y="10" width="1" height="1" fill="#08030D"/>'
        '<rect x="12" y="13" width="1" height="1" fill="#08030D"/>'
        '<rect x="19" y="13" width="1" height="1" class="tintable"/>'
        '<rect x="5" y="16" width="1" height="1" class="tintable"/>'
        '<rect x="20" y="12" width="1" height="6" class="tintable"/>'
        '<rect x="4" y="12" width="1" height="6" class="tintable"/>'
        '<rect x="12" y="15" width="1" height="1" fill="#08030D"/>'
        '<rect x="12" y="17" width="1" height="1" fill="#08030D"/>'
        '<rect x="13" y="8" width="1" height="1" fill="#08030D"/>'
        '<rect x="12" y="9" width="4" height="1" class="tintable"/>'
        '<rect x="7" y="20" width="11" height="1" fill="#F9F4F2"/>'
        '<rect x="8" y="21" width="9" height="1" fill="#F9F4F2"/>'
        '<rect x="18" y="21" width="1" height="1" fill="#F9F4F2"/>'
        '<rect x="19" y="20" width="2" height="2" fill="#F9F4F2"/>'
        '<rect x="4" y="20" width="2" height="2" fill="#F9F4F2"/>'
        '<rect x="6" y="21" width="1" height="1" fill="#F9F4F2"/>'
        '<rect x="21" y="19" width="1" height="3" fill="#08030D"/>'
        '<rect x="3" y="19" width="1" height="3" fill="#08030D"/>';
    }

    function _snowmanSlender() internal pure returns (string memory) {
        return '<rect x="10" y="1" width="3" height="2" fill="#16786C"/>'
        '<rect x="17" y="14" width="3" height="3" fill="#CB7300"/>'
        '<rect x="9" y="3" width="5" height="1" fill="#16786C"/>'
        '<rect x="10" y="4" width="3" height="3" class="tintable"/>'
        '<rect x="9" y="7" width="5" height="6" class="tintable"/>'
        '<rect x="12" y="13" width="2" height="9" class="tintable"/>'
        '<rect x="9" y="13" width="2" height="9" class="tintable"/>'
        '<rect x="11" y="5" width="1" height="1" fill="#FD5442"/>'
        '<rect x="5" y="15" width="12" height="1" fill="#36262D"/>'
        '<rect x="7" y="8" width="1" height="9" class="tintable"/>'
        '<rect x="15" y="8" width="1" height="9" class="tintable"/>';
    }

    function _snowmanZoom() internal pure returns (string memory) {
        return '<rect x="9" y="1" width="7" height="2" class="tintable"/>'
        '<rect x="10" y="3" width="6" height="1" fill="black"/>'
        '<rect x="11" y="4" width="5" height="1" fill="black"/>'
        '<rect x="9" y="3" width="1" height="1" fill="#F38B7C"/>'
        '<rect x="8" y="4" width="1" height="1" fill="#F38B7C"/>'
        '<rect x="5" y="4" width="1" height="1" class="tintable"/>'
        '<rect x="19" y="4" width="1" height="1" class="tintable"/>'
        '<rect x="6" y="5" width="13" height="1" class="tintable"/>'
        '<rect x="7" y="6" width="11" height="1" fill="white"/>'
        '<rect x="7" y="13" width="11" height="1" fill="white"/>'
        '<rect x="8" y="14" width="9" height="1" fill="white"/>'
        '<rect x="9" y="15" width="7" height="1" fill="white"/>' '<rect y="14" width="7" height="10" fill="white"/>'
        '<rect x="7" y="16" width="11" height="8" fill="white"/>'
        '<rect x="18" y="14" width="6" height="10" fill="white"/>'
        '<rect x="10" y="4" width="1" height="1" fill="#F38B7C"/>'
        '<rect x="9" y="4" width="1" height="1" fill="#2A46FF"/>'
        '<rect x="6" y="7" width="13" height="6" fill="white"/>'
        '<rect x="8" y="11" width="9" height="1" fill="black"/>'
        '<rect x="11" y="9" width="3" height="3" fill="#FD5442"/>'
        '<rect x="12" y="17" width="1" height="1" fill="black"/>'
        '<rect x="17" y="15" width="1" height="1" fill="white"/>'
        '<rect x="7" y="15" width="1" height="1" fill="white"/>'
        '<rect x="12" y="20" width="1" height="1" fill="black"/>';
    }

    function _sugarPlumFairy() internal pure returns (string memory) {
        return '<rect x="7" y="3" width="2" height="2" fill="#36262D"/>'
        '<rect x="9" y="3" width="1" height="2" fill="#7C3C58"/>'
        '<rect x="10" y="3" width="1" height="1" fill="#7C3C58"/>'
        '<rect x="10" y="8" width="3" height="4" fill="#7C3C58"/>'
        '<rect x="10" y="5" width="1" height="1" fill="#7C3C58"/>'
        '<rect x="11" y="5" width="2" height="1" class="tintable"/>'
        '<rect x="13" y="8" width="2" height="1" class="tintable"/>'
        '<rect x="6" y="10" width="3" height="1" class="tintable"/>'
        '<rect x="15" y="7" width="2" height="1" class="tintable"/>'
        '<rect x="17" y="6" width="1" height="1" class="tintable"/>'
        '<rect x="18" y="5" width="1" height="1" class="tintable"/>'
        '<rect x="9" y="9" width="1" height="1" class="tintable"/>'
        '<rect x="5" y="11" width="1" height="1" class="tintable"/>'
        '<rect x="3" y="10" width="1" height="1" class="tintable"/>'
        '<rect x="17" y="3" width="1" height="1" class="tintable"/>'
        '<rect x="18" y="4" width="1" height="1" fill="#F38B7C"/>'
        '<rect x="9" y="8" width="1" height="1" fill="#F38B7C"/>'
        '<rect x="7" y="14" width="1" height="1" fill="#F38B7C"/>'
        '<rect x="9" y="14" width="1" height="1" fill="#F38B7C"/>'
        '<rect x="11" y="14" width="1" height="1" fill="#F38B7C"/>'
        '<rect x="13" y="14" width="1" height="1" fill="#F38B7C"/>'
        '<rect x="12" y="14" width="1" height="3" class="tintable"/>'
        '<rect x="10" y="14" width="1" height="3" class="tintable"/>'
        '<rect x="10" y="17" width="2" height="3" class="tintable"/>'
        '<rect x="10" y="20" width="2" height="2" fill="#7C3C58"/>'
        '<rect x="15" y="14" width="1" height="1" fill="#F38B7C"/>'
        '<rect x="20" y="8" width="1" height="1" fill="#2A46FF"/>'
        '<rect x="18" y="10" width="1" height="1" fill="#2A46FF"/>'
        '<rect x="20" y="11" width="1" height="1" fill="#2A46FF"/>'
        '<rect x="19" y="14" width="1" height="1" fill="#2A46FF"/>'
        '<rect x="8" y="17" width="1" height="1" fill="#2A46FF"/>'
        '<rect x="5" y="17" width="1" height="1" fill="#2A46FF"/>'
        '<rect x="7" y="20" width="1" height="1" fill="#2A46FF"/>'
        '<rect x="9" y="12" width="5" height="1" fill="#F38B7C"/>'
        '<rect x="6" y="13" width="11" height="1" fill="#F38B7C"/>'
        '<rect x="4" y="11" width="1" height="1" fill="#F38B7C"/>'
        '<rect x="10" y="6" width="3" height="2" class="tintable"/>'
        '<rect x="11" y="4" width="2" height="1" fill="#7C3C58"/>'
        '<rect x="5" y="4" width="2" height="1" fill="#F38B7C"/>'
        '<rect x="7" y="7" width="2" height="1" fill="#F38B7C"/>'
        '<rect x="5" y="5" width="3" height="1" fill="#F38B7C"/>'
        '<rect x="6" y="6" width="3" height="1" fill="#F38B7C"/>'
        '<rect x="8" y="5" width="2" height="1" fill="#36262D"/>'
        '<rect x="9" y="6" width="1" height="1" fill="#36262D"/>'
        '<rect x="10" y="4" width="1" height="1" fill="#2A46FF"/>';
    }

    function _shortThief() internal pure returns (string memory) {
        return '<rect x="10" y="3" width="1" height="1" fill="black"/>'
        '<rect x="9" y="4" width="7" height="2" fill="black"/>' '<rect x="12" y="3" width="1" height="1" fill="black"/>'
        '<rect x="14" y="3" width="1" height="1" fill="black"/>'
        '<rect x="13" y="3" width="1" height="1" fill="#F38B7C"/>'
        '<rect x="11" y="3" width="1" height="1" fill="#F38B7C"/>'
        '<rect x="5" y="16" width="1" height="1" fill="#F38B7C"/>'
        '<rect x="18" y="16" width="1" height="1" fill="#F38B7C"/>'
        '<rect x="12" y="11" width="1" height="1" fill="#7C3C58"/>'
        '<rect x="12" y="13" width="1" height="1" fill="black"/>'
        '<rect x="8" y="18" width="3" height="2" fill="black"/>'
        '<rect x="12" y="18" width="3" height="2" fill="black"/>'
        '<rect x="12" y="12" width="1" height="1" fill="#36262D"/>'
        '<rect x="12" y="14" width="1" height="1" fill="#36262D"/>'
        '<rect x="12" y="16" width="1" height="2" fill="#36262D"/>'
        '<rect x="12" y="15" width="1" height="1" fill="black"/>'
        '<rect x="12" y="20" width="1" height="1" fill="black"/>'
        '<rect x="12" y="21" width="3" height="1" fill="black"/>'
        '<rect x="8" y="21" width="3" height="1" fill="black"/>'
        '<rect x="9" y="20" width="1" height="1" fill="black"/>'
        '<rect x="10" y="9" width="1" height="9" fill="#36262D"/>'
        '<rect x="8" y="9" width="2" height="9" class="tintable"/>'
        '<rect x="15" y="9" width="2" height="9" class="tintable"/>'
        '<rect x="18" y="9" width="2" height="7" class="tintable"/>'
        '<rect x="4" y="9" width="3" height="7" class="tintable"/>'
        '<rect x="14" y="9" width="1" height="9" fill="#36262D"/>'
        '<rect x="11" y="11" width="1" height="7" fill="#36262D"/>'
        '<rect x="13" y="11" width="1" height="7" fill="#36262D"/>'
        '<rect x="11" y="9" width="3" height="1" fill="#F38B7C"/>'
        '<rect x="11" y="10" width="3" height="1" fill="#7C3C58"/>'
        '<rect x="9" y="6" width="7" height="3" fill="#F38B7C"/>'
        '<rect x="20" y="11" width="1" height="5" class="tintable"/>';
    }

    function _tallThief() internal pure returns (string memory) {
        return '<rect x="6" y="1" width="1" height="1" class="tintable"/>'
        '<rect x="8" y="13" width="1" height="1" class="tintable"/>'
        '<rect x="8" y="15" width="1" height="2" class="tintable"/>'
        '<rect x="10" y="15" width="1" height="2" class="tintable"/>'
        '<rect x="14" y="15" width="1" height="2" class="tintable"/>'
        '<rect x="16" y="15" width="1" height="2" class="tintable"/>'
        '<rect x="15" y="15" width="1" height="2" fill="#F38B7C"/>'
        '<rect x="13" y="15" width="1" height="2" fill="#F38B7C"/>'
        '<rect x="11" y="15" width="1" height="2" fill="#F38B7C"/>'
        '<rect x="9" y="15" width="1" height="2" fill="#F38B7C"/>'
        '<rect x="10" y="17" width="2" height="1" fill="#F38B7C"/>'
        '<rect x="11" y="18" width="3" height="1" fill="#F38B7C"/>'
        '<rect x="13" y="17" width="2" height="1" fill="#F38B7C"/>'
        '<rect x="12" y="15" width="1" height="3" class="tintable"/>'
        '<rect x="16" y="13" width="1" height="1" class="tintable"/>'
        '<rect x="9" y="17" width="1" height="1" class="tintable"/>'
        '<rect x="8" y="17" width="1" height="1" fill="#CB7300"/>'
        '<rect x="9" y="18" width="1" height="1" fill="#CB7300"/>'
        '<rect x="10" y="19" width="1" height="1" fill="#CB7300"/>'
        '<rect x="15" y="18" width="1" height="1" fill="#CB7300"/>'
        '<rect x="14" y="19" width="1" height="1" fill="#CB7300"/>'
        '<rect x="16" y="17" width="1" height="1" fill="#CB7300"/>'
        '<rect x="15" y="17" width="1" height="1" class="tintable"/>'
        '<rect x="16" y="18" width="1" height="1" class="tintable"/>'
        '<rect x="8" y="18" width="1" height="1" class="tintable"/>'
        '<rect x="15" y="19" width="2" height="1" class="tintable"/>'
        '<rect x="8" y="19" width="2" height="1" class="tintable"/>'
        '<rect x="8" y="11" width="1" height="1" class="tintable"/>'
        '<rect x="8" y="12" width="9" height="1" fill="#F38B7C"/>'
        '<rect x="8" y="14" width="9" height="1" fill="#F38B7C"/>'
        '<rect x="9" y="13" width="7" height="1" fill="#F38B7C"/>'
        '<rect x="9" y="11" width="1" height="1" fill="black"/>'
        '<rect x="11" y="11" width="1" height="1" fill="black"/>'
        '<rect x="13" y="11" width="1" height="1" fill="black"/>'
        '<rect x="15" y="11" width="1" height="1" fill="black"/>'
        '<rect x="14" y="11" width="1" height="1" fill="white"/>'
        '<rect x="14" y="18" width="1" height="1" fill="white"/>'
        '<rect x="12" y="20" width="1" height="4" fill="white"/>'
        '<rect x="11" y="20" width="1" height="4" fill="#CB7300"/>'
        '<rect x="13" y="20" width="1" height="4" fill="#CB7300"/>'
        '<rect x="14" y="20" width="3" height="4" class="tintable"/>'
        '<rect x="8" y="20" width="3" height="4" class="tintable"/>'
        '<rect x="11" y="19" width="3" height="1" fill="white"/>'
        '<rect x="10" y="11" width="1" height="1" fill="white"/>'
        '<rect x="10" y="18" width="1" height="1" fill="white"/>'
        '<rect x="16" y="11" width="1" height="1" class="tintable"/>'
        '<rect x="9" y="4" width="1" height="1" class="tintable"/>'
        '<rect x="8" y="4" width="1" height="1" fill="#F38B7C"/>'
        '<rect x="8" y="9" width="4" height="2" fill="#F38B7C"/>'
        '<rect x="13" y="9" width="4" height="2" fill="#F38B7C"/>'
        '<rect x="10" y="4" width="1" height="1" fill="#F38B7C"/>'
        '<rect x="12" y="4" width="1" height="1" fill="#F38B7C"/>'
        '<rect x="14" y="4" width="1" height="1" fill="#F38B7C"/>'
        '<rect x="16" y="4" width="1" height="1" fill="#F38B7C"/>'
        '<rect x="12" y="9" width="1" height="3" fill="#FD5442"/>'
        '<rect x="8" y="5" width="9" height="4" fill="#F38B7C"/>'
        '<rect x="7" y="7" width="1" height="3" class="tintable"/>'
        '<rect x="17" y="7" width="1" height="3" class="tintable"/>'
        '<rect x="11" y="4" width="1" height="1" class="tintable"/>'
        '<rect x="13" y="4" width="1" height="1" class="tintable"/>'
        '<rect x="15" y="4" width="1" height="1" class="tintable"/>'
        '<rect x="6" y="4" width="2" height="1" class="tintable"/>'
        '<rect x="5" y="5" width="3" height="1" class="tintable"/>'
        '<rect x="6" y="6" width="2" height="1" class="tintable"/>'
        '<rect x="17" y="6" width="2" height="1" class="tintable"/>'
        '<rect x="17" y="5" width="3" height="1" class="tintable"/>'
        '<rect x="17" y="4" width="2" height="1" class="tintable"/>'
        '<rect x="7" y="2" width="11" height="1" class="tintable"/>'
        '<rect x="5" y="3" width="15" height="1" class="tintable"/>'
        '<rect x="8" y="1" width="1" height="1" class="tintable"/>'
        '<rect x="10" y="1" width="1" height="1" class="tintable"/>'
        '<rect x="12" y="1" width="1" height="1" class="tintable"/>'
        '<rect x="14" y="1" width="1" height="1" class="tintable"/>'
        '<rect x="16" y="1" width="1" height="1" class="tintable"/>'
        '<rect x="18" y="1" width="1" height="1" class="tintable"/>'
        '<rect x="2" y="10" width="6" height="1" fill="black"/>'
        '<rect x="17" y="10" width="5" height="1" fill="black"/>'
        '<rect x="3" y="11" width="5" height="1" fill="black"/>'
        '<rect x="17" y="11" width="4" height="1" fill="black"/>'
        '<rect x="4" y="12" width="4" height="1" fill="black"/>'
        '<rect x="17" y="12" width="3" height="1" fill="black"/>'
        '<rect x="5" y="13" width="3" height="1" fill="black"/>'
        '<rect x="17" y="13" width="2" height="1" fill="black"/>'
        '<rect x="6" y="14" width="2" height="1" fill="black"/>'
        '<rect x="7" y="15" width="1" height="9" fill="black"/>'
        '<rect x="17" y="14" width="1" height="10" fill="black"/>'
        '<rect x="18" y="14" width="6" height="10" fill="#06534A"/>'
        '<rect y="14" width="6" height="10" fill="#06534A"/>' '<rect x="6" y="15" width="1" height="9" fill="#06534A"/>';
    }

    function _tree() internal pure returns (string memory) {
        return '<rect x="9" y="21" width="5" height="1" class="tintable"/>'
        '<rect x="10" y="20" width="3" height="1" fill="#513340"/>'
        '<rect x="11" y="19" width="1" height="1" fill="#513340"/>'
        '<rect x="10" y="19" width="1" height="1" fill="#369F49"/>'
        '<rect x="14" y="19" width="1" height="1" fill="#369F49"/>'
        '<rect x="17" y="17" width="1" height="1" fill="#369F49"/>'
        '<rect x="13" y="15" width="2" height="1" fill="#369F49"/>'
        '<rect x="9" y="15" width="3" height="1" fill="#369F49"/>'
        '<rect x="14" y="16" width="3" height="1" fill="#369F49"/>'
        '<rect x="8" y="19" width="1" height="1" fill="#369F49"/>'
        '<rect x="5" y="17" width="1" height="1" fill="#369F49"/>'
        '<rect x="6" y="15" width="1" height="1" fill="#369F49"/>'
        '<rect x="8" y="14" width="1" height="1" fill="#369F49"/>'
        '<rect x="16" y="13" width="1" height="1" fill="#369F49"/>'
        '<rect x="15" y="11" width="1" height="1" fill="#369F49"/>'
        '<rect x="14" y="10" width="1" height="1" fill="#369F49"/>'
        '<rect x="11" y="11" width="3" height="1" fill="#369F49"/>'
        '<rect x="7" y="13" width="1" height="1" fill="#369F49"/>'
        '<rect x="7" y="10" width="1" height="1" fill="#369F49"/>'
        '<rect x="9" y="4" width="1" height="1" fill="#369F49"/>'
        '<rect x="13" y="4" width="1" height="1" fill="#369F49"/>'
        '<rect x="11" y="2" width="1" height="3" fill="#369F49"/>'
        '<rect x="10" y="5" width="3" height="1" fill="#369F49"/>'
        '<rect x="9" y="10" width="4" height="1" fill="#369F49"/>'
        '<rect x="11" y="6" width="2" height="4" fill="#369F49"/>'
        '<rect x="8" y="11" width="2" height="1" fill="#369F49"/>'
        '<rect x="9" y="13" width="5" height="1" fill="#369F49"/>'
        '<rect x="10" y="12" width="5" height="1" fill="#369F49"/>'
        '<rect x="10" y="14" width="6" height="1" fill="#369F49"/>'
        '<rect x="7" y="16" width="6" height="1" fill="#369F49"/>'
        '<rect x="6" y="18" width="11" height="1" fill="#369F49"/>'
        '<rect x="8" y="17" width="7" height="1" fill="#369F49"/>'
        '<rect x="12" y="19" width="1" height="1" fill="#369F49"/>';
    }

    function _yetiBasic() internal pure returns (string memory) {
        return '<rect x="12" y="2" width="1" height="1" class="tintable"/>'
        '<rect x="10" y="3" width="5" height="1" class="tintable"/>'
        '<rect x="10" y="4" width="1" height="1" class="tintable"/>'
        '<rect x="12" y="4" width="1" height="1" class="tintable"/>'
        '<rect x="14" y="4" width="1" height="1" class="tintable"/>'
        '<rect x="9" y="5" width="1" height="1" class="tintable"/>'
        '<rect x="15" y="5" width="1" height="1" class="tintable"/>'
        '<rect x="9" y="6" width="7" height="1" class="tintable"/>'
        '<rect x="9" y="7" width="1" height="1" class="tintable"/>'
        '<rect x="15" y="7" width="1" height="1" class="tintable"/>'
        '<rect x="8" y="8" width="9" height="1" class="tintable"/>'
        '<rect x="9" y="9" width="8" height="2" class="tintable"/>'
        '<rect x="18" y="9" width="2" height="5" class="tintable"/>'
        '<rect x="9" y="11" width="1" height="1" class="tintable"/>'
        '<rect x="16" y="11" width="1" height="1" class="tintable"/>'
        '<rect x="9" y="12" width="8" height="2" class="tintable"/>'
        '<rect x="4" y="9" width="4" height="5" class="tintable"/>'
        '<rect x="4" y="14" width="3" height="4" class="tintable"/>'
        '<rect x="8" y="14" width="8" height="2" class="tintable"/>'
        '<rect x="17" y="14" width="3" height="4" class="tintable"/>'
        '<rect x="8" y="16" width="7" height="1" class="tintable"/>'
        '<rect x="8" y="17" width="3" height="4" class="tintable"/>'
        '<rect x="12" y="17" width="3" height="4" class="tintable"/>'
        '<rect x="11" y="4" width="1" height="1" fill="#2A46FF"/>'
        '<rect x="5" y="18" width="2" height="1" fill="#2A46FF"/>'
        '<rect x="17" y="18" width="3" height="1" fill="#2A46FF"/>'
        '<rect x="12" y="21" width="3" height="1" fill="#2A46FF"/>'
        '<rect x="8" y="21" width="3" height="1" fill="#2A46FF"/>'
        '<rect x="11" y="5" width="1" height="1" fill="black"/>'
        '<rect x="13" y="5" width="1" height="1" fill="black"/>'
        '<rect x="13" y="4" width="1" height="1" fill="#2A46FF"/>'
        '<rect x="12" y="5" width="1" height="1" fill="#2A46FF"/>'
        '<rect x="14" y="5" width="1" height="1" fill="#2A46FF"/>'
        '<rect x="10" y="7" width="5" height="1" fill="#2A46FF"/>'
        '<rect x="10" y="5" width="1" height="1" fill="#2A46FF"/>';
    }

    function _yetiZoom() internal pure returns (string memory) {
        return '<rect x="8" y="2" width="7" height="1" class="tintable"/>'
        '<rect x="6" y="3" width="11" height="1" class="tintable"/>'
        '<rect x="5" y="4" width="13" height="1" class="tintable"/>'
        '<rect x="5" y="5" width="2" height="1" class="tintable"/>'
        '<rect x="8" y="5" width="1" height="1" class="tintable"/>'
        '<rect x="10" y="5" width="1" height="1" class="tintable"/>'
        '<rect x="12" y="5" width="1" height="1" class="tintable"/>'
        '<rect x="14" y="5" width="1" height="1" class="tintable"/>'
        '<rect x="16" y="5" width="2" height="1" class="tintable"/>'
        '<rect x="4" y="6" width="2" height="3" class="tintable"/>'
        '<rect x="17" y="6" width="2" height="3" class="tintable"/>'
        '<rect x="3" y="9" width="2" height="1" class="tintable"/>'
        '<rect x="18" y="9" width="2" height="1" class="tintable"/>'
        '<rect x="2" y="10" width="19" height="1" class="tintable"/>'
        '<rect x="3" y="11" width="1" height="1" class="tintable"/>'
        '<rect x="19" y="11" width="1" height="1" class="tintable"/>'
        '<rect x="2" y="12" width="2" height="1" class="tintable"/>'
        '<rect x="19" y="12" width="2" height="1" class="tintable"/>'
        '<rect x="3" y="13" width="1" height="1" class="tintable"/>'
        '<rect x="7" y="14" width="1" height="1" class="tintable"/>'
        '<rect x="9" y="14" width="1" height="1" class="tintable"/>'
        '<rect x="11" y="14" width="1" height="1" class="tintable"/>'
        '<rect x="13" y="14" width="1" height="1" class="tintable"/>'
        '<rect x="15" y="14" width="1" height="1" class="tintable"/>'
        '<rect x="17" y="14" width="7" height="1" class="tintable"/>'
        '<rect x="19" y="13" width="1" height="1" class="tintable"/>'
        '<rect y="14" width="6" height="1" class="tintable"/>' '<rect y="15" width="24" height="3" class="tintable"/>'
        '<rect y="18" width="3" height="6" class="tintable"/>'
        '<rect x="3" y="20" width="1" height="4" class="tintable"/>'
        '<rect x="4" y="18" width="3" height="6" class="tintable"/>'
        '<rect x="7" y="21" width="1" height="3" class="tintable"/>'
        '<rect x="7" y="18" width="4" height="1" class="tintable"/>'
        '<rect x="8" y="19" width="3" height="5" class="tintable"/>'
        '<rect x="11" y="20" width="1" height="4" class="tintable"/>'
        '<rect x="12" y="18" width="3" height="6" class="tintable"/>'
        '<rect x="15" y="18" width="4" height="1" class="tintable"/>'
        '<rect x="16" y="19" width="3" height="1" class="tintable"/>'
        '<rect x="16" y="20" width="8" height="1" class="tintable"/>'
        '<rect x="20" y="18" width="4" height="2" class="tintable"/>'
        '<rect x="15" y="21" width="9" height="3" class="tintable"/>'
        '<rect x="7" y="5" width="1" height="1" fill="#2A46FF"/>'
        '<rect x="18" y="12" width="1" height="1" fill="#2A46FF"/>'
        '<rect x="16" y="14" width="1" height="1" fill="#2A46FF"/>'
        '<rect x="14" y="14" width="1" height="1" fill="#2A46FF"/>'
        '<rect x="12" y="14" width="1" height="1" fill="#2A46FF"/>'
        '<rect x="10" y="14" width="1" height="1" fill="#2A46FF"/>'
        '<rect x="8" y="14" width="1" height="1" fill="#2A46FF"/>'
        '<rect x="6" y="14" width="1" height="1" fill="#2A46FF"/>'
        '<rect x="5" y="12" width="1" height="1" fill="white"/>'
        '<rect x="7" y="12" width="1" height="1" fill="white"/>'
        '<rect x="9" y="12" width="1" height="1" fill="white"/>'
        '<rect x="11" y="12" width="1" height="1" fill="white"/>'
        '<rect x="13" y="12" width="1" height="1" fill="white"/>'
        '<rect x="15" y="12" width="1" height="1" fill="white"/>'
        '<rect x="17" y="12" width="1" height="1" fill="white"/>'
        '<rect x="6" y="12" width="1" height="1" fill="black"/>'
        '<rect x="8" y="12" width="1" height="1" fill="black"/>'
        '<rect x="10" y="12" width="1" height="1" fill="black"/>'
        '<rect x="12" y="12" width="1" height="1" fill="black"/>'
        '<rect x="14" y="12" width="1" height="1" fill="black"/>'
        '<rect x="16" y="12" width="1" height="1" fill="black"/>'
        '<rect x="3" y="18" width="1" height="2" fill="#2A46FF"/>'
        '<rect x="7" y="19" width="1" height="2" fill="#2A46FF"/>'
        '<rect x="11" y="18" width="1" height="2" fill="#2A46FF"/>'
        '<rect x="15" y="19" width="1" height="2" fill="#2A46FF"/>'
        '<rect x="19" y="18" width="1" height="2" fill="#2A46FF"/>'
        '<rect x="4" y="12" width="1" height="1" fill="#2A46FF"/>'
        '<rect x="5" y="9" width="13" height="1" fill="#2A46FF"/>'
        '<rect x="4" y="11" width="15" height="1" fill="#2A46FF"/>'
        '<rect x="4" y="13" width="15" height="1" fill="#2A46FF"/>'
        '<rect x="9" y="5" width="1" height="1" fill="#2A46FF"/>'
        '<rect x="11" y="5" width="1" height="1" fill="#2A46FF"/>'
        '<rect x="13" y="5" width="1" height="1" fill="#2A46FF"/>'
        '<rect x="15" y="5" width="1" height="1" fill="#2A46FF"/>'
        '<rect x="6" y="6" width="11" height="3" fill="#2A46FF"/>';
    }
}

// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

interface ICharacterSVGRenderer {
    function characterSVG(uint8 character) external pure returns (string memory);
}