// SPDX-License-Identifier: MIT
pragma solidity ^0.8.9;

import "@openzeppelin/contracts/utils/Strings.sol";

library Accessories {
  using Strings for uint256;
  string constant ACCESSORIES_ACCESSORY___BALL_AND_CHAIN =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAlQTFRFAAAANTU1////eV5mqQAAAAN0Uk5T//8A18oNQQAAAGhJREFUeNrs08sKgDAMRNGb/v9HK7EtLgRDBFc3y8Achj4YHwcBAQEBAQEBAQEBAYFfAaj7PO6WQB0gZ8fgvigAEDEDV6qa30BECtm/c4irAQNGD5idaV4j9VN7adB+SN28v/GcQ4ABAHvcH0/tVeZ+AAAAAElFTkSuQmCC";

  string constant ACCESSORIES_ACCESSORY___BAMBOO_SWORD =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABJQTFRFAAAAobSMbpZwNTU1//PC////9rlm+AAAAAZ0Uk5T//////8As7+kvwAAAIxJREFUeNrs1EEOwjAMRNHvabj/lWlZhG4sHEdCIE32fpbHSXhsHgwYMGDAgAED/wjAHkAEGwDEceQCn8tjB7jKQ+sjcGsvaTlEXh0r5RmgUyiVpyNotu9dJDRK7fMtMKJUngMaovcWmCm0HtOV3XsR68AtetQDNFfXHKGYfR4i/OSXZsCAgS8ATwEGAJ4MTc47vCuHAAAAAElFTkSuQmCC";

  string constant ACCESSORIES_ACCESSORY___BANHAMMER =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABJQTFRFAAAARUVFiW8+nIFNNTU1////WEZNygAAAAZ0Uk5T//////8As7+kvwAAAF1JREFUeNrs0zEOACEIBdEvsPe/8pK4ayxVCpuZjuZFjOopJgAAAAAAAAAAgBNAWQVQy3Qf0LzQvNMi4P6P3tMmYGbfaL1NIMahdbZClC4xMt18SPxGAACAxV4BBgAzOE6RHSKDeAAAAABJRU5ErkJggg==";

  string constant ACCESSORIES_ACCESSORY___BASKET_OF_EXCESS_USED_GRAPHICS_CARDS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABhQTFRFjGw9AAAAnIFNX19fNTU1i3hVUf9a////bzuQfgAAAAh0Uk5T/////////wDeg71ZAAAAc0lEQVR42uzUMQ6AMAwDwLhuy/9/TIKQKLDQILFgL5l88tLa8jImQIAAAQIECBAgQMCXQEMSQNnvU+EOeJFEFgArQIZAJIDoVtIcCGQa8FZ3wTal+5jMghAm+lfAxmSAMqRpQcssOE1A7i0c0Zf2I2AVYAC0CWwMgkb27wAAAABJRU5ErkJggg==";

  string constant ACCESSORIES_ACCESSORY___BEEHIVE_ON_A_STICK =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABhQTFRFOjYo2btHxKc3lcWT5ckmiW8+cVw0////0AhlCAAAAAh0Uk5T/////////wDeg71ZAAAAoElEQVR42uyUsRZDIQhDCUT6/39csKfja19x6RAGHdRLDKI9DsMEEEAAAQQQQAABBJgAIo4BMQFE5LojwT6kzVzrBXnPPwH21AxbKzNnHvQ5wB243Gjf/AdR4ZgoaB9QAG8JPgLUeiUHauTwHdRpeksYA7hN4OgKO9gGlIrpUzZ2GZ2wqYJ2kNdFuNFMJYBuJ93YFh5+KNSnKsDfA54CDABcam2fLMsYLAAAAABJRU5ErkJggg==";

  string constant ACCESSORIES_ACCESSORY___BLUE_BALLOON =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABJQTFRFUGv/AAAA////S2Lewcv/////3UEM/gAAAAZ0Uk5T//////8As7+kvwAAAIhJREFUeNrs1ksKwCAMBNCMn/tfuUpxIcGFGfDTJmvngSQRJZMlc8dRiwAgtWAG3nwvyFw+KWEOSMIA7QK9cCsQYe2Cyq8FmhBhH+VYC9QyBWqZihCQtwIq/0Ngfxd4QAkO3Ah8YRIdOAEwv4kgP5oIHKCf88XAOH8NMGyiYZAccMCBU4FHgAEALcxMUDaINK4AAAAASUVORK5CYII=";

  string constant ACCESSORIES_ACCESSORY___BLUE_BOXING_GLOVES =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABJQTFRFS2LeAAAAQFbNOk65UGv/////l5XVcAAAAAZ0Uk5T//////8As7+kvwAAAIBJREFUeNrs09sOgCAMA9C1zP//ZcFbIgxZ4mv72IyTqWjbz5gAAQIECBAgQICANQCy1GDsS9hbdhAlC7gdQaoegXtwBjgygLMXWs1whXiDJryBet5zwPUEJLpvM3kJM8A6wDyqvzZA2HMJnJNkCIx1dJVxJlnrdxYgQMCTXYABAJm2TLsHrFsVAAAAAElFTkSuQmCC";

  string constant ACCESSORIES_ACCESSORY___BLUE_FINGERNAIL_POLISH =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAZQTFRFUGv/////mbDXhwAAAAJ0Uk5T/wDltzBKAAAAPUlEQVR42uzRMQoAMAgDwPj/Txc6l1IQHMrpGi+DqeYEAAAAAAAAAACYAdKNZ+/xOI99F8AbAQDA18ASYADZ2w/1RrYn5QAAAABJRU5ErkJggg==";

  string constant ACCESSORIES_ACCESSORY___BLUE_GARDENER_TROWEL =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRFAAAAzs7Or6+vUGv/////pnagNQAAAAV0Uk5T/////wD7tg5TAAAAXklEQVR42uzSQQrAMAhE0VFz/zPXQLtoVrEJgcKflaunqGqLEQAAAAAAAAAAwK8AZVYAWWaC0Nj2BSRRAxRxVxGeMXNVJ9BT9P7u+r6DPkF9BxuvwCsDAAAcBy4BBgBd/D9Pz6sdCgAAAABJRU5ErkJggg==";

  string constant ACCESSORIES_ACCESSORY___BLUE_MERGE_BEARS_FOAM_FINGER =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFUGv/AAAAQFbN////p7KLPAAAAAR0Uk5T////AEAqqfQAAABpSURBVHja7NRBDoAgDETRMt7/zoKNQVeaDhvjn7DlpVBobGYCAAAAAAAAAADgAWi3VIC4pAao71RIKgM61lCqFcisII/gVGDewYou5Poq0N+yCZzfwQBmN34ODKF5I+3lPGKsA2R2AQYAuGQuEx6LJBMAAAAASUVORK5CYII=";

  string constant ACCESSORIES_ACCESSORY___BLUE_PURSE =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRFAAAAUGv/QFbN6sU3////+r7FoQAAAAV0Uk5T/////wD7tg5TAAAAUElEQVR42uzUIQ4AIAwEwaPl/28mIQ0KAycQ7PpOTlXdTAAAAAAAAAAAAH8DMgGFByi0PzgElvMEmN0DrXKATBPwFkT1bEFXxT8AANg3BBgAk4k+6UUWSXYAAAAASUVORK5CYII=";

  string constant ACCESSORIES_ACCESSORY___BLUE_SPATULA =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRFAAAAzs7OUGv/S2Le////To9UdgAAAAV0Uk5T/////wD7tg5TAAAAY0lEQVR42uzTMRKAMAhE0RVy/zMrGR21XOJYfapt8sJAorFYAgAAAAAAAAAA8ADN6gPaZskAHvepgAoOoIi4chyY3cELqLN2B5l5xsxOB+MeulozWN/Cx++AzwQAAPAvsAswAL6sPuEHbd5dAAAAAElFTkSuQmCC";

  string constant ACCESSORIES_ACCESSORY___BUCKET_OF_BLUE_PAINT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABVQTFRFAAAA////tLS0UGv/zs7OS2Le////pdOoIQAAAAd0Uk5T////////ABpLA0YAAABzSURBVHja7NRRCsAwCAPQGGvvf+TVwS5gYFBIKBSEPvTDYouBAQMGDBgwYMCAAQN/AsQQAL8bU+CtQAHYEQDmSXEOVL+vGgPB6nCNgTxDMEMA4hwFiAZC6yB0QByhG5gCG6uTC+NtRCchrnP6S7sKeAQYAOTbXaqRV41fAAAAAElFTkSuQmCC";

  string constant ACCESSORIES_ACCESSORY___BUCKET_OF_RED_PAINT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABVQTFRFAAAA////tLS0/1BZzs7O3ktT////nvWR5QAAAAd0Uk5T////////ABpLA0YAAABzSURBVHja7NRRCsAwCAPQGGvvf+TVwS5gYFBIKBSEPvTDYouBAQMGDBgwYMCAAQN/AsQQAL8bU+CtQAHYEQDmSXEOVL+vGgPB6nCNgTxDMEMA4hwFiAZC6yB0QByhG5gCG6uTC+NtRCchrnP6S7sKeAQYAOTbXaqRV41fAAAAAElFTkSuQmCC";

  string constant ACCESSORIES_ACCESSORY___BURNED_OUT_GRAPHICS_CARD =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABVQTFRF3H4x+sZdX19f3GIxNTU1Uf9a////weq1yAAAAAd0Uk5T////////ABpLA0YAAABiSURBVHja7NNBCoAwDETRGcfm/ke2BbciNrj7A1nmNSRU1YwAAAAAAAAAAL4DvmsbkMvaB1yS1QBkK9PYB9b7eR7hfQezO0kDcHLMdK6QY4wWoOYEpXOF3wgAAADwP3AJMAA5rl7xWBKYYwAAAABJRU5ErkJggg==";

  string constant ACCESSORIES_ACCESSORY___COLD_STORAGE_WALLET =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFkd//csHiv+z/////mxaC1QAAAAR0Uk5T////AEAqqfQAAABHSURBVHja7NPRCcBACATR0eu/55C0MHAQGPf/sYJy5BAQEBAQEBAQEPAnYBcwAHhgDTC2wfBGrfBFAvIO6BcCAgLuAo8AAwA73i+oUn+EFAAAAABJRU5ErkJggg==";

  string constant ACCESSORIES_ACCESSORY___DOUBLE_DUMBBELLS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFAAAAzs7OwsLC////pe1aBAAAAAR0Uk5T////AEAqqfQAAABeSURBVHja7NOxCoAwDEXRm/j//ywZulRNER0Ubqa8DAcepWwPBwEBAQEBAQEBgQUA9/a3AWpOwtV9BoiAGKn2oLsfgUzIkWpPuntfgbkC6wofeAX/goCAwM+BXYABAKA/LrfTSt8OAAAAAElFTkSuQmCC";

  string constant ACCESSORIES_ACCESSORY___FRESH_SALMON =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFAAAA05eWwYmJ////R5N01QAAAAR0Uk5T////AEAqqfQAAABwSURBVHja7NPRDoAgCIXhH3r/dw5qqdxF3dXxwo1NPpgo28uFAAECBAgQIEDAf4FyDroA2EyIwOgBkTEAi8CbHWTFCdT8O0DWtxWge4lA6cDoTgH30YJn8GAK7lf+EdB/B+fs112fSYAAAZ8DdgEGANnjL0UHvmSiAAAAAElFTkSuQmCC";

  string constant ACCESSORIES_ACCESSORY___HAND_IN_A_BLUE_COOKIE_JAR =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRFUGv/AAAAiW8+QFbN////OG/BHwAAAAV0Uk5T/////wD7tg5TAAAAbUlEQVR42uzUQQrAIAxE0Yzp/c9csWIXFqoJtJs/Kzc+Ehm0IxkDAAAAAAAAAAB4BTQd9gDZiJKAK7iC9/y0QrtfataFGSjqQhioUVl+xSdAbQLPTJACrG8QB64exYC7Rx5u4gg/EgDAt8ApwABVnz4SpDFC8gAAAABJRU5ErkJggg==";

  string constant ACCESSORIES_ACCESSORY___HAND_IN_A_RED_COOKIE_JAR =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRF/1BZAAAAiW8+zUBI////arMh7AAAAAV0Uk5T/////wD7tg5TAAAAbUlEQVR42uzUQQrAIAxE0Yzp/c9csWIXFqoJtJs/Kzc+Ehm0IxkDAAAAAAAAAAB4BTQd9gDZiJKAK7iC9/y0QrtfataFGSjqQhioUVl+xSdAbQLPTJACrG8QB64exYC7Rx5u4gg/EgDAt8ApwABVnz4SpDFC8gAAAABJRU5ErkJggg==";

  string constant ACCESSORIES_ACCESSORY___HOT_WALLET =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABJQTFRF3H4xnIFN3GIxiW8++sZd////EWHDYAAAAAZ0Uk5T//////8As7+kvwAAAGFJREFUeNrs00kOwCAMQ1E3hPtfuYm6RkC9/VaW8GQxaJoRAAAAAAAAAMA5oJkWkOoxACl1UELrAlHEvsNyQe+vcYCIEn6fwXgqEWkCMhvIuMYPMB7S6PAbAQAAAO7yCjAADUtPC7EwRw0AAAAASUVORK5CYII=";

  string constant ACCESSORIES_ACCESSORY___MINERS_PICKAXE =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABVQTFRFAAAAoKCgnIFNiW8+gICAzs7O////i+d05QAAAAd0Uk5T////////ABpLA0YAAACnSURBVHja7NVLDoAwCATQabHe/8gWNcakP1pWmunOKC8IiNidBwQIECBAgMAXAAAuACklI9HMIBiJ5jMISniKiC0T8HRBhQBPG01C974KDgAQQwrtLiDGKNs6EPXI+CV6gAg8gIafdVwE5BrkDPSnCa1rPCM9A+TSV2bBDmjnSsEMnJ3PtStSMAJ3eLEEZoBK+HBtvoB6+MTnjKUNzT8TAQK/AQ4BBgCyFV0iMuGRkwAAAABJRU5ErkJggg==";

  string constant ACCESSORIES_ACCESSORY___NINJA_SWORDS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRFRUVFWlpaAAAA////5iQ6MgAAAAR0Uk5T////AEAqqfQAAAB3SURBVHja7NNLDoAgDADRAe5/Z0FXQhsxJq6GJW0f5Uf7OBAQEBCIgLrFUVOAHWFKor0U5hSCMIky5pclWBaopF0wok+30OtLBhTuBxgCvb4kQg+s3RHUEwtngKctcCXGGxgwGy8xPwN/o4CAgICAgIDAP8AhwABhiC9FBnlWjwAAAABJRU5ErkJggg==";

  string constant ACCESSORIES_ACCESSORY___NONE =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAZQTFRF////AAAAVcLTfgAAAAF0Uk5TAEDm2GYAAAAdSURBVHja7MGBAAAAAMOg+VPf4ARVAQAAAHwTYAAQQAABpAJfkQAAAABJRU5ErkJggg==";

  string constant ACCESSORIES_ACCESSORY___PHISHING_NET =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRFAAAAzs7OiW8+nIFN////17HmAwAAAAV0Uk5T/////wD7tg5TAAAAhklEQVR42uzUMQ7AIAxDURNy/zM3JAwtUzETkpn5T64qAT88EHAngDgnAHoc8AC6NTcDC2QfAgvMvh0A2dMLYkD1PDD7RgOzd/4TqucXmGVPLhh9/QVuwat3FoAfLBgDsPYbQPaOpd8DxmV8+/9ADaj3hHyRDHqVBQgQIECAAAECbgEeAQYAIro+ZrPFMXwAAAAASUVORK5CYII=";

  string constant ACCESSORIES_ACCESSORY___PHISHING_ROD =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABhQTFRFAAAAiW8+nIFN////pqam6Jr/lpaW////PqdPKAAAAAh0Uk5T/////////wDeg71ZAAAA30lEQVR42uzWQRbCIAxF0QdS2f+OhYJWWlqTcJwonf+blAAH4uDHBCYwgb8GgBEAvHOYgRT3jpsZyHGHGSjdE61AjUcjkMvX5bcAzdobgHXtt5QWaEevB8rsohnI5Zu8DuA1PBtwaF8JHNtXAb32NUC3fTlAv30xUA9utALn5WUA5+VlgD8vLwMu86JfuJ6v/VL9PsAgkHbPELDuvgEg50PADJS8ROgDa/8h3IUAe6CeviSIABZa4Hl5wGeAZTkAb5ePIE8m2l/AXR+fHbCdFXrvHs3Daj40J/AjwEOAAQAGmmh85Os/qAAAAABJRU5ErkJggg==";

  string constant ACCESSORIES_ACCESSORY___PICNIC_BASKET_WITH_BLUE_AND_WHITE_BLANKET =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABJQTFRFAAAAnIFNiW8+UGv/////////nmBe/wAAAAZ0Uk5T//////8As7+kvwAAAIFJREFUeNrs1EsOgDAIBNCBtve/slTwk7iRstLMGBM2vE4aI0YxIECAAAECBAgQIPBlAKgBEC0Bto8YsAbE/jWkG2AUGgB2cGQOWQCtN7HXH5uQBXpT1difUxpoMuPnW5C/A93j56suAOLxJusNjuSBs8KzwOsP6Rb+kQj8EtgEGABWyU2k+mn+MgAAAABJRU5ErkJggg==";

  string constant ACCESSORIES_ACCESSORY___PICNIC_BASKET_WITH_RED_AND_WHITE_BLANKET =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABJQTFRFAAAAnIFNiW8+/1BZ////////WaG6vQAAAAZ0Uk5T//////8As7+kvwAAAIFJREFUeNrs1EsOgDAIBNCBtve/slTwk7iRstLMGBM2vE4aI0YxIECAAAECBAgQIPBlAKgBEC0Bto8YsAbE/jWkG2AUGgB2cGQOWQCtN7HXH5uQBXpT1difUxpoMuPnW5C/A93j56suAOLxJusNjuSBs8KzwOsP6Rb+kQj8EtgEGABWyU2k+mn+MgAAAABJRU5ErkJggg==";

  string constant ACCESSORIES_ACCESSORY___PINK_FINGERNAIL_POLISH =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAZQTFRF6Jr/////Gn0/cgAAAAJ0Uk5T/wDltzBKAAAAPUlEQVR42uzRMQoAMAgDwPj/Txc6l1IQHMrpGi+DqeYEAAAAAAAAAACYAdKNZ+/xOI99F8AbAQDA18ASYADZ2w/1RrYn5QAAAABJRU5ErkJggg==";

  string constant ACCESSORIES_ACCESSORY___PINK_PURSE =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRFAAAA6Jr/6sU3yqLV////gFKrOAAAAAV0Uk5T/////wD7tg5TAAAAUElEQVR42uzUIQ4AIAwEwaPw/zeTkAZVAycQ7PpOTlXDTAAAAAAAAAAAAH8DMgGFByhUHxwC23kCrO6BljlAhAl4C3r2bMFQxj8AAKibAgwAqFQ+700k2ukAAAAASUVORK5CYII=";

  string constant ACCESSORIES_ACCESSORY___PROOF_OF_RIBEYE_STEAK =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABJQTFRFAAAAlkBAjVhNq3Jy4dzH////6hv7jQAAAAZ0Uk5T//////8As7+kvwAAAGJJREFUeNrs0zEOACEIRNEB9P5XXuyJIVJs86F1Xoio9rAEAAAAAAAAAAAA8CugGSD5CJC7WX1cvXyYRbY/AxaHKPL9CVY9QHuClV3l25eY+Qlw1uBlvv2QlMVvBAC41CfAACltTwmqMus0AAAAAElFTkSuQmCC";

  string constant ACCESSORIES_ACCESSORY___RED_BALLOON =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABJQTFRF/1BZAAAA////3ktT/8HF////KJQlUAAAAAZ0Uk5T//////8As7+kvwAAAIhJREFUeNrs1ksKwCAMBNCMn/tfuUpxIcGFGfDTJmvngSQRJZMlc8dRiwAgtWAG3nwvyFw+KWEOSMIA7QK9cCsQYe2Cyq8FmhBhH+VYC9QyBWqZihCQtwIq/0Ngfxd4QAkO3Ah8YRIdOAEwv4kgP5oIHKCf88XAOH8NMGyiYZAccMCBU4FHgAEALcxMUDaINK4AAAAASUVORK5CYII=";

  string constant ACCESSORIES_ACCESSORY___RED_BOXING_GLOVES =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAABJQTFRF3ktTAAAAuTpBzUBI/1BZ////5XnPCAAAAAZ0Uk5T//////8As7+kvwAAAHlJREFUeNrs0zsOwCAMA9AYp/e/cilIHSCUoK72aEVPER+7fsYECBAgQIAAAQIE7AGQpQZzX8LesoMoWcB6kKpnAP4NOHZAm+IoPDXDFUKgCSNAPwDqODHcjdsRMG2wOJs1sDhEInmNRKqOnjJ6krW+swABAt7cAgwAkflMjo47aC0AAAAASUVORK5CYII=";

  string constant ACCESSORIES_ACCESSORY___RED_FINGERNAIL_POLISH =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAZQTFRF/1BZ////zwu78gAAAAJ0Uk5T/wDltzBKAAAAPUlEQVR42uzRMQoAMAgDwPj/Txc6l1IQHMrpGi+DqeYEAAAAAAAAAACYAdKNZ+/xOI99F8AbAQDA18ASYADZ2w/1RrYn5QAAAABJRU5ErkJggg==";

  string constant ACCESSORIES_ACCESSORY___RED_GARDENER_TROWEL =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRFAAAAzs7Or6+v/1BZ////8M3MQAAAAAV0Uk5T/////wD7tg5TAAAAXklEQVR42uzSQQrAMAhE0VFz/zPXQLtoVrEJgcKflaunqGqLEQAAAAAAAAAAwK8AZVYAWWaC0Nj2BSRRAxRxVxGeMXNVJ9BT9P7u+r6DPkF9BxuvwCsDAAAcBy4BBgBd/D9Pz6sdCgAAAABJRU5ErkJggg==";

  string constant ACCESSORIES_ACCESSORY___RED_MERGE_BEARS_FOAM_FINGER =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF/1BZAAAAzUBI////ldQ1tgAAAAR0Uk5T////AEAqqfQAAABpSURBVHja7NRBDoAgDETRMt7/zoKNQVeaDhvjn7DlpVBobGYCAAAAAAAAAADgAWi3VIC4pAao71RIKgM61lCqFcisII/gVGDewYou5Poq0N+yCZzfwQBmN34ODKF5I+3lPGKsA2R2AQYAuGQuEx6LJBMAAAAASUVORK5CYII=";

  string constant ACCESSORIES_ACCESSORY___RED_PURSE =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRFAAAA/1BZzUBI6sU3////qDFC5wAAAAV0Uk5T/////wD7tg5TAAAAUElEQVR42uzUIQ4AIAwEwaPl/28mIQ0KAycQ7PpOTlXdTAAAAAAAAAAAAH8DMgGFByi0PzgElvMEmN0DrXKATBPwFkT1bEFXxT8AANg3BBgAk4k+6UUWSXYAAAAASUVORK5CYII=";

  string constant ACCESSORIES_ACCESSORY___RED_SPATULA =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA9QTFRFAAAAzs7O/1BZ3ktT////FwcUVwAAAAV0Uk5T/////wD7tg5TAAAAY0lEQVR42uzTMRKAMAhE0RVy/zMrGR21XOJYfapt8sJAorFYAgAAAAAAAAAA8ADN6gPaZskAHvepgAoOoIi4chyY3cELqLN2B5l5xsxOB+MeulozWN/Cx++AzwQAAPAvsAswAL6sPuEHbd5dAAAAAElFTkSuQmCC";

  string constant ACCESSORIES_ACCESSORY___TOILET_PAPER =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAxQTFRF////AAAAzs7O////E2eUFAAAAAR0Uk5T////AEAqqfQAAABjSURBVHja7NQxDsAwCENRTO9/55auoVIcpkrfO8+EIXENEwAAAAAAAAAAAAAGoCkQmgK7wgcQeQ4oKhMgX2HwBGXl/Ihy+hvg6XfmG8BbYAFqfv8AK+D2NxtU+A8A/gfcAgwAZUAvUaKkyVoAAAAASUVORK5CYII=";

  string constant ACCESSORIES_ACCESSORY___WOODEN_WALKING_CANE =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAAlQTFRFAAAAiW8+////sfTlzAAAAAN0Uk5T//8A18oNQQAAAElJREFUeNrs1DEOACAIBMGF/z/aGD+goJVLQcckR3FkcxAQEBAQEBAQEBD4BCDmDqoA65Rt4RWQ3Qj1JwoICFwCjjuu3YlDgAEA4kIfmE6EbaEAAAAASUVORK5CYII=";

  function getAsset(uint256 assetNum) external pure returns (string memory) {
    if (assetNum == 0) {
      return ACCESSORIES_ACCESSORY___BALL_AND_CHAIN;
    } else if (assetNum == 1) {
      return ACCESSORIES_ACCESSORY___BAMBOO_SWORD;
    } else if (assetNum == 2) {
      return ACCESSORIES_ACCESSORY___BANHAMMER;
    } else if (assetNum == 3) {
      return ACCESSORIES_ACCESSORY___BASKET_OF_EXCESS_USED_GRAPHICS_CARDS;
    } else if (assetNum == 4) {
      return ACCESSORIES_ACCESSORY___BEEHIVE_ON_A_STICK;
    } else if (assetNum == 5) {
      return ACCESSORIES_ACCESSORY___BLUE_BALLOON;
    } else if (assetNum == 6) {
      return ACCESSORIES_ACCESSORY___BLUE_BOXING_GLOVES;
    } else if (assetNum == 7) {
      return ACCESSORIES_ACCESSORY___BLUE_FINGERNAIL_POLISH;
    } else if (assetNum == 8) {
      return ACCESSORIES_ACCESSORY___BLUE_GARDENER_TROWEL;
    } else if (assetNum == 9) {
      return ACCESSORIES_ACCESSORY___BLUE_MERGE_BEARS_FOAM_FINGER;
    } else if (assetNum == 10) {
      return ACCESSORIES_ACCESSORY___BLUE_PURSE;
    } else if (assetNum == 11) {
      return ACCESSORIES_ACCESSORY___BLUE_SPATULA;
    } else if (assetNum == 12) {
      return ACCESSORIES_ACCESSORY___BUCKET_OF_BLUE_PAINT;
    } else if (assetNum == 13) {
      return ACCESSORIES_ACCESSORY___BUCKET_OF_RED_PAINT;
    } else if (assetNum == 14) {
      return ACCESSORIES_ACCESSORY___BURNED_OUT_GRAPHICS_CARD;
    } else if (assetNum == 15) {
      return ACCESSORIES_ACCESSORY___COLD_STORAGE_WALLET;
    } else if (assetNum == 16) {
      return ACCESSORIES_ACCESSORY___DOUBLE_DUMBBELLS;
    } else if (assetNum == 17) {
      return ACCESSORIES_ACCESSORY___FRESH_SALMON;
    } else if (assetNum == 18) {
      return ACCESSORIES_ACCESSORY___HAND_IN_A_BLUE_COOKIE_JAR;
    } else if (assetNum == 19) {
      return ACCESSORIES_ACCESSORY___HAND_IN_A_RED_COOKIE_JAR;
    } else if (assetNum == 20) {
      return ACCESSORIES_ACCESSORY___HOT_WALLET;
    } else if (assetNum == 21) {
      return ACCESSORIES_ACCESSORY___MINERS_PICKAXE;
    } else if (assetNum == 22) {
      return ACCESSORIES_ACCESSORY___NINJA_SWORDS;
    } else if (assetNum == 23) {
      return ACCESSORIES_ACCESSORY___NONE;
    } else if (assetNum == 24) {
      return ACCESSORIES_ACCESSORY___PHISHING_NET;
    } else if (assetNum == 25) {
      return ACCESSORIES_ACCESSORY___PHISHING_ROD;
    } else if (assetNum == 26) {
      return ACCESSORIES_ACCESSORY___PICNIC_BASKET_WITH_BLUE_AND_WHITE_BLANKET;
    } else if (assetNum == 27) {
      return ACCESSORIES_ACCESSORY___PICNIC_BASKET_WITH_RED_AND_WHITE_BLANKET;
    } else if (assetNum == 28) {
      return ACCESSORIES_ACCESSORY___PINK_FINGERNAIL_POLISH;
    } else if (assetNum == 29) {
      return ACCESSORIES_ACCESSORY___PINK_PURSE;
    } else if (assetNum == 30) {
      return ACCESSORIES_ACCESSORY___PROOF_OF_RIBEYE_STEAK;
    } else if (assetNum == 31) {
      return ACCESSORIES_ACCESSORY___RED_BALLOON;
    } else if (assetNum == 32) {
      return ACCESSORIES_ACCESSORY___RED_BOXING_GLOVES;
    } else if (assetNum == 33) {
      return ACCESSORIES_ACCESSORY___RED_FINGERNAIL_POLISH;
    } else if (assetNum == 34) {
      return ACCESSORIES_ACCESSORY___RED_GARDENER_TROWEL;
    } else if (assetNum == 35) {
      return ACCESSORIES_ACCESSORY___RED_MERGE_BEARS_FOAM_FINGER;
    } else if (assetNum == 36) {
      return ACCESSORIES_ACCESSORY___RED_PURSE;
    } else if (assetNum == 37) {
      return ACCESSORIES_ACCESSORY___RED_SPATULA;
    } else if (assetNum == 38) {
      return ACCESSORIES_ACCESSORY___TOILET_PAPER;
    } else if (assetNum == 39) {
      return ACCESSORIES_ACCESSORY___WOODEN_WALKING_CANE;
    }
    return ACCESSORIES_ACCESSORY___NONE;
  }
}

// SPDX-License-Identifier: MIT
// OpenZeppelin Contracts (last updated v4.7.0) (utils/Strings.sol)

pragma solidity ^0.8.0;

/**
 * @dev String operations.
 */
library Strings {
    bytes16 private constant _HEX_SYMBOLS = "0123456789abcdef";
    uint8 private constant _ADDRESS_LENGTH = 20;

    /**
     * @dev Converts a `uint256` to its ASCII `string` decimal representation.
     */
    function toString(uint256 value) internal pure returns (string memory) {
        // Inspired by OraclizeAPI's implementation - MIT licence
        // https://github.com/oraclize/ethereum-api/blob/b42146b063c7d6ee1358846c198246239e9360e8/oraclizeAPI_0.4.25.sol

        if (value == 0) {
            return "0";
        }
        uint256 temp = value;
        uint256 digits;
        while (temp != 0) {
            digits++;
            temp /= 10;
        }
        bytes memory buffer = new bytes(digits);
        while (value != 0) {
            digits -= 1;
            buffer[digits] = bytes1(uint8(48 + uint256(value % 10)));
            value /= 10;
        }
        return string(buffer);
    }

    /**
     * @dev Converts a `uint256` to its ASCII `string` hexadecimal representation.
     */
    function toHexString(uint256 value) internal pure returns (string memory) {
        if (value == 0) {
            return "0x00";
        }
        uint256 temp = value;
        uint256 length = 0;
        while (temp != 0) {
            length++;
            temp >>= 8;
        }
        return toHexString(value, length);
    }

    /**
     * @dev Converts a `uint256` to its ASCII `string` hexadecimal representation with fixed length.
     */
    function toHexString(uint256 value, uint256 length) internal pure returns (string memory) {
        bytes memory buffer = new bytes(2 * length + 2);
        buffer[0] = "0";
        buffer[1] = "x";
        for (uint256 i = 2 * length + 1; i > 1; --i) {
            buffer[i] = _HEX_SYMBOLS[value & 0xf];
            value >>= 4;
        }
        require(value == 0, "Strings: hex length insufficient");
        return string(buffer);
    }

    /**
     * @dev Converts an `address` with fixed length of 20 bytes to its not checksummed ASCII `string` hexadecimal representation.
     */
    function toHexString(address addr) internal pure returns (string memory) {
        return toHexString(uint256(uint160(addr)), _ADDRESS_LENGTH);
    }
}